### ISSUE TITLE
BootstrapGenericPanel improvements

### ISSUE THREAD

**Issue by vrozkovec** [l0rdn1kk0n/wicket-bootstrap#1006]
Hi, would you be interested in improving [`BootstrapGenericPanel`](https://github.com/l0rdn1kk0n/wicket-bootstrap/tree/wicket-10.x-bootstrap-5.x/bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/panel) for BS 5.x branch in a way, that would allow easy setting of panel style via either constructor or `withStyle(PanelStyle style)` method? Style would be optional, enum constant values: Default, Primary, Secondary, Success, Danger, Warning, Info, Light, Dark.

I'm just migrating my codebase from Wicket 8.x and Bootstrap 3 to Wicket 10.x and Bootstrap 5 and this would help the transition from BS panels to cards that happened at BS v4 and generally it could come handy for someone else. 

I'm also thinking about improving this panel a bit further by allowing setting custom color, background and border for its header, body and footer. What do you think?

**Comment by martin-g** [comment]
Sounds good to me!

**Comment by vrozkovec** [comment]
Opened PR #1016
