### ISSUE TITLE
Project URL on github project page is dead

### ISSUE THREAD

**Issue by sebthom** [l0rdn1kk0n/wicket-bootstrap#1028]
Maybe replace http://wb-mgrigorov.rhcloud.com/ with https://wicketbootstrap.teliclab.info/

![image](https://github.com/l0rdn1kk0n/wicket-bootstrap/assets/426959/3b61147f-c32b-469f-a6e0-cb71c2b73f7f)

**Comment by martin-g** [comment]
PR please

**Comment by sebthom** [comment]
That is a github project setting. that is not possible via PR.

**Comment by reckart** [comment]
Sounds like that may fall into the category of things where repo access level is insufficient...?

Cf. https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/1026#issuecomment-1875398013

**Comment by sebthom** [comment]
Maybe it's time to (hard)fork the repo and put it under e.g. wicketstuff? l0rdn1kk0n doesn't seem to have been active on github for years.

**Comment by chrisco484** [comment]
> Maybe it's time to (hard)fork the repo and put it under e.g. wicketstuff? l0rdn1kk0n doesn't seem to have been active on github for years.

+1

**Comment by solomax** [comment]
@sebthom would you like to move it to `wicketstuff/core` or make top level subproject of `wicketstuff`?

**Comment by chrisco484** [comment]
> @sebthom would you like to move it to `wicketstuff/core` or make top level subproject of `wicketstuff`?

Given that it's an 'all encompassing' Wicket project - i.e. if affects the look and feel of all components regardless of which project they're in - maybe it's worthy of being a top level subproject of 'wicketstuff'.

**Comment by solomax** [comment]
sounds reasonable :)

**Comment by reckart** [comment]
+1 for separate project in the wicketstuff org :)

**Comment by martin-g** [comment]
I've asked @l0rdn1kk0n to move the project!
If nothing happens until 23.01.2024 I will try to do it manually! Any help/references how to do it are welcome!
What about wicket-jquery-selectors and wicket-webjars ?

**Comment by martin-g** [comment]
The projects have been moved to my account!
This should be good enough for the time being!

**Comment by martin-g** [comment]
Fixed!
Thanks!
