### ISSUE TITLE
wicket-bootstrap-sass in Maven central repository contains dependency to ua.kasta:jsass instead of io.bit3:jsass

### ISSUE THREAD

**Issue by VaclavC** [l0rdn1kk0n/wicket-bootstrap#1029]
If I open [wicket-bootstrap-sass in Maven central](https://central.sonatype.com/artifact/de.agilecoders.wicket/wicket-bootstrap-sass) there is a dependency to ua.kasta:jsass which can't be found in repository. I'am not sure, where is the problem?

**Comment by reckart** [comment]
That is interesting. Normally, libraries do not disappear from Maven Central.

That said, a new version of io.bit3:jsass has ben released. If you use an older version of Wicket, you can exclude the ua.kasta version and instead depend manually on

```
<dependency>
  <groupId>io.bit3</groupId>
  <artifactId>jsass</artifactId>
  <version>5.11.0</version>
</dependency>
```

For the `wicket-9.x-bootstrap-5.x` branch, there was already a PR to cross-grade: https://github.com/martin-g/wicket-bootstrap/pull/1026

... but it still needs to be incorporated into other current branches...

**Comment by VaclavC** [comment]
Yes, it is, but if I search for jsass, there is no ua.kasta one: https://central.sonatype.com/search?q=jsass

I'am working with Wicket 10 version. Here on Gihtub I can see correct io.bit3 in relevant pom.xml, but on Maven central there is still ua.kasta.

**Comment by reckart** [comment]
It appears the ua.kasta was on Maven Central for quite a while. I do not know why it was pulled. Feel free to open a PR against the Wicket 10 branch to switch to the io.bit3 version. You can probably just open a PR with a cherry-pick of https://github.com/martin-g/wicket-bootstrap/pull/1026

**Comment by martin-g** [comment]
Here is the explanation how it works:
- https://central.sonatype.com/artifact/de.agilecoders.wicket/bootstrap-parent (v7.0.1) has:
```
 <repository>
            <id>repo.clojars.org</id>
            <url>https://repo.clojars.org</url>
        </repository>
```
- https://repo.clojars.org/ua/kasta/jsass/ provides the jar

No magic!

**Comment by reckart** [comment]
Oh, I had been quite sure it was on Maven Central as well - must have been dreaming :) Thanks @martin-g for clearing this up.
