### ISSUE TITLE
How to load JS resources in an orderly fashion ?

### ISSUE THREAD

**Issue by sundarsabapathi** [l0rdn1kk0n/wicket-bootstrap#1030]
Hi all, I am using wicket bootstrap in my Application. Bootstrap resources are loaded automatically through the wicket-bootstrap library in the init method of the WebApplication class like this:

```
BootstrapSettings settings = new BootstrapSettings();
Bootstrap.install(this, settings); BootstrapSass.install(this);
```

 I am using an Abstract page to load other JS resources and all the other pages extend this page. I want one of my JS resources to load after the bootstrap JS resources are loaded . Kindly advice how to achieve this

**Comment by martin-g** [comment]
You have been answered at users@wicket.apache.org: https://lists.apache.org/thread/qpbognx648czgty73wpzn92ndswnl1vr 10 days ago.
Please also consult with https://nightlies.apache.org/wicket/guide/9.x/single.html#_resource_dependencies
