### ISSUE TITLE
Dropdown submenus 

### ISSUE THREAD

**Issue by torse** [l0rdn1kk0n/wicket-bootstrap#1031]
It would be nice to support dropdown submenus like in this example:
https://mdbootstrap.com/docs/standard/extended/dropdown-multilevel/#section-button-dropdown-on-hover

It has been implemented in an older version but seems to be missing now:
https://github.com/martin-g/wicket-bootstrap/commit/8f99b8afa7b06a66220649a8f61399a54a711f91

Are there any plans to restore the submenu functionality into the current codebase?

**Comment by martin-g** [comment]
I did some archeology. The functionality has been removed with https://github.com/martin-g/wicket-bootstrap/commit/e9cd53817a5462177a81b93653503471a148d054 because Bootstrap itself dropped it.

I don't mind re-adding it in -extensions if you provide a PR!

**Comment by martin-g** [comment]
Also see https://bootstrap-menu.com/detail-multilevel.html
