### ISSUE TITLE
Please update bootwatch theme to 5.3.3/5.3.4

### ISSUE THREAD

**Issue by r1gm** [l0rdn1kk0n/wicket-bootstrap#1118]
Hi, 

Please update bootwatch theme css to 5.3.3/5.3.4

i encounter problem especially cerulean theme  

.bg-danger .h1, .bg-danger .h2, .bg-danger .h3, .bg-danger .h4, .bg-danger .h5, .bg-danger .h6, .bg-danger h1, .bg-danger h2, .bg-danger h3, .bg-danger h4, .bg-danger h5, .bg-danger h6, .bg-dark .h1, .bg-dark .h2, .bg-dark .h3, .bg-dark .h4, .bg-dark .h5, .bg-dark .h6, .bg-dark h1, .bg-dark h2, .bg-dark h3, .bg-dark h4, .bg-dark h5, .bg-dark h6, .bg-info .h1, .bg-info .h2, .bg-info .h3, .bg-info .h4, .bg-info .h5, .bg-info .h6, .bg-info h1, .bg-info h2, .bg-info h3, .bg-info h4, .bg-info h5, .bg-info h6, .bg-primary .h1, .bg-primary .h2, .bg-primary .h3, .bg-primary .h4, .bg-primary .h5, .bg-primary .h6, .bg-primary h1, .bg-primary h2, .bg-primary h3, .bg-primary h4, .bg-primary h5, .bg-primary h6, .bg-success .h1, .bg-success .h2, .bg-success .h3, .bg-success .h4, .bg-success .h5, .bg-success .h6, .bg-success h1, .bg-success h2, .bg-success h3, .bg-success h4, .bg-success h5, .bg-success h6, .bg-warning .h1, .bg-warning .h2, .bg-warning .h3, .bg-warning .h4, .bg-warning .h5, .bg-warning .h6, .bg-warning h1, .bg-warning h2, .bg-warning h3, .bg-warning h4, .bg-warning h5, .bg-warning h6 {
  color: #fff;
}

when using firefox Web Developer Tools to inspect the theme resetting the color to white.

For Note : 
I'm using Wicket-Bootstrap 7.0.5 with Wicket 10.1.0

Best Regards,
Erwan

**Comment by martin-g** [comment]
Fixed with #1119
