### ISSUE TITLE
integrate jsfeedback

### ISSUE THREAD

**Issue by sadiq81** [l0rdn1kk0n/wicket-bootstrap#210]
This is actually a feature request.

I saw a great concept of sending feedback back to the server using js.

Take a look an see you think its interesting.

http://experiments.hertzen.com/jsfeedback/

**Comment by JavaLuigi** [comment]
Yes, it looks interesting but it's not maintained. The last commit is 3 years ago.

**Comment by martin-g** [comment]
Closing the issue due to lack of interest to it.
