### ISSUE TITLE
Update Website agilecoders.de

### ISSUE THREAD

**Issue by JavaLuigi** [l0rdn1kk0n/wicket-bootstrap#321]
Hi there,

it would be helpful for newbies when the website was kept into an actual state. What is the problem to update aglilecoders.de to Bootstrap 3.0.3? 

If you need help, no problem feel free to ask me.

Kind regards
Ludger

**Comment by klopfdreh** [comment]
**+1 to update the site** - there are so many changes in the current version (master / 7.x) and it would be greate to demonstrate the new features.

**Comment by martin-g** [comment]
As the description of the project at https://github.com/l0rdn1kk0n/wicket-bootstrap says the new demo site is: http://wb-mgrigorov.rhcloud.com/.
It uses latest 0.10.x branch, i.e. 7.x.

I think this ticket could be closed now.

**Comment by klopfdreh** [comment]
Maybe agilecoders site can redirect to the current updated one, because Google lists the outdated one at first position.

**Comment by JavaLuigi** [comment]
+1 to redirect
