### ISSUE TITLE
DropZone - modern file uploader

### ISSUE THREAD

**Issue by martin-g** [l0rdn1kk0n/wicket-bootstrap#371]
It seems http://www.dropzonejs.com/bootstrap.html provides what http://blueimp.github.io/jQuery-File-Upload/ was missing (see http://wicketinaction.com/2012/11/uploading-files-to-wicket-iresource/).

Do we want integration with it ?
Please vote if you want it integrated.

P.S. The minimal IE version that it supports is IE10.

**Comment by damienhollis** [comment]
+1 this would be great

**Comment by klopfdreh** [comment]
I am working on it and create a pull request when it's done.

**Comment by klopfdreh** [comment]
See also the following commits:

https://github.com/klopfdreh/wicket-bootstrap/commits/master

and a request to allow multipart in AbstractDefaultAjaxEventBehavior:

http://apache-wicket.1842946.n4.nabble.com/Change-AbstractDefaultAjaxBehavior-to-allow-multipart-td4670748.html

**Comment by klopfdreh** [comment]
Hi Martin - I think this can be closed, now. :-)

**Comment by martin-g** [comment]
Thank you for the contribution, Tobias!
