### ISSUE TITLE
Consider replacing JQuery UI for dragging and resizing with Interact.js

### ISSUE THREAD

**Issue by martin-g** [l0rdn1kk0n/wicket-bootstrap#466]
Currently we use JQuery UI for Draggable and Resizable behaviors.

The benefit of using http://interactjs.io/ are:
- lighter (much less resources)
- support for touch devices
- support for SVG

See https://hacks.mozilla.org/2014/11/interact-js-for-drag-and-drop-resizing-and-multi-touch-gestures/

**Comment by klopfdreh** [comment]
@martin-g - only the first try - I think we should discuss what to implement for the config.

My suggestions would be:
* snapping (http://interactjs.io/docs/snapping/#snapping)
* snapping grids (http://interactjs.io/docs/snapping/#snap-grids)
* autoscroll (http://interactjs.io/docs/#autoscroll)
* inertia (http://interactjs.io/docs/#inertia)
* maxPerElement (http://interactjs.io/docs/#maxperelement)

What do you think?

**Comment by martin-g** [comment]
I thought that I've closed this issue as "Won't bother".
For my last project I needed to use jQuery UI Sortable, so I've did some research before that and IMO jQuery UI Sortable is much simpler and easier to use.
jQuery UI is not very live project at the moment. I'm not sure what will happen with it in the future but for now I think it is the better choice for this kind of tasks.

**Comment by klopfdreh** [comment]
Mh, the integration itself is not far from finish state, so what speaks against integrating it in addition to jQuery UI.
