### ISSUE TITLE
Change a less/css property at runtime

### ISSUE THREAD

**Issue by sisao** [l0rdn1kk0n/wicket-bootstrap#482]
Hi,

Is it possible to change a less variable at runtime and recompile the less file?
I found this https://cwiki.apache.org/confluence/display/WICKET/Dynamically+Generate+a+CSS+Stylesheet but its from 2010 and I'm not sure if it works with the less feature...

thx and regards
Stefan

**Comment by martin-g** [comment]
Hi,

You mean to create the Less resource programmatically, right ?
This is not supported at the moment. 
The functionality that is supported is: you can edit the variable manually and the change should be picked.

Please provide a quickstart application I can play with and I'll see what can be done.

**Comment by sisao** [comment]
See https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/489
