### ISSUE TITLE
Add integration for http://eonasdan.github.io/bootstrap-datetimepicker/

### ISSUE THREAD

**Issue by martin-g** [l0rdn1kk0n/wicket-bootstrap#487]
http://eonasdan.github.io/bootstrap-datetimepicker/ provides date+**time** picker.

**Comment by martin-g** [comment]
@lehvolk Are you interested to make the integration ?

**Comment by lehvolk** [comment]
Yes, I'm. 

PS I have strong deadline for my daily job in the end of January. I don't think I have enought time for contribution till the end of deadline.

**Comment by martin-g** [comment]
Same here.
Add a comment here when you start working on this. Just to avoid working both on the same this. I'll do the same.
Thank you!

**Comment by lehvolk** [comment]
Deal.

**Comment by lehvolk** [comment]
I start the integration.

**Comment by martin-g** [comment]
OK. Thanks!

**Comment by lehvolk** [comment]
I have strange issue with glyphicons. Calendar icon not display properly, but other icons seems displayed correctly. This affects the presentation of datetime widget. Maybe there is a conflict between glyphicons and bootstrap versions? Do you have any suggestions of such behavior?

**Comment by martin-g** [comment]
I have faced this issue when the markup snippet is not as the expected one.
In my project I use:
https://github.com/apache/isis/blob/master/component/viewer/wicket/ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/scalars/ScalarPanelTextFieldAbstract.html#L38

**Comment by lehvolk** [comment]
I find bug - Jasny components has dependencies to Bootstrap css 2.2.2 version which conflicts with Bootstrap version from BootstrapSettings. I think we should replace JasnyCssReference.INSTANCE with css reference from BootstrapSettings. Jasny uses Bootstrap 3.2.2 in his demo (http://jasny.github.io/bootstrap/javascript/).

**Comment by martin-g** [comment]
Right. I see it too at http://wb-mgrigorov.rhcloud.com/wicket/resource/de.agilecoders.wicket.extensions.javascript.jasny.JasnyCssReference/css/bootstrap.css.
Please file a ticket.
I think we should deprecate Jasny's FileUploadField. 
de.agilecoders.wicket.extensions.markup.html.bootstrap.form.fileinput.BootstrapFileInput is much better component.

**Comment by lehvolk** [comment]
I can solve current issue with <a href="https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/490">new one</a>.

**Comment by martin-g** [comment]
Implemented with #491
