### ISSUE TITLE
RichPopoverBehavior does not render placeholder tag for ajax refresh

### ISSUE THREAD

**Issue by jcoder2** [l0rdn1kk0n/wicket-bootstrap#488]
Hello,

I been unable to find a way to refresh the content of a RichPopoverBehavior as a result of an AJAX request. I've build a sample project to demonstrate the behaviour I'm attempting to achieve.

https://github.com/jcoder2/issue488

If I add the link with the RichPopoverBehavior to the ajax target then:
 - the refreshed link loses reference to any open popover (can't close popover with click trigger).
 - there is a javascript error if the popup is closed because the tag was removed in the browser dom.
 - RichPopoverBehavior creates a new instance of my DataPanel when reloading it might be more efficient.

If I rely on events to refresh the popover but do not add the link to the ajax target
 - the DataPanel refreshes while open but raises javascript errors while closed

The issue seems to be that there's no way to get a RichPopoverBehavior to output a place holder tag. 

What I'm hoping to achieve is a popover that can be updated while open or closed during an AJAX event.

Any suggestions?

This may relate to https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/220

I am using wicket-bootstrap version 0.9.5 but sample is 0.9.7.

Regards

**Comment by jcoder2** [comment]
any thoughts on this? please and thank you.

**Comment by martin-g** [comment]
I'll take a look at your quickstart very soon!

**Comment by martin-g** [comment]
Bootstrap's Popover keeps its static content in `data-content` HTML element attribute:
```html
<a id="linke" rel="popover" title="" data-content="
            <div class=&quot;table-responsive&quot; id=&quot;container12&quot;>
                <table class=&quot;dataview table table-bordered table-striped table-condensed&quot;>
                    <tr class=&quot;headers&quot;>
                        <th><span>Name</span></th>
                        <th><span>Type</span></th>
                    </tr>
                    <tr>
                        <td><span>name1</span></td>
                        <td><span>Little</span></td>
                    </tr><tr>
                        <td><span>name2</span></td>
                        <td><span>Little</span></td>
                    </tr>
                </table>
            </div>
        " data-original-title="RichPopover">Popover</a>
```

As you can see the behavior's body has an id: `container12`, but since it is not a DOM element it cannot be updated with Wicket's Ajax. Once you open the popover Bootstrap uses this text to create the HTML elements out of it and later Ajax updates work as expected.

I've added `bodyEnabled` boolean property to TestPopoverBehavior that is toggled to `true` when the popover is being shown and this solved the issue.
Please see https://github.com/jcoder2/issue488/pull/1.

**Comment by jcoder2** [comment]
Hi Martin,

Thank you for your efforts. Your solution removes errors from the logs but doesn't solve the functional issue as I see it. While closed, the content of the popup still cannot be updated nor does it retain it's state after being updated, closed and reopened.

Would this approach help: http://www.cagataygurturk.com/load-a-bootstrap-popover-content-with-ajax/ 

Perhaps data-poload attribute in the example could reference a wicket page?

Steps to reproduce scenario #1:
1. open the Popover 
2. observe, the Type column in RichPopover displays Big
3. close the Popover
4. select the radio button labeled Little
5. open the Popover
6. observe, the Type column in RichPopover still displays Big
I'd expect that the Type column in RichPopover would displays Little

Steps to reproduce scenario #2:
1. open the Popover
2. select the radio button labeled Little
3. observe, the Type column in RichPopover now displays Little
4. close the Popover and reopen it
5. observe, the Type column in RichPopover now displays nothing
I'd expect that the Type column in RichPopover would displays Little

Thanks for your time.

Will
