### ISSUE TITLE
Actualization of Jasny components

### ISSUE THREAD

**Issue by lehvolk** [l0rdn1kk0n/wicket-bootstrap#490]
JasnyCssReference.INSTANCE shoud be replaced with css reference from BootstrapSettings. Jasny uses Bootstrap 3.2.0 in his <a href="http://jasny.github.io/bootstrap/javascript/">demo</a> but JasnyCssReference.INSTANCE points to bootstrap version 2.2.2. I think Jasny js should be actualized too.

Jasny's FileUploadField should be deprecated de.agilecoders.wicket.extensions.markup.html.bootstrap.form.fileinput.BootstrapFileInput is much better component (see discussion <a href="https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/487#issuecomment-72416615">here</a>).

**Comment by martin-g** [comment]
And this is fixed too, right ?

**Comment by lehvolk** [comment]
Yes.
