### ISSUE TITLE
Animated behavior

### ISSUE THREAD

**Issue by danjee** [l0rdn1kk0n/wicket-bootstrap#496]
Hello,
I would like to create a new pull request with an AnimatedBehavior class that will use Daniel Eden's css file: http://daneden.github.io/animate.css/
My question is what kind of css reference should I use: 
- a cdn url
- put the css file inside the package 
- use a webjar?
Thank you

**Comment by martin-g** [comment]
Awesome!
Use webjar by default and CDN when https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/IBootstrapSettings.java#L175 returns `true`.
Thank you!
