### ISSUE TITLE
DateTimePicker icon

### ISSUE THREAD

**Issue by danjee** [l0rdn1kk0n/wicket-bootstrap#501]
Before this datetime input field was added in the framework by @lehvolk I used the same jquery plugin for working with time events in my projects but I had a different way of adding icon. It was something like this:

```
@Override
	protected void onInitialize() {
                super.onInitialize();
		if(withIcon()){
			add(new BootstrapBaseBehavior(){

				private static final long serialVersionUID = -7570348574095299836L;

				@Override
				public void beforeRender(Component component) {
					component.getResponse().write("<div class=\"input-group\">");
					super.beforeRender(component);
				}

				@Override
				public void afterRender(Component component) {
					super.afterRender(component);
					component.getResponse().write("<span class=\"input-group-addon\"><span    class=\"fa fa-calendar\"></span></span></div>");
				}
			});
		}
}
```

This spares the API for a different Java class when in need for an icon to highlight that you are using a time field.

**Comment by martin-g** [comment]
Yes, this is a possible way to do it.
But it is already released and I see no reason to mark it as deprecated and replace it now.
Thanks though!
