### ISSUE TITLE
CryptoMapper

### ISSUE THREAD

**Issue by Shengche** [l0rdn1kk0n/wicket-bootstrap#503]
I wrote an application with wicket 6.19.0 and wicket-bootstrape 0.9.8.
I tried to encrypt the url using 
setRootRequestMapper(new CryptoMapper(getRootRequestMapper(), this));

but it failed to encrypt the url and the odd thing was that resource urls were encrypted!

The demo site is http://coding.teliclab.info
Please help me to figure out the problem(s). Thank you.

**Comment by martin-g** [comment]
Please consult with CryptoMapper's javadoc:
https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/core/request/mapper/CryptoMapper.java#L56-L58

The issue is not related to Wicket-Bootstrap.
Please ask for further help at users@wicket.apache.org.

**Comment by Shengche** [comment]
Thanks Martin.

On Fri, Mar 27, 2015 at 3:21 AM, Martin Grigorov <notifications@github.com>
wrote:

> Please consult with CryptoMapper's javadoc:
>
> https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/core/request/mapper/CryptoMapper.java#L56-L58
>
> The issue is not related to Wicket-Bootstrap.
> Please ask for further help at users@wicket.apache.org.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/503#issuecomment-86679655>
> .
>



-- 
--------------------------------------------------------------------------------------------->
To boldly go where no man has gone before.
--------------------------------------------------------------------------------------------->
We do this not because it is easy. We do this because it is hard.
--------------------------------------------------------------------------------------------->
front713@gmail.com
--------------------------------------------------------------------------------------------->
