### ISSUE TITLE
How do I manually add bootstrap dependencies when autoAppendResources is false?

### ISSUE THREAD

**Issue by doncferguson** [l0rdn1kk0n/wicket-bootstrap#506]
While most of my wicket pages use bootstrap, some don't (in particular, outbound HTML emails). I'd like to suppress auto loading dependencies (by calling bootstrapSettings.setAutoAppendResources(false)) and add the dependencies only on pages that need it.  Since these all inherit from a single base class, that should be easy.

I'm not clear on the how to add the wicket-bootstrap dependencies manually.  The following almost works:
        public BootstrapBase() {
             add(BootstrapBaseBehavior.instance());
            ....
        }
        @Override
        public void renderHead(IHeaderResponse response) {
             ...
              for (HeaderItem item : BootstrapJavaScriptReference.instance().getDependencies()) {
                response.render(item);
             }
         }

but some components don't seem to be initialized properly (in particular, my menu bar is broken)
Any hints on the correct way to add bootstrap to a page if autoAppendResources is false?

**Comment by doncferguson** [comment]
Seems like the following does the trick:
  public BootstrapBasePage () {
        add(BootstrapBaseBehavior.instance());
        add(BootstrapJavascriptBehavior.instance());
        add(BootstrapResourcesBehavior.instance());
        .....
   }

**Comment by l0rdn1kk0n** [comment]
`add(BootstrapResourcesBehavior.instance());` is correct, it adds both js and css resources.
