### ISSUE TITLE
Autoclose option in DatetimePicker.

### ISSUE THREAD

**Issue by VigneshPalanisamy** [l0rdn1kk0n/wicket-bootstrap#507]
There is no autoclose option in DatetimePickerConfig. if you give autoclose option like DateTextFieldConfig. it will be very useful for us.

**Comment by martin-g** [comment]
We can provide only options which are available in the JS widget.
Please check http://eonasdan.github.io/bootstrap-datetimepicker/ and if the option is available there give us its name and we will add it to DatetimePickerConfig. If it is not then create an issue at https://github.com/Eonasdan/bootstrap-datetimepicker/issues and ping us when it is available.
Thanks!

**Comment by VigneshPalanisamy** [comment]
Thanks Martin, 
      Autoclose option was not there while picker uses the timepicker.  So i created an issue https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1057

**Comment by VigneshPalanisamy** [comment]
Thanks martin,
        There was no options to autoclose the picker while it using timepicker. But there is a option to show close button in dateTimePicker http://eonasdan.github.io/bootstrap-datetimepicker/Options/#showclose.

**Comment by martin-g** [comment]
Added it.

**Comment by VigneshPalanisamy** [comment]
Thanks martin.

**Comment by VigneshPalanisamy** [comment]
bootstrap-datetimepicker 'showClose' feature is added from the version 4.7.14 only. please update to latest version.

bootstrap-datetimepicker change log http://eonasdan.github.io/bootstrap-datetimepicker/Version%204%20Changelog/

**Comment by martin-g** [comment]
Could you please send a Pull Request?
Thanks!

**Comment by VigneshPalanisamy** [comment]
Thanks, When you will release 0.9.9 ?

**Comment by martin-g** [comment]
My plan is to release it right after Wicket 6.20 is released.
I can do it even earlier but first I want to update other widgets' JS, the themes, ...
I'll try to do it tomorrow evening (GMT+2).
