### ISSUE TITLE
Add integration with a decent WYSIWYG editor

### ISSUE THREAD

**Issue by martin-g** [l0rdn1kk0n/wicket-bootstrap#512]
E.g. https://github.com/summernote/summernote

**Comment by klopfdreh** [comment]
Hi,

just to let you know that I tried to integrate it, but there were a lot of styling issues with the current theme, which makes the editor not usable at the current state. Maybe I did something wrong, but as of the documentation it is rather easy to integrate it with:

```java
$(document).ready(function() {
  $('#summernote').summernote();
});
```

**Comment by martin-g** [comment]
So Summernote looks well only with the default Bootstrap theme? And looks bad with any other theme (e.g. Bootswatch, Material design)?

**Comment by klopfdreh** [comment]
I only tested it with the theme of the wicket-bootstrap-examples (in which I integrated the DropZoneFileUpload) and in this theme the layout was broken. Maybe it was only related to this theme, but I just wanted to give a short feedback. I didn't test int with Bootswatch / Material

**Comment by martin-g** [comment]
The samples run with Bootswatch theme by default. There is a theme chooser at the top-right corner.
To change the theme provider (to Bootstrap, Material Design or Vegibit) you have to edit WicketApplication.java directly.

I'll take a look soon.
Thanks, Tobias!

**Comment by klopfdreh** [comment]
I managed to get it working - I am going to finalize it soon.

**Comment by klopfdreh** [comment]
<img width="960" alt="summernote" src="https://cloud.githubusercontent.com/assets/980773/8899273/906b406c-3432-11e5-8a2d-0a1f1a0fcbed.png">

**Comment by klopfdreh** [comment]
One point we should discuss is how to get the content of the editor shipped to the backend. Maybe via button or a hook to embed the editor into a form? What do you think?

**Comment by reiern70** [comment]
Hi,

I haven't looked at your integration but... Maybe use the call-backs 
http://summernote.org/#/deep-dive#callbacks

to get contents into a hidden input? E.g

1- Roll out a behaviour creating client side-component. 
2- An "TextField" component that creates the a hidden input + client side so that text is synchronized with hidden field when it changes.
3- You will need to add server side call-back to upload images and so on?

**Comment by martin-g** [comment]
Hi,

I haven't looked neither at Tobias' work nor at Summernote docs but I'd expect the editor to submit its text as a normal FormComponent, i.e. if it is a part of a Form then submitting the form should update the editor's model object. Also AjaxFormComponentUpdatingBehavior should work as for any other FormComponent.

**Comment by klopfdreh** [comment]
@martin-g - I will modify the code the way that it is handled like a FormComponent.
@reiern70 - I think this will also target your ideas. I will have a look at images - how they can be handled.

I will go for the changes during this week and finalize the component.

**Comment by reiern70** [comment]
Hi,

I would try to do it as:

1- A behavior generating client side + server side hooks for things like image uploads... AJAX event corresponding to client side events and so on.
2- A form component using behaviour in 1).

IMHO this way you provide more flexibility (use it as a behavior or as a ready to use form component)

**Comment by klopfdreh** [comment]
Thanks for your suggestions. I will integrate on thursday.

**Comment by klopfdreh** [comment]
I added a new commit to my repo. Do you want the images to be uploaded first and then add it locally with base64 string or should the image received from server if inserted?

**Comment by reiern70** [comment]
Thanks for your work! Can you create a PR so that it is easier to see your work? Not completely follow you regarding the images... I haven't seen how hey work on UI widget.

**Comment by klopfdreh** [comment]
Some comments ago there is a reference to the branch.

**Comment by reiern70** [comment]
Ah! Juts missed it. Thanks!

**Comment by reiern70** [comment]
Hi,

Some comments

1- https://github.com/klopfdreh/wicket-bootstrap/blob/31e64c097afd64734eac3ecb381035fd9708b918/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/editor/SummernoteEditor.java

I would make this a Bahavior that checks it is attached to a div.

2- That behaviour should have the machinery to create all client side code from server side... properties and methods.

3- Additional roll out ad form component panel with 
3.1 A hidden input to store text inside the component
3.2 A div for the Behavior in A.
3.3. Tune the behaviour to make it store contents on hidden input field.

4- Maybe roll an Wicket/AJAX powered version of the behavior in 1?

**Comment by klopfdreh** [comment]
If a user is inserting an image it is going to be send to the server (for each image one request) and also applied to the editor - local. Next step to do is to send the text of the editor to the server on submit of a surrounding form. This is a little bit more complicated, because the text is inserted to a <p> tag in a following div container rendered by the summernote editor.

@martin-g is there a way to apply a AjaxFormComponentUpdatingBehavior to a foreign html element?

**Comment by klopfdreh** [comment]
I changed the implementation that way, that images are received from server, now. You only have to do two things:

1. mountResource(SummernoteStoredImageResourceReference.SUMMERNOTE_MOUNT_PATH, new SummernoteStoredImageResourceReference());

2. SummernoteConfig.setUploadFolder(new File("/Users/user/summernoteimagefolder"));

So if you store the content and reload the page with the stored content (images are then pointing to the mounted resource again) the images are going to be load from server.

**Comment by klopfdreh** [comment]
Only thing left is to send the content of the editor to server and receive it on load (maybe we could use the FormComponent Model for that)

**Comment by klopfdreh** [comment]
I am going to do a base64 encode / decode of the image header value, because I remember IE having some troubles with UTF-8 chars.

**Comment by klopfdreh** [comment]
One thing I think is also required is to add a random id to the image name, so that it is not replaced by another upload.

**Comment by martin-g** [comment]
@klopfdreh Please create a Pull Request so it is easy to test/comment on your code.

**Comment by klopfdreh** [comment]
@martin-g Ok - but there are several commits, now - I have to squash them before integration.

**Comment by martin-g** [comment]
It's not mandatory to squash them.

**Comment by klopfdreh** [comment]
No problem - We also can let the commits as they are. :-)
