### ISSUE TITLE
Question regarding BootstrapRadioChoice inline feature

### ISSUE THREAD

**Issue by de-marcelh** [l0rdn1kk0n/wicket-bootstrap#519]
Hi there,

i am trying to use the BootstrapRadioChoice inline feature in my application, but have no luck so far. The radios keep being stacked. I tried it in the sample application as well with the same result. I added some screenshots of my code below, am i doing something wrong?

![code_bootstrapradiochoicejava](https://cloud.githubusercontent.com/assets/5574762/8177828/ee7fcd70-1408-11e5-989d-15b9df517a04.png)
![code_bootstrapradiochoicehtml](https://cloud.githubusercontent.com/assets/5574762/8177827/ee74d9e2-1408-11e5-919c-48308e41e546.png)
![sampleappbootstrapradiochoice](https://cloud.githubusercontent.com/assets/5574762/8177833/006d0e08-1409-11e5-8579-165cd7f5fe90.png)

EDIT: Using wicket-bootstrap 0.9.10

Kind regards

Marcel

**Comment by martin-g** [comment]
It seems it was a bug.
Fixed! Thanks!
