### ISSUE TITLE
update wicket and guava version

### ISSUE THREAD

**Issue by johnjcool** [l0rdn1kk0n/wicket-bootstrap#520]
hello,

could you please update to the new wicket version 6.20.0. wicket-webjars uses guava version 18.0 because of an cdi issue. could you also update wicket-bootstrap-extension to guava 18.0. it is already using 14.0.1.

kind regards

**Comment by johnjcool** [comment]
after upagrding could you please release wicket-bootstrap 0.9.11.

**Comment by martin-g** [comment]
Done.
0.9.11 will come shortly. I want to update to Bootstrap 3.3.5 first.
