### ISSUE TITLE
BootstrapAjaxLink and default label

### ISSUE THREAD

**Issue by tahitiangabriel** [l0rdn1kk0n/wicket-bootstrap#522]
By default in BootstrapAjaxLink the label is set with the link's model.
````java
    public BootstrapAjaxLink(String id, IModel<T> model, Buttons.Type type) {
        super(id, model);

        add(buttonBehavior = new ButtonBehavior(type, Buttons.Size.Medium));
        add(icon = newIcon("icon"));
        add(splitter = newSplitter("splitter"));

        this.label = newLabel("label", model);   <------------
        add(label); 
    }
````
Which is weird as it displays the object address. For example : "xx.xxxxx.MyBean@62b4a3f5"

So I must set manually an empty label as a workaround : 
````java
setLabel(Model.of(""));
````

Shouldn't we set an empty label by default because the label and the model handle by the link are two different things?

Also we can add a new constructor like :
````java
public BootstrapAjaxLink(String id, IModel<T> model , IModel<?> LabelModel, Buttons.Type type)
````

**Comment by martin-g** [comment]
Improved by using different models for the link itself and its label.
This led to backward incompatible change but since Wicket Bootstrap is still 0.x I think it is OK. It is definitely a bug fix.
Thanks!

**Comment by tahitiangabriel** [comment]
Thank you Martin you rock!
