### ISSUE TITLE
Add support for context-relative less resources

### ISSUE THREAD

**Issue by jakub-krauz** [l0rdn1kk0n/wicket-bootstrap#524]
In the bootstrap-less module less resources from the classpath are supported via LessResourceReference. It does not support context-relative resources (located in the webapp directory). It would be very useful to implement something like LessContextRelativeResourceReference (extending the functionality of org.apache.wicket.request.resource.ContextRelativeResourceReference) and other necessary objects.

**Comment by martin-g** [comment]
Duplicate #523
