### ISSUE TITLE
Improve summernote editor to show a busy spinner if a picture is uploading

### ISSUE THREAD

**Issue by klopfdreh** [l0rdn1kk0n/wicket-bootstrap#537]
As mentioned in the topic of this issue. Improve the summernote editor to show a busy spinner during the upload.

Start showing the spinner after this line:
https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/editor/js/summernote_init.js#L15

Stop showing the spinner after this line: 
https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/editor/js/summernote_init.js#L36

I think an overlay would be nice

**Comment by martin-g** [comment]
L15 receives an array of files, L36 is the success callback after each Ajax call.
If there are more than one files to upload then you should hide the overlay after the *last* upload.

**Comment by klopfdreh** [comment]
Yes thats right! There is no callback for that case, but I think if a counter is places at the start in onImageUpload and the counter is increased every time an image has been uploaded we can achieve the goal.

**Comment by klopfdreh** [comment]
I'm going to try my best to get this issue solved this evening.

**Comment by klopfdreh** [comment]
The last thing which is missing is to show / hide the overlay after some seconds the upload process has started. So if the upload takes to long, then show the overlay. If the upload process is fast enought - don't show it.

**Comment by klopfdreh** [comment]
Two things is left:

1. The default value for the spinner timeout is not set. That is strange, because of the initialization:
```java
private static final IKey<Integer> OverlayTimeout = newKey("overlayTimeout", 2000);
```
(In the summernote_init.js the value of "summernoteConfig.overlayTimeout" is undefined)

2. If the image is uploaded the spinner disappears, but the image is shown some seconds after that. I think we should fix this by adding an onLoad to the inserted image. and then increase the count / hide the spinner.

**Comment by klopfdreh** [comment]
1: Is fixed.

2: I need to investigate that a bit more at the weekend.

**Comment by klopfdreh** [comment]
Closed due to https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/582
