### ISSUE TITLE
Make Modal class more friendly with getter and setter methods

### ISSUE THREAD

**Issue by mdisabatino** [l0rdn1kk0n/wicket-bootstrap#539]
In Modal class all fields are declared private and there aren't getter and setter methods.

**Comment by RLStokes** [comment]
So with this change, you must override onInitialize() to set the header, because header is not initialized in the constructor?  Is that what was intended?

**Comment by martin-g** [comment]
No. Now you can override any of the `create**()` methods to create your own container. No need to override `#onInitialize()`.
