### ISSUE TITLE
DropDownButton newButtonList is private

### ISSUE THREAD

**Issue by johnjcool** [l0rdn1kk0n/wicket-bootstrap#545]
it would be very nice if the factory method newButtonList in DropDownButton would be protected. The use case is also to set activeStateAppender to buttons inside dropdown. therefore we have to extend class ButtonList poplateItem.

ps: we are using 0.9.x because we couldn't migrate to wicket 7 at the moment.

**Comment by martin-g** [comment]
I'd love to press the "Merge" button! ;-)

**Comment by johnjcool** [comment]
thanks :-)

**Comment by tahitiangabriel** [comment]
@johnjcool 

Aren't button create by you in the newSubMenuButtons function?
Can't you add the activeStateAppender at your button creation (in onConfigure for example)?

```java
    /**
     * creates a list of sub menu buttons which will be shown if sub menu will be opened.
     *
     * @param buttonMarkupId the markup id that all sub menu buttons must be use.
     * @return list of sub menu buttons
     */
    protected abstract List<AbstractLink> newSubMenuButtons(final String buttonMarkupId);

    /**
     * creates a new {@link ButtonList} that contains all buttons from {@link #newButtonList(String)}
     *
     * @param markupId the markup id of {@link ButtonList}
     * @return new {@link ButtonList} instance
     */
    private ButtonList newButtonList(final String markupId) {
        final ButtonList buttonList = new ButtonList(markupId, newSubMenuButtons(ButtonList.getButtonMarkupId()));
        buttonList.setRenderBodyOnly(true);

        return buttonList;
    }
```

**Comment by johnjcool** [comment]
No. You have to set the activeStateAppender on ListItem (<li class="active">) instead of nested AbstractLink (<a class="active">).

**Comment by tahitiangabriel** [comment]
I don't see any "active" state on Dropdown in the documentation, so I guess it's for your own use case.
I'm just aware about the "disabled" state : http://getbootstrap.com/components/#dropdowns-disabled.

**Comment by johnjcool** [comment]
you're right.  but it is working. we have to support dropdown-submenu in our navigation.

thanks for the hint with onConfigure. Here the workarond:

```java
protected void onConfigure() {
	super.onConfigure();

	if (isActive(this)) {
		ListItemCssClassHelper.onConfigure(this, "active");
	}
}
```

but i think it would be better if factory methods are protected to have a chance to extend.

**Comment by tahitiangabriel** [comment]
By the way the "disable" state is not handle by ButtonList if the button is disable.
So it produce code which is not correct : 
```Java
<li>
<a id="button8f" class="btn btn-disabled btn-link" disabled="disabled" >..</a>
</li>
```
So we should change it to : 
```Java
@Override
    protected void populateItem(ListItem<AbstractLink> item) {
        final AbstractLink link = item.getModelObject();
         if(!link.isEnable()) {

        Args.isTrue(getButtonMarkupId().equals(link.getId()), "component id is invalid, please use ButtonList.getButtonMarkupId()");

        item.add(link);
    }
```

**Comment by tahitiangabriel** [comment]
@johnjcool 
Thank you for the tip about ListItemCssClassHelper. I was not aware of this class. It is very useful!

**Comment by martin-g** [comment]
> I'd love to press the "Merge" button! ;-)

By this I meant "Please send a PR and I'll be glad to merge it"

**Comment by tahitiangabriel** [comment]
@martin-g we know! I will try to do this tomorrow.

**Comment by tahitiangabriel** [comment]
@martin-g 

I've done the following modification : 
```Java
    protected void populateItem(ListItem<AbstractLink> item) {
        final AbstractLink link = item.getModelObject();
        Args.isTrue(getButtonMarkupId().equals(link.getId()), "component id is invalid, please use ButtonList.getButtonMarkupId()");

        if (!link.isEnabled()) {
            item.add(new CssClassNameAppender("disabled"));
        }
        item.add(link);
    }
````
But it's not working if "enabled" is set in the onConfigure of the button : 
```Java
@Override
                    protected void onConfigure() {
                        super.onConfigure();
                        setEnabled(someTests);
}
```
as onConfigure is call after the populateItem of the ButtonList. How can I handle this?

**Comment by martin-g** [comment]
I'll tell you a secret;)
You can configure a component you depend on with `buttonList.configure()`.
This way you can configure some component that must be configured before the current component is configured.
Does this solve the issue?

**Comment by tahitiangabriel** [comment]
@martin-g 
Thank you very much for your help. I'm using Wicket for years and I still learn many things from you and your posts. So yes, it does solve my issue!
PR coming soon...

**Comment by johnjcool** [comment]
@martin-g do you have a snapshot repo for wicket bootstrap?

**Comment by martin-g** [comment]
Just uploaded https://oss.sonatype.org/content/repositories/snapshots/de/agilecoders/wicket/wicket-bootstrap-core/0.9.13-SNAPSHOT/.
Enjoy!

**Comment by johnjcool** [comment]
Thanks :)
