### ISSUE TITLE
Missing jquery webjar dependencies

### ISSUE THREAD

**Issue by fmartelli** [l0rdn1kk0n/wicket-bootstrap#549]
I have this issue working with the new Apache Syncope admin console.
This wicket application is based on wicket-bootstrap and use a custom theme (bootstrap based).

The problem that I have is on induced jquery dependencies: they fail (HTTP 404) since null version. 
It seems that "current" placeholder is replaced with null because no recent available version found.

Further strange things:
1. no exceptions in log files
2. wicket application involve several pages but just a specific one has this problem

See below for some errors reported into the javascript console.

"NetworkError: 404 Not Found - http://localhost:9080/syncope-console/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/jquery-ui/null/ui/minified/jquery.ui.widget.min.js"

"NetworkError: 404 Not Found - http://localhost:9080/syncope-console/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/jquery-ui/null/ui/minified/jquery.ui.resizable.min.js"

"NetworkError: 404 Not Found - http://localhost:9080/syncope-console/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/jquery-ui/null/ui/minified/jquery.ui.mouse.min.js"

"NetworkError: 404 Not Found - http://localhost:9080/syncope-console/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/jquery-ui/null/ui/minified/jquery.ui.core.min.js"

"NetworkError: 404 Not Found - http://localhost:9080/syncope-console/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/jquery-ui/null/ui/minified/jquery.ui.draggable.min.js"

"NetworkError: 404 Not Found - http://localhost:9080/syncope-console/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/jquery-ui/null/ui/minified/jquery.ui.core.min.js"

"NetworkError: 404 Not Found - http://localhost:9080/syncope-console/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/jquery-ui/null/ui/minified/jquery.ui.widget.min.js"

"NetworkError: 404 Not Found - http://localhost:9080/syncope-console/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/jquery-ui/null/ui/minified/jquery.ui.mouse.min.js"

"NetworkError: 404 Not Found - http://localhost:9080/syncope-console/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/jquery-ui/null/ui/minified/jquery.ui.resizable.min.js"

"NetworkError: 404 Not Found - http://localhost:9080/syncope-console/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/jquery-ui/null/ui/minified/jquery.ui.draggable.min.js"

**Comment by Adar** [comment]
Hi,

I had this error and doing a WicketWebjars.install(this); in init() resolved it for me. Maybe it helps in your case, too (?)

**Comment by martin-g** [comment]
Which version of jQuery do you want to use?
Could please paste here the Maven `<dependency>` from your pom.xml.

**Comment by martin-g** [comment]
Actually it is jQuery UI, not jQuery itself.
Please paste the code that contributes WebjarsJavaScriptResourceReference for jQuery UI too.

**Comment by fmartelli** [comment]
Thank you Adar but  it seems that WicketWebjars.install(this) does not resolve my issue.

Martin, see below wicket  and some relevant webjars dependencies into the pom.xml and  my init() method.

       ...
       <dependency>
        <groupId>org.webjars</groupId>
        <artifactId>jquery</artifactId>
        <version>${jquery.version}</version>
      </dependency>
      <dependency>
        <groupId>org.webjars</groupId>
        <artifactId>jquery-ui</artifactId>
        <version>${jquery-ui.version}</version>
      </dependency>
      <dependency>
        <groupId>org.webjars</groupId>
        <artifactId>jquery-ui-themes</artifactId>
        <version>${jquery-ui.version}</version>
      </dependency>
      <dependency>
        <groupId>org.webjars</groupId>
        <artifactId>bootstrap</artifactId>
        <version>${bootstrap.version}</version>
      </dependency>
      <dependency>
        <groupId>org.webjars</groupId>
        <artifactId>bootstrap-select</artifactId>
        <version>${bootstrap-select.version}</version>
      </dependency>
      .....
      
      <dependency>
        <groupId>org.apache.wicket</groupId>
        <artifactId>wicket</artifactId>
        <version>${wicket.version}</version>
        <type>pom</type>
      </dependency>
      <dependency>
        <groupId>org.apache.wicket</groupId>
        <artifactId>wicket-extensions</artifactId>
        <version>${wicket.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.wicket</groupId>
        <artifactId>wicket-datetime</artifactId>
        <version>${wicket.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.wicket</groupId>
        <artifactId>wicket-spring</artifactId>
        <version>${wicket.version}</version>
        <exclusions>
          <exclusion>
            <groupId>org.springframework</groupId>
            <artifactId>spring</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>org.apache.wicket</groupId>
        <artifactId>wicket-auth-roles</artifactId>
        <version>${wicket.version}</version>
      </dependency>
      <dependency>
        <groupId>com.googlecode.wicket-jquery-ui</groupId>
        <artifactId>wicket-jquery-ui</artifactId>
        <version>${wicket-jqueryui.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.wicket</groupId>
        <artifactId>wicket-native-websocket-javax</artifactId>
        <version>${wicket.version}</version>
      </dependency>
      <dependency>
        <groupId>de.agilecoders.wicket</groupId>
        <artifactId>wicket-bootstrap-core</artifactId>
        <version>${wicket-bootstrap.version}</version>
      </dependency>
      <dependency>
        <groupId>de.agilecoders.wicket</groupId>
        <artifactId>wicket-bootstrap-extensions</artifactId>
        <version>${wicket-bootstrap.version}</version>
      </dependency>
      


<pre>
   @Override
    protected void init() {
        super.init();
        IBootstrapSettings settings = new BootstrapSettings();
        settings.setThemeProvider(new SingleThemeProvider(new AdminLTE()));
        Bootstrap.install(this, settings);
        
        // tried since suggested by Adar (see https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/549) 
        // WicketWebjars.install(this);

        getResourceSettings().setUseMinifiedResources(true);

        getComponentInstantiationListeners().add(new SpringComponentInjector(this));
        getResourceSettings().setThrowExceptionOnMissingResource(true);

        getJavaScriptLibrarySettings().setJQueryReference(new DynamicJQueryResourceReference());

        getSecuritySettings().setAuthorizationStrategy(new MetaDataRoleAuthorizationStrategy(this));
        ClassPathScanningCandidateComponentProvider scanner = new ClassPathScanningCandidateComponentProvider(false);
        scanner.addIncludeFilter(new AssignableTypeFilter(BasePage.class));

        for (BeanDefinition bd : scanner.findCandidateComponents(StringUtils.EMPTY)) {
            try {
                @SuppressWarnings("unchecked")
                Class<? extends BasePage> clazz = (Class<? extends BasePage>) ClassUtils.resolveClassName(
                        bd.getBeanClassName(), ClassUtils.getDefaultClassLoader());
                MetaDataRoleAuthorizationStrategy.authorize(clazz, SyncopeConsoleSession.AUTHENTICATED);
            } catch (Throwable t) {
                LOG.warn("Could not inspect class {}", bd.getBeanClassName(), t);
            }
        }

        getMarkupSettings().setStripWicketTags(true);
        getMarkupSettings().setCompressWhitespace(true);

        getRequestCycleListeners().add(new SyncopeConsoleRequestCycleListener());

        mountPage("/login", getSignInPageClass());

        final String activitiModelerDirectory = WebApplicationContextUtils.getWebApplicationContext(
                WebApplication.get().getServletContext()).getBean("activitiModelerDirectory", String.class);
        mountResource("/" + ACTIVITI_MODELER_CONTEXT, new ResourceReference(ACTIVITI_MODELER_CONTEXT) {

            private static final long serialVersionUID = -128426276529456602L;

            @Override
            public IResource getResource() {
                return new FilesystemResource(ACTIVITI_MODELER_CONTEXT, activitiModelerDirectory);
            }

        });
        mountResource("/workflowDefGET", new ResourceReference("workflowDefGET") {

            private static final long serialVersionUID = -128426276529456602L;

            @Override
            public IResource getResource() {
                return new WorkflowDefGETResource();
            }
        });
        mountResource("/workflowDefPUT", new ResourceReference("workflowDefPUT") {

            private static final long serialVersionUID = -128426276529456602L;

            @Override
            public IResource getResource() {
                return new WorkflowDefPUTResource();
            }
        });
    }
</pre>

**Comment by martin-g** [comment]
Please respect our time!
Read again my earlier comments and read your response, and then try to put yourself in my shoes and give an answer by using the information you've just provided.

**Comment by tahitiangabriel** [comment]
Double check your ${jquery-ui.version} in your pom. What is its value?

**Comment by fmartelli** [comment]
Sorry Martin, max respect!
Nevermind, thanks anyway.

Hi Gabriel, thanks for your reply.
<jquery-ui.version>1.11.4</jquery-ui.version>

**Comment by martin-g** [comment]
Thanks!
And now please show us the String you pass to WebjarsJSRR for jquery.ui.js

**Comment by fmartelli** [comment]
Hi Martin, actually I don't understand your question.
I think I didn't specify any string for  WebjarsJavaScriptResourceReference. Maybe someone else but I don't know how and where. I'm sorry if I'm not so good with wicket and wicket-bootstrap ...

BTW, I found the problem: jquery-ui 1.11.4 webjar dependency does no longer include the missing JSs. The latest one to explicitly include JSs for mouse, resizable, draggable and so on, seems to be the 1.10.4-1.

Into the 1.11.4, jquery-ui.js Includes core.js, widget.js, mouse.js, draggable.js, resizable.js, datepicker.js.

Hope this help you to save time!
Thank you anyway and sorry again if I disturbed you.

Best regards,
F.

**Comment by martin-g** [comment]
For now you should downgrade jQuery UI to 1.10.x.

For the next release we should upgrade the references in https://github.com/l0rdn1kk0n/wicket-bootstrap/tree/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/jqueryui to the new WebJars layout for 1.11.x.
