### ISSUE TITLE
Summernote usage

### ISSUE THREAD

**Issue by ymlaine** [l0rdn1kk0n/wicket-bootstrap#550]
Hi,

After trying to play with Summernote implementation, I noticed that it's not possible to use it as a Wicket FormComponent (I mean it doesn't seem to submit the content to the FormComponent's Model.) Is there a reason for that ? I tried to make it extend TextArea and did some other small changes and it seems to work much more the Wicket way out of the box. But this way it has to be backed by a < textarea > field, is it a real constraint ? I can send a pull request if you want.

regards,
Yves-Marie

**Comment by martin-g** [comment]
https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/editor/SummernoteEditor.java#L48 - it is a FormComponent. 
And it used the model as a store: https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/editor/SummernoteEditor.java#L84

But please share with us your improvements!

@klopfdreh /CC.

**Comment by ymlaine** [comment]
Yes I saw that it extends FormComponent and that the Model content is passed to Summernote by the init Javascript, but the way the content is submitted back to the Component doesn't seem to use the FormComponent. I mean, the only way I found to get the content is to pull it with the getSubmitedContent() method 
https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/editor/SummernoteEditor.java#L105
(or maybe I didn't manage to make it work.. )

So, after some try it seems clearer to me to force the component to be binded to a textarea by extending TextArea and rely on the component for the submit logic. (so no need to base64encode the content anymore.)

I will try to create a pull request, at leat to show you what I try to explain. :)

**Comment by martin-g** [comment]
Thanks!

**Comment by ymlaine** [comment]
I tried this pull request but there is a build problem, but I don't exactly understand why. (I'm not a github expert.)

https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/551/files

**Comment by klopfdreh** [comment]
The issue about that: summernote renders its own markup structure into the div previous to your commit - it is not really a textarea or div which can be submitted the way a FormComponent is submitted by wicket. That is the reason why I choose to submit it that specific way in the blur event function. It uses a hidden field to send the content back to the server (the only way to get it into the form out of the editor)

So when you have a look into you html code, then you will notice that your code will not work, because the content edited via summernote is somewhere more deeper in a newly created html structure.

-1 to the PR

**Comment by ymlaine** [comment]
You're right, summernote render its own markup, but I noticed that when you apply it on a textarea it automatically hides it (set display : none;) and keeps the content up to date with the editor html code. This way I found it simpler to rely on TextArea component even if it's hidden. I modified the Demo page, so you can try, it works, as easy as using a TextArea.

**Comment by klopfdreh** [comment]
Oh! Great if this is working out of the box and the content is submitted like with a normal textarea then +1 - we also should remove the getEditorContent method then. 

Thank you for the hint!

@martin-g can you help to integrate the change. :smiley:
