### ISSUE TITLE
onblur event doesn't work with Material Design theme in Firefox

### ISSUE THREAD

**Issue by mot4** [l0rdn1kk0n/wicket-bootstrap#553]
I try to handle a onblur event on a input type number with Material Design. It works fine in Chrome and IE but not in Firefox.

HTML:
< input type="number" wicket:id="myInput" onblur="alert('test');" />

Java:
add(new NumberTextField<>("myInput", myModel, Integer.class).setMinimum(0).setStep(10));

I tried it with a AjaxFormComponentUpdatingBehavior with the same result.

**Comment by martin-g** [comment]
Please try with plain HTML page, without Wicket Bootstrap.

**Comment by mot4** [comment]
Ok, I tried it and works fine without bootstrap css.
The problem looks like a css conflict.
The solution for me was disable the property "float: left" (in my css overridden).

input-groups.less file line 28:  float: left;

https://github.com/twbs/bootstrap/blob/master/less/input-groups.less#L28

**Comment by martin-g** [comment]
I'm glad you found a solution!
You can report the issue at https://github.com/FezVrasta/bootstrap-material-design
