### ISSUE TITLE
No 0.10.4-SNAPSHOT artifacts on Sonatype?

### ISSUE THREAD

**Issue by ilgrosso** [l0rdn1kk0n/wicket-bootstrap#557]
I cannot find any Maven artifact for 0.10.4-SNAPSHOT on Sonatype under (for example)

https://oss.sonatype.org/content/repositories/snapshots/de/agilecoders/wicket/bootstrap-parent/

This seems to be according to what I can see from Travis CI:

https://travis-ci.org/l0rdn1kk0n/wicket-bootstrap/branches

**Comment by martin-g** [comment]
Just uploaded new snapshots!

**Comment by ilgrosso** [comment]
Thanks!

**Comment by tahitiangabriel** [comment]
@martin-g It looks like you have broken the 0.913 snapshot.
My archiva is looking for wicket-bootstrap-core-0.9.13-20150928.100817-3 but there is only   wicket-bootstrap-core-0.9.13-20150928.100803-2 in the repository.

Is it related to the build number in the maven-metadata.xml file ?
```xml
<snapshot>
    <timestamp>20150928.100817</timestamp>
    <buildNumber>3</buildNumber>
</snapshot>
```

**Comment by martin-g** [comment]
Archiva ...
I've just did `mvn clean deploy` from my working directory.
Let me do it one more time.

**Comment by martin-g** [comment]
@tahitiangabriel Please try again.

**Comment by tahitiangabriel** [comment]
@martin-g  what's wrong with archiva?

There is still something wrong in the version number : 
```xml
<snapshot>
    <timestamp>20150928.194532</timestamp>
    <buildNumber>5</buildNumber>
</snapshot>
<lastUpdated>20150928194532</lastUpdated>
<snapshotVersions>
    <snapshotVersion>
         <extension>jar</extension>
          <value>0.9.13-20150928.194518-4</value>    <--------------- should be 20150928.194532-5
          <updated>20150928194532</updated>
    </snapshotVersion>
```

If you look at the 0.8.5-snapshot, number version is fine :
```xml
<snapshot>
    <timestamp>20131007.221705</timestamp>
     <buildNumber>2</buildNumber>
</snapshot>
<lastUpdated>20131007221705</lastUpdated>
<snapshotVersions>
    <snapshotVersion>
         <extension>jar</extension>
         <value>0.8.5-20131007.221705-2</value>
         <updated>20131007221705</updated>
    </snapshotVersion>
```

**Comment by martin-g** [comment]
I have no idea.
If you care about this then feel free to open a bug against maven-deploy-plugin.
Here are my details:
```
 mvn --version                                                                                                                                                                 18:15:03 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /home/martin/devel/maven-latest
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /home/martin/devel/jdk1.8.0_60/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-28-generic", arch: "amd64", family: "unix"
```

**Comment by tahitiangabriel** [comment]
That is strange. Everything was fine with the previous release on September 6th.
Nevermind, I will manually deploy it in my own repo.
Thank you for your help.
