### ISSUE TITLE
When the DatetimePickerConfig use "dd/MM/yyyy" format, I got an error from bootstrap-datetimepicker.js

### ISSUE THREAD

**Issue by francois92** [l0rdn1kk0n/wicket-bootstrap#558]
When the DatetimePickerConfig use "dd/MM/yyyy" format, I got an error from bootstrap-datetimepicker.js

TypeError: maxDate Could not parse date parameter:30/09/2015
bootstrap-datetimepicker.js
line 1662

DatetimePickerConfig config = new DatetimePickerConfig()
	.withFormat("dd/MM/yyyy")
	.withMinDate(new DateTime().minusDays(90).toDate())
	.withMaxDate(new Date());

new DatetimePicker("fromDate", config))	

Env:
Wicket 7.0.0
wicket-bootstrap-core : 0.10.3
wicket-bootstrap-extensions : 0.10.3

Is it possible to get the format valid ?
François

**Comment by martin-g** [comment]
Please create a simple demo app and share it in your GitHub account.

**Comment by francois92** [comment]
Hi Martin,
Here is the quickstart
https://github.com/francois92/projects_github

**Comment by francois92** [comment]
solved.

The problem was the inversion of mindate and maxdate 
withMinDate(new DateTime().minusDays(90).toDate())
.withMaxDate(new Date());
was the problem

with that, it's ok
withMinDate(new Date())
.withMaxDate(new DateTime().minusDays(90).toDate());

François

**Comment by martin-g** [comment]
Sorry, I didn't have time to look at your quickstart yet!

So, is there a bug in wicket-bootstrap or it was the application?

**Comment by francois92** [comment]
I made a mistake while setting the dates. 
and the error message returned by bootstrap.js was not good.
There is no bug in wicket-bootstrap

**Comment by martin-g** [comment]
Thanks!
