### ISSUE TITLE
Add functionality to add non-form buttons to navbar

### ISSUE THREAD

**Issue by pietvandongen** [l0rdn1kk0n/wicket-bootstrap#565]
It doesn't seem possible to add actual buttons (e.g. `<button>`) to the navbar at the moment. It is possible to add links and buttons withing a form, but no buttons that have are not embedded in the form.

Bootstrap documents these types of buttons [at their Components page](http://getbootstrap.com/components/#navbar-buttons):

> Add the `.navbar-btn` class to `<button>` elements not residing in a `<form>` to vertically center them in the navbar.

The example HTML they provide is (not the use of the class `navbar-btn`, which is explicitly meant for this type of navbar button and has its own dedicated styling in the Bootstrap framework):

```html
<button type="button" class="btn btn-default navbar-btn">Sign in</button>
```

So I'd like to be able do something like this in my code:

```java
navbar.addComponents(NavbarComponents.transform(Navbar.ComponentPosition.RIGHT,
        new NavBarNonFormButton(Login.class, Model.of("Sign in")
));
```

Please also note that the `navbar-btn` class can only be used on `<button>` elements within a `.navbar-nav`, so adding this class to an anchor tag is not sufficient:

> Like the standard button classes, `.navbar-btn` can be used on `<a>` and `<input>` elements. However, neither `.navbar-btn` nor the standard button classes should be used on `<a>` elements within `.navbar-nav`.

**Comment by martin-g** [comment]
Thank you for the issue!
Do you like to send a Pull Request?

**Comment by pietvandongen** [comment]
I'll try to free up some time to make a pull request, but that could take a while.

**Comment by klopfdreh** [comment]
Great thank you!

**Comment by martin-g** [comment]
Closing as "Won't do".

Better don't use Navbar component at all but add the needed HTML into your Wicket Panel/Page and add Wicket components where needed.
