### ISSUE TITLE
Add functionality to add non-form AJAX buttons to navbar

### ISSUE THREAD

**Issue by pietvandongen** [l0rdn1kk0n/wicket-bootstrap#566]
Similar to issue #565, but this concerns buttons that don't link to a Wicket class. This would enable us to add a button that only has JavaScript-functionality and no link to a page.

The requirements are the same as for #565, but at creation of the button, it should not require a page class to link to. It should look something like this:

```java
navbar.addComponents(NavbarComponents.transform(Navbar.ComponentPosition.RIGHT,
    new NavBarNonFormAjaxButton<String>(Model.of("Sign in") {
        @Override
        public void onClick(AjaxRequestTarget target) {
            // Etcetera...
        }
    }
));
```

**Comment by martin-g** [comment]
Closing as "Won't do".

Better don't use Navbar component at all but add the needed HTML into your Wicket Panel/Page and add Wicket components where needed.
