### ISSUE TITLE
Typeahead lookup fails when Url encryption is enabled

### ISSUE THREAD

**Issue by gsaviane** [l0rdn1kk0n/wicket-bootstrap#567]
Typeahead v10 fails to lookup choices from Bloodhound datasource when the wicket application is set up to encrypt URLs via CryptoMapper.
To reproduce the problem, set up a new Wicket-Bootstrap application having URL encryption. Provide a page having a Typeahead with a minimal TypeaheadConfig and Bloodhound to lookup over a set of choices. Run the application and type in some characters in the Typeahead to partially match the choices. No item will be resolved from the available choices. To see what happens open the browser's inspector and select the "Network" tab.
Lookups Ajax calls fail because their URLs are made as follow:
<Encryipted-URL>&term=<typed chars>

The code appending the "term" parameter presumes the URL already contains a "?", but the Encryipted-URL part does not.
We investigate the problem and we ended up that the method Bloodhound.getRemoteUrl(String) should append "&param=" only if the URL already contains a question mark. Otherwise it should append "?term=".

**Comment by martin-g** [comment]
Fixed with #568
