### ISSUE TITLE
Add fixed width option to Font Awesome CSS reference

### ISSUE THREAD

**Issue by pietvandongen** [l0rdn1kk0n/wicket-bootstrap#569]
Font Awesome provides an option to set icons at a fixed width. This is very useful for lists or pull down menus that use icons. Documentation on this option can be found here: https://fortawesome.github.io/Font-Awesome/examples/#fixed-width

The class that gets added is `fa-fw`. 

P.S.: If I can find the time, I'll implement it myself and do a pull request.

**Comment by tahitiangabriel** [comment]
Yes that would be nice if you could send a PR.

**Comment by martin-g** [comment]
Beware that the constants (like FontAwesomeIconType.adjust) are JVM singletons and changing its property will affect its usage in the whole application (class loader)!
If you need fixed width icon then create your own instance!

**Comment by martin-g** [comment]
I've found that my first commit introduced an inconsistency.
So I moved `#fixedWidth()` to FontAwesomeIconTypeBuilder as the other properties.
