### ISSUE TITLE
OptimizedMobileViewportMetaTag is optimized for no zoom

### ISSUE THREAD

**Issue by dmbeer** [l0rdn1kk0n/wicket-bootstrap#570]
The are two settings for the viewport tag one is for zoom and mobile devices and the other is without zoom and setting the max scale so that people can't zoom in on the device.

**Comment by martin-g** [comment]
This should be reworked to use either builder pattern of fluent API. I'd prefer Fluent API.
E.g.:
```java
MobileViewportTag mvt = new MobileViewportTag(id);
mvt.width(...).initialScale(...).maxScale(...)
```
Maybe `user-scalable` should be auto-detected if initialScale!=maxScale. (I have to double check that this is its purpose though).

**Comment by dmbeer** [comment]
According to the documentation here http://getbootstrap.com/css/#overview-mobile it suggests that you can only provide it as one of two values but from this blog you can adjust the settings http://www.inmotionhosting.com/support/edu/website-design/create-responsive-template/viewpoint-meta-tag-website-responsive-template.

So actually the way it was correctly done for bootstrap. If however it works by customising it then yes we should make it customisable.

**Comment by dmbeer** [comment]
@martin-g see PR #572
