### ISSUE TITLE
summernote

### ISSUE THREAD

**Issue by francois92** [l0rdn1kk0n/wicket-bootstrap#573]
Hi Martin, Michael,

I try the Summernote editor.

The value in the summernoteModel does not appear in the text area.
Do I miss something ?
(I did configure Bootstrap and Summernote in the Application class as the example does)

Here is the code I use (in a form) :
IModel<String> summernoteModel = Model.of("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.");
SummernoteEditor summernoteEditor = new SummernoteEditor("summernote", summernoteModel, summernoteConfig);

and for the html : 
<textarea wicket:id="summernote" ></textarea>

Wicket-Bootstrap Version 0.10.4 and 0.10.5
Wicket version 7.1.0
OSX / Safari / Firefox

Thanks
François

**Comment by martin-g** [comment]
Or check the demo in the `samples` module. As you can see at http://wb-mgrigorov.rhcloud.com/summernote the model is rendered at first load.
Please provide a demo application showing the problem and I'll reopen this issue.
Thank you and Merry Christmas!

**Comment by francois92** [comment]
When the air mode is false, it's not working.
here is a quickstart
François
[quickstart.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/72449/quickstart.zip)

**Comment by martin-g** [comment]
I'll take a look soon!

**Comment by francois92** [comment]
Thanks Martin

**Comment by francois92** [comment]
If the SummernoteEditor's model object contains any carriage return
we got an ERROR: Wicket.Ajax.Call.processEvaluation: Exception evaluating javascript: SyntaxError: Unexpected EOF, text: (function(){;(function() {
    .......

**Comment by martin-g** [comment]
New ticket please! :-)

**Comment by francois92** [comment]
https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/578

François
