### ISSUE TITLE
BootstrapFileInputField does not allow override (package private) of onSubmit/onError

### ISSUE THREAD

**Issue by ceefour** [l0rdn1kk0n/wicket-bootstrap#577]
* https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/form/fileinput/BootstrapFileInputField.java#L136
* https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/form/fileinput/BootstrapFileInputField.java#L145

If `BootstrapFileInput` is the only way to use it, but it doesn't allow customization such as setting `accept="image/*;capture=camera"`

**Comment by martin-g** [comment]
I've tried to improve both issues.
Please let me know if more improvements are needed!

**Comment by ceefour** [comment]
Thanks @martin-g !

Public getFileInput() getter would be appreciated for simple tweaks :)

**Comment by martin-g** [comment]
I think the factory method is better for this purpose.
You can also store its return value if you really need to keep a reference to the inputField.

**Comment by ceefour** [comment]
Sure! That's already too cool! Thanks!
