### ISSUE TITLE
DropzoneFileUpload

### ISSUE THREAD

**Issue by kjertil** [l0rdn1kk0n/wicket-bootstrap#579]
I have created a basic page using a BootStrapForm containing a DropZoneFileUpload.

When I add an single file to, and click the "Start" button for the file, everything works correctly - "onUpload" is invoked correctly.

If I on the other hand click "Start upload" (next to "Add Files"). I get and error in my log file:

WARN  RequestCycleExtra - ********************************
WARN  RequestCycleExtra - Handling the following exception
org.apache.wicket.core.request.mapper.StalePageException: null
WARN  RequestCycleExtra - ********************************

And nothing else happens! "onUpload" is not invoked.

Using Wicket 7.1.0
Wicket-bootstrap: 0.10.5
On Jetty: 9.3.6.v20151106

Bootstrap is initialized using:
		BootstrapSettings settings = new BootstrapSettings();
		Bootstrap.install(this, settings);

**Comment by martin-g** [comment]
Please provide a quickstart application!
Or provide steps to reproduce with the samples application.
Thank you!

**Comment by kjertil** [comment]
[Dropzone.txt](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/94289/Dropzone.txt)

Attached a quickstart.

I can't get it to reproduce the stalepage exception :-(

But the problem with not getting a callback to "onLoad" still remains.

(note: I tried to attach a .zip file, but it was rejected, so rename the attachment to .zip" - sorry)

**Comment by kjertil** [comment]
I have reproduced the missing StalePage exception.
If I set ConfigurationType to RuntimeConfigurationType.DEVELOPMENT then I get a StalePageException.
If I set ConfigurationType to RuntimeConfigurationType.DEPLOYMENT the StalePageException disappers.

However uploading multiple files using "Start upload" still does not work.

**Comment by martin-g** [comment]
Everything works fine with the samples application!
I'll try now with your quickstart!

**Comment by martin-g** [comment]
In your application `Start upload` button makes a normal (non-Ajax) request.
It submits the form.

**Comment by martin-g** [comment]
Removing the form around the DropzoneFileUpload (which is a Panel, and not a FormComponent) fixed the problem.

**Comment by martin-g** [comment]
"Start upload" button was using `<button type="submit" ...>` and this led to this problem.

Thanks for reporting!

**Comment by kjertil** [comment]
Thanks for fixing the issue.
Any ETA on when It will be released (0.10.7?)

**Comment by martin-g** [comment]
There are not enough fixes/improvements since 0.10.6 yet!
It will take few weeks before 0.10.7.

You can "fix" it locally in the meantime by extending DropZoneFileUpload and providing custom markup for it.

**Comment by kjertil** [comment]
Okay - thanks :-)
