### ISSUE TITLE
Use jquery-migrate 1.3.0

### ISSUE THREAD

**Issue by habecht** [l0rdn1kk0n/wicket-bootstrap#583]
In Wicket 7.2.0 the jQuery version got updated to 1.12.0. This version did not work with the jquery-migrate version which is used by wicket-bootstrap (https://github.com/jquery/jquery-migrate/issues/128). If I override the used jquery-migrate with the latest 1.3.0 version, the problem is solved, so I suggest that this should be included within a next release.

**Comment by martin-g** [comment]
Please send us a Pull Request with the change!
Thank you!

**Comment by danjee** [comment]
Sorry for bothering, but this issue seems pretty delicate for people using Wicket 7.2.0. When will the next release be possible with the fix ?
Thank you

**Comment by martin-g** [comment]
I'll do it right away!

**Comment by martin-g** [comment]
Done!
0.9.16 and 0.10.6 should be at Maven Central station soon! :-)

**Comment by danjee** [comment]
Thank you very much!
