### ISSUE TITLE
Jquery migrate upgrade for wicket 7.2.0

### ISSUE THREAD

**Issue by danjee** [l0rdn1kk0n/wicket-bootstrap#584]
After upgrading to wicket 7.2.0 I started having problems with some jquery plugins in my application.
The wicket upgrade comes with jquery upgrade. I came across this post on the [jquery forum](https://forum.jquery.com/topic/typeerror-view-is-null-line-5645-of-jquery-2-2-0-js) with an error just like mine.
After upgrading the jquery migrate version in wicket-bootstrap the problem disappeared.
So I think an upgrade is needed for the 1.3.0 version of jquery-migrate.
Thank you

**Comment by danjee** [comment]
I can create the PR myself but I am afraid of collateral damage if any.

**Comment by martin-g** [comment]
Duplicate of #583 .
