### ISSUE TITLE
Refreshing BootstrapSelect broken in 0.10.5/6

### ISSUE THREAD

**Issue by bkempe** [l0rdn1kk0n/wicket-bootstrap#586]
Steps to reproduce:
1. Go to https://wb-mgrigorov.rhcloud.com/select
2. click "Refresh first select"
3. console shows "Wicket.Ajax: Wicket.Ajax.Call.processComponent: Component with id [[default7e]] was not found while trying to perform markup update. Make sure you called component.setOutputMarkupId(true) on the component whose markup you are trying to update."

**Comment by martin-g** [comment]
@lehvolk What is the purpose of this "Refresh" button?
Bootstrap-Select.js generates some HTML structure to render its stuff. Updating just the `<select>` with Wicket doesn't help much.

**Comment by lehvolk** [comment]
JS components needs to be destroyed manually. Check the [code](https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/form/select/BootstrapSelectBehavior.java#L57) Seems that DestroyScript do the stuff and after that component not rendered.

**Comment by martin-g** [comment]
Updating bootstrap-select.js to 1.10.0 fixed it!
Thanks!
