### ISSUE TITLE
Update README.md with latest version

### ISSUE THREAD

**Issue by MarcGiffing** [l0rdn1kk0n/wicket-bootstrap#587]
Hi,

please update the current release versions in the readme or reference only to the releases site. It took me quite some time to realize that the information in the readme are outdated.

Maybe the BUGFIX/PATCH version number should be marked with a star or X.

> Current release version:
> 
> * [Wicket 7.x](http://wicket.apache.org/) and [Bootstrap 3.3.5](https://github.com/twbs/bootstrap/):  0.10.3
> * [Wicket 6.x](http://wicket.apache.org/) and [Bootstrap 3.3.5](https://github.com/twbs/bootstrap/): 0.9.12
> * Wicket 6.x and Bootstrap 2.*: 0.8.4

Thanks

**Comment by martin-g** [comment]
Thanks!
