### ISSUE TITLE
material_design theme css resources empty

### ISSUE THREAD

**Issue by subes** [l0rdn1kk0n/wicket-bootstrap#593]
Hi, 

just noticed that in the current version the css files are empty. Maybe someone should fetch the files again. See for example: https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-themes/src/main/java/de/agilecoders/wicket/themes/markup/html/material_design/css/material-fullpalette.css

**Comment by martin-g** [comment]
Thanks!
