### ISSUE TITLE
[new] wicket-bootstrap-patternfly artifact

### ISSUE THREAD

**Issue by ceefour** [l0rdn1kk0n/wicket-bootstrap#594]
To provide support for [PatternFly open interface project](https://www.patternfly.org/).

It's available as webjar in Maven central (http://search.maven.org/#search|ga|1|patternfly) (although [needs to be deployed manually for each new version](https://github.com/patternfly/patternfly/issues/110)) so it'd be great to have the components/patterns available ready for use in Wicket.

Probably as a `Theme`.

**Comment by martin-g** [comment]
I've seen this project few months ago but it didn't impress me.
Looking at it again I still don't see what it brings. Most of the "examples" are actually images.

@ceefour Do you plan to contribute an integration or you hope someone else to do it ?

**Comment by ceefour** [comment]
http://cockpit-project.org/ uses PatternFly. It's pretty cool, actually :) Definitely takes a lot of the mundane/boring things about making a dashboard/admin UI.

The live examples are https://rawgit.com/patternfly/patternfly/master/tests/cards.html (and other tabs there)

Yes I'm trying to make initial integration in https://github.com/soluvas/soluvas-web project, e.g.: https://github.com/soluvas/soluvas-web/commit/dcdfdc0e264597ce32bfb8be1d97ef012820e337

Most Wicket Bootstrap components would just work as it is, while I hope the rest of Patternfly-specific components will just be thin wrappers.

**Comment by martin-g** [comment]
OK. Then I'll wait for the pull request! :-)

**Comment by klopfdreh** [comment]
+1 for this - could be great for implementing dashboards of administrative interfaces.

**Comment by klopfdreh** [comment]
@martin-g maybe label as feature? 👍

**Comment by martin-g** [comment]
Closing for now.
Please open a Pull Request once you have something.
Thanks!
