### ISSUE TITLE
Bootstrap Toggle: confusing how to set On / Off labels

### ISSUE THREAD

**Issue by ilgrosso** [l0rdn1kk0n/wicket-bootstrap#595]
`de.agilecoders.wicket.extensions.markup.html.bootstrap.form.checkbox.bootstraptoggle.BootstrapToggleConfig.withOnLabel(String)` and `de.agilecoders.wicket.extensions.markup.html.bootstrap.form.checkbox.bootstraptoggle.BootstrapToggleConfig.withOffLabel(String)` seem to be useless; if you want to set On and Off labels, you need instead to override `de.agilecoders.wicket.extensions.markup.html.bootstrap.form.checkbox.bootstraptoggle.BootstrapToggle.getOnLabel()` and `de.agilecoders.wicket.extensions.markup.html.bootstrap.form.checkbox.bootstraptoggle.BootstrapToggle.getOffLabel()`

**Comment by martin-g** [comment]
Thanks!
I've made the config methods protected so they will not appear in the suggestions in the IDE unless someone explicitly extends the config and make the public again.
Added some javadoc to make it more clear too.

**Comment by ilgrosso** [comment]
Thanks!
