### ISSUE TITLE
Dependency upon jackson library not listed in pom.xml

### ISSUE THREAD

**Issue by amynbe** [l0rdn1kk0n/wicket-bootstrap#596]
Bootstrap.java depends on http://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core, I don't know which version of jackson you are using -- shouldn't this be in the pom file ?

**Comment by martin-g** [comment]
wicket-bootstrap depends on wicket-jquery-selectors, and this one depends on jackson 2.6.0 in the latest release: https://github.com/l0rdn1kk0n/wicket-jquery-selectors/blob/wicket-7/pom.xml#L23

You can use `mvn dependency:tree` in your project to see what are the effective dependencies (direct and transitive ones).
