### ISSUE TITLE
NotificationMessage doesn't escape strings per default (XSS attack possible )

### ISSUE THREAD

**Issue by dchristl** [l0rdn1kk0n/wicket-bootstrap#597]
The member escapeModelStrings in NotificationMessage is unintialized per default and evaluates to false on usage. 
Therefore when shown in NotificationAlert the escaping will be set to false and cross site scripting is possible. The escapeModelStrings variable should be set to true, because it is unusual for developers that the normal behaviour (string escaping) of Wicket is disabled and have to be enabled every time.

**Comment by martin-g** [comment]
Thanks!

**Comment by dchristl** [comment]
You're welcome. Is it possible to downport this to the Wicket 6.x branch (0.9.16), too? And release a new version? Thanks in advance.

**Comment by martin-g** [comment]
`master` branch is 0.9.x, so the fix will be in 0.9.17.
Wicket 6.23.0 is currently being voted. As soon it is released I'll release 0.9.17.
