### ISSUE TITLE
Pagination component follow the default bootstrap hierarchy

### ISSUE THREAD

**Issue by heryqk** [l0rdn1kk0n/wicket-bootstrap#598]
The Pagination component does not seem to follow the default bootstrap hierarchy. The Bootstrap documentation states the pagination class attribute should be on the `<ul>` element.

Currently the Pagination component appends the pagination class to the enclosing tag (i.e. `<div>`). With that said, most of the themes do not work with the Pagination.

`<nav>
  <ul class="pagination">...</ul>
</nav>
`

**Comment by martin-g** [comment]
I have used this component before and I didn't have problems to style it.
Could you please provide a quickstart application ?

**Comment by heryqk** [comment]
Thanks for the quick response Martin,

here's the quick start. I added a Theme Switcher on the top right corner to show the behavior is not tied to a specific theme.

Eric H.

On Apr 29, 2016, at 08:53 AM, Martin Grigorov <notifications@github.com> wrote:

I have used this component before and I didn't have problems to style it.
Could you please provide a quickstart application ?

**Comment by martin-g** [comment]
Did you attach something ?
Because there is nothing attached to your comment.
You can also link to a GitHub repo with the quickstart.

**Comment by heryqk** [comment]
Attaching file.

[PaginationQuickstart598.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/242529/PaginationQuickstart598.zip)

**Comment by martin-g** [comment]
Thanks!
