### ISSUE TITLE
Allow to configure size of Modal window

### ISSUE THREAD

**Issue by heapifyman** [l0rdn1kk0n/wicket-bootstrap#60]
What would be the best way to adjust the size of a Modal window?

is there a way to add settings like described here https://github.com/twitter/bootstrap/issues/675 to a Modal?

**Comment by markosjal** [comment]
could someone please explain this FULLY? I know it says it is jacascript but most likely needs to be refrenced elsewhere. Since my javascript skills are limited , I would like some guidance . These partial answers are great for the folks with advanced knowledge but guys like me can be left in the dark

**Comment by martin-g** [comment]
@markosjal What did you try and it didn't work ?

**Comment by markosjal** [comment]
did not try anything with the solution posted here .
I do not understand where nor how to use 
`
@Override
protected String createInitializerScript(final String markupId) {
    return super.createInitializerScript(markupId) + ".css({witdth:$(window).width() - 100 , height:$(window).height() - 100});";
}`
 I need the modals to fit on screen,

**Comment by markosjal** [comment]
After re-reading this thread I believe this is CSS. I added it to the css file no difference , so assuming it must be refrenced elsewhere

**Comment by markosjal** [comment]
tried it in <script> tags too no go , nothing.

**Comment by martin-g** [comment]
Check what is the generated HTML/JS code in the browser's view-source. Then play with the generated JS code in the browser's Dev Tools > Console until you see it working.
If you cannot make it work then please create a mini application with your attempt and we will help you finish it.

**Comment by markosjal** [comment]
No idea what to "play with". I never did understand javascript it seems convoluted and intentionally confusing unlike PHP.

If I can get the code unwrapped from the php I will think about it but it is always a best practice to offer a complete answer rather than an answer not fully understood by some

**Comment by martin-g** [comment]
I do not understand PHP ...
For some people one thing is hard to understand, for others - something else. It is normal.
Please use https://wicket.apache.org/start/quickstart.html to create a mini application, add Wicket-Boostrap to it, add a Modal in HomePage, override its `createInitializerScript()` method as explained above. 
If it doesn't do what you want then push your code to your GitHub account and we will help finish it.

**Comment by markosjal** [comment]
thats a lot of very specific work you are asking for for what should alteady be documented. There are other, better documented, solutions that do much the same , but thanks anyway

**Comment by martin-g** [comment]
Well, that's what I could offer for free.
If you are willing to pay for my time then I could do it all for you and document it for the next user.
Good luck!

**Comment by markosjal** [comment]
precisely why nobody gives a full answer

do not understand how someone can post a solution that is incomplete and even has "width" misspelled.

**Comment by chrisco484** [comment]
In wicketstuff there is a ModalX library (created by me) which is a wrapper around wicket's modal window system to *hopefully* make dealing with modals easier.

Its API is designed to mimic that of class desktop UI frameworks like Swing, OWL, MFC etc., (later two being C++ of course but the interfaces and usage are common among all of them).

It has the ability to set the width of a modal window.

The idea is to construct an instance of your modal content and simply call it's "show" method. The constructor of your modal content class can call a width setter method and the modal will open up at that width.
