### ISSUE TITLE
Using setLabel() method of BootstrapCheckbox results in NullPointerException

### ISSUE THREAD

**Issue by heryqk** [l0rdn1kk0n/wicket-bootstrap#601]
When using setLabel() of BootstrapCheckbox to add a label, instead of sing constructor, the component throws a NullPointerException on the Checkbox instance.

See Quickstart.
[BootstrapCheckboxQuickstart.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/248889/BootstrapCheckboxQuickstart.zip)

**Comment by martin-g** [comment]
Thanks!
