### ISSUE TITLE
Inline checkbox should not be wrapped in <div class="checkbox">

### ISSUE THREAD

**Issue by heryqk** [l0rdn1kk0n/wicket-bootstrap#605]
Inline checkbox should not be wrapped in <div class="checkbox">. It breaks the hierarchy and does not render the checkbox's properly.

[InlineCheckboxQuickstart.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/255173/InlineCheckboxQuickstart.zip)

**Comment by martin-g** [comment]
Thanks!
