### ISSUE TITLE
MenuDivider class="divider" does not render by default

### ISSUE THREAD

**Issue by jcoder2** [l0rdn1kk0n/wicket-bootstrap#606]
After upgrading from 0.9.11 to 0.9.16, MenuDivider no longer shows as a horizontal bar when added to a DropDownButton by default.
![no-menu-divider](https://cloud.githubusercontent.com/assets/3442885/15159317/00f4e776-16a9-11e6-8c7b-2e7355a04819.png)

Looking into it a bit, it appears that ListItemCssClassHelper in MenuDivider, requires that the ListView in DropDownButton be set to reuseItems=true or the class="divider" css is not added.  ListView.reuseItems is false by default and DropDownButton doesn't set it.  As a workaround I've have to override DropDownButton.newButtonList() as follows.  Is there a better solution?

```
@Override
protected ButtonList newButtonList(final String markupId) {
    final ButtonList buttonList = super.newButtonList( markupId );
    buttonList.setReuseItems( true );
    return buttonList;
}
```

**Comment by martin-g** [comment]
Please create a quickstart application so we can debug it and fix it.
Thanks!

**Comment by martin-g** [comment]
I can reproduce the problem with the themes switcher.
The real problem is that `MenuDivider##onConfigure()` is executed *before* `MenuDivider#onInitialize()`.
I'll debug it!

**Comment by martin-g** [comment]
Thanks for the report!

**Comment by jcoder2** [comment]
Yup, that got it. Thanks!
