### ISSUE TITLE
Remove Bootswatch Amelia theme

### ISSUE THREAD

**Issue by martin-g** [l0rdn1kk0n/wicket-bootstrap#608]
Amelia has been deprecated and removed: http://news.bootswatch.com/post/94634387436/new-themes-paper-and-sandstone

Take a look at https://forums.manning.com/posts/list/34938.page (https://github.com/simonholmes/amelia) for a community fork.

**Comment by tahitiangabriel** [comment]
Poor Amelia, I already miss you :-)

**Comment by martin-g** [comment]
Fixed with #610
