### ISSUE TITLE
DatetimePicker: Invalid format passed to maxDate() (probably also minDate()) function

### ISSUE THREAD

**Issue by ceefour** [l0rdn1kk0n/wicket-bootstrap#611]
I got the following:

```
bootstrap-datetimepicker-ver-3F0B119112040D0B6285B68CB129AEC7.js:2 Uncaught TypeError: maxDate() Could not parse date parameter: 15-05-2003
```

My DateTime Picker format is indeed using `dd-MM-YYYY` however it seems the maxDate/minDate settings still use the ISO format, so the component should adhere to maxDate/minDate specs.

**Comment by martin-g** [comment]
It would be useful if you provide some Java code that leads to the problem.
I cannot do anything with such report.

**Comment by martin-g** [comment]
I guess you face this problem: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1600

**Comment by martin-g** [comment]
Fixed!

**Comment by ceefour** [comment]
Thanks  @martin-g  the bug you mentioned seems to be our problem
