### ISSUE TITLE
Missing CssClassNames for Table Contextual Classes

### ISSUE THREAD

**Issue by heryqk** [l0rdn1kk0n/wicket-bootstrap#614]
Good afternoon,

would it be possible to add the Table contextual classes for rows/cells as defined by bootstrap ?

```
<!-- On rows -->
<tr class="active">...</tr>
<tr class="success">...</tr>
<tr class="warning">...</tr>
<tr class="danger">...</tr>
<tr class="info">...</tr>

<!-- On cells (`td` or `th`) -->
<tr>
  <td class="active">...</td>
  <td class="success">...</td>
  <td class="warning">...</td>
  <td class="danger">...</td>
  <td class="info">...</td>
</tr>
```

**Comment by martin-g** [comment]
Hi,

To add them where exactly ?

**Comment by heryqk** [comment]
Initially I was thinking about adding them in 

```
    @SuppressWarnings("UnusedDeclaration")
    public static final class Table {
        public static final String table = "table";
        public static final String striped = "table-striped";
        public static final String bordered = "table-bordered";
        public static final String hover = "table-hover";
        public static final String condensed = "table-condensed";
        public static final String responsive = "table-responsive";
    }
```
But if it made more sense to create a new static final class in CssClassNames names ContextualClass with values, active, success, warning, danger and info, that could work too.

I'm essentially looking to style table rows using the newRowItem without creating a concurrent set of static variables for ContextualClasses.

**Comment by martin-g** [comment]
Wait!
Initially you said `danger` & Co. and now you talk about `striped` & Co.
Which ones you really mean?
Please check `TableBehavior`.

**Comment by heryqk** [comment]
Sorry for the confusion, I do mean `danger` & co.

I meant adding the contextual classes to the Table class or creating a new class named ContextualClass.

**Comment by martin-g** [comment]
Which Table class ?

**Comment by heryqk** [comment]
I'm referring to the 

 public static final class Table {} in de.agilecoders.wicket.core.util.CssClassNames

**Comment by tahitiangabriel** [comment]
You will have to create a class like the LabelBehavior and probably reuse LabelType (that is using the same css classes).
On all your <td> and <tr> you will have to bind a WebmarkupContainer.

**Comment by heryqk** [comment]
You recommend I add this myself or should those classes be added to wicket-bootstrap-core ?

I believe list-group / list-group-item should have the same treatment ?

**Comment by tahitiangabriel** [comment]
I mean you could create a new beahivor like the LabelBehavior for TD,TH and TR and send a PR. ;-)

And if you are talking about http://getbootstrap.com/components/#list-group-contextual-classes, yes that would be nice also.

**Comment by heryqk** [comment]
Sounds good !

I'll do that. Thanks !!

Eric H.

**Comment by heryqk** [comment]
PR #615 should address this.
