### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by eBeyond** [l0rdn1kk0n/wicket-bootstrap#622]
It would be great if the wiki could be more improved.

- There are some pages marked as TBD
- The images aren't shown anymore (in nearly all existing pages)

**Comment by martin-g** [comment]
I've updated the existing docs.
I won't mind to receive some help with the rest of the stuff (TBDs and TODOs).

**Comment by eBeyond** [comment]
I would support as far as I can.

**Comment by martin-g** [comment]
Looking forward to your contributions!
Thank you, @eBeyond !
