### ISSUE TITLE
datetimepicker cannot be set to multidate

### ISSUE THREAD

**Issue by mikey75** [l0rdn1kk0n/wicket-bootstrap#623]
bootstrap-datepicker.js has a resource for setting multidate selection support. Alas, I can't seem to find this being wicketified in wicket-bootstrap. No setMultidate type of setter for any of the components from bootstrap-datepicker, nor their *Config classes. Any info of how to go about this? I'd like to be able to set multiselection on a datepicker.

Regards,
Michal

**Comment by martin-g** [comment]
Pull Request is the best way!

**Comment by martin-g** [comment]
But you should also be able to extend the Config class and use it in your app in the meantime.

**Comment by mikey75** [comment]
Tnx. Actually I am confused now since wicket-bootstrap-extensions pom.xml depends on Eonasdan-bootstrap-datepicker which does not have  multi option, and the wicket-bootstrap wiki says it uses https://github.com/eternicode/bootstrap-datepicker which is completely different codebase. Any ideas?

**Comment by mikey75** [comment]
Okay, seems that if you  call DateTimePicker - it uses Eonasdan picker, and the DateTextField will use the bootstrap3 picker which has a config part that can be extended. Actually it is ok i think, because one can build his own DateTimePicker using the bootstrap3 parts. If one wants easy, go with DateTimePicker. Sorry for troubling you :) @martin-g

**Comment by martin-g** [comment]
I'll update the Wiki.
Thanks!

**Comment by mikey75** [comment]
If someone's interested here's how i did that. Comments welcome 
https://gist.github.com/mikey75/55d3b9b7776c5925b11ff602dee9a8df

**Comment by martin-g** [comment]
This is how it is supposed to be extended :+1:

**Comment by mikey75** [comment]
tnx for the merge, i think the issue is a close now.
