### ISSUE TITLE
0.10.6 Has empty CSS for material design?

### ISSUE THREAD

**Issue by d2a-raudenaerde** [l0rdn1kk0n/wicket-bootstrap#625]
Maybe I'm doing something wrong, but as I add the maven dependency to wicket-bootstrap-themes, all my .css files are empty?

I use this dependency:

```
		<dependency>
			<groupId>de.agilecoders.wicket</groupId>
			<artifactId>wicket-bootstrap-themes</artifactId>
			<version>0.10.6</version>
		</dependency>
```

**Comment by martin-g** [comment]
I cannot reproduce the problem.

```diff
diff --git i/bootstrap-samples/src/main/java/de/agilecoders/wicket/samples/WicketApplication.java w/bootstrap-samples/src/main/java/de/agilecoders/wicket/samples/WicketApplication.java
index 717a12b..61c9ff4 100644
--- i/bootstrap-samples/src/main/java/de/agilecoders/wicket/samples/WicketApplication.java
+++ w/bootstrap-samples/src/main/java/de/agilecoders/wicket/samples/WicketApplication.java
@@ -4,6 +4,8 @@ import java.io.IOException;
 import java.io.InputStream;
 import java.util.Properties;
 
+import de.agilecoders.wicket.core.settings.SingleThemeProvider;
+import de.agilecoders.wicket.themes.markup.html.material_design.MaterialDesignTheme;
 import net.ftlines.wicketsource.WicketSource;
 
 import org.apache.wicket.Application;
@@ -208,7 +210,7 @@ public class WicketApplication extends WebApplication {
      */
     private void configureBootstrap() {
         final IBootstrapSettings settings = new BootstrapSettings();
-        final ThemeProvider themeProvider = new BootswatchThemeProvider(BootswatchTheme.Flatly);
+        final ThemeProvider themeProvider = new SingleThemeProvider(new MaterialDesignTheme());//BootswatchThemeProvider(BootswatchTheme.Flatly);
 
         settings.setJsResourceFilterName("footer-container")
                 .setThemeProvider(themeProvider)
```

I've made the change above locally and I can see MaterialDesign theme being used by the samples application.

In addition I just double checked https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-themes/src/main/java/de/agilecoders/wicket/themes/markup/html/material_design/css/bootstrap-material-design.css and https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-themes/src/main/java/de/agilecoders/wicket/themes/markup/html/material_design/css/bootstrap-material-design.min.css

**Comment by martin-g** [comment]
Please provide steps to reproduce and we will reopen the issue!

**Comment by d2a-raudenaerde** [comment]
I downloaded the maven artifact: wicket-bootstrap-themes/0.10.6/wicket-bootstrap-themes-0.10.6.

When expanding the jar, I see a 'material_design/css' package, that contains material-fullpalette.css and material.css, but both files are empty ?

**Comment by martin-g** [comment]
I'll make a new release these days!

**Comment by martin-g** [comment]
Duplicate of #593

**Comment by d2a-raudenaerde** [comment]
Thanks! Do you have any idea when the release will take place?

**Comment by martin-g** [comment]
Maybe tomorrow.
I want to update the dependencies (themes, js, Maven) first.
