### ISSUE TITLE
BootstrapFileInput does not localize

### ISSUE THREAD

**Issue by margrie91** [l0rdn1kk0n/wicket-bootstrap#629]
We are running wicket version 6.23.0 and we noticed a bug in wicket-extensions (ver. 0.9.16):
BootstrapFileInput does not localize/translate itself.

**Comment by martin-g** [comment]
Please provide more information.
Even better a quickstart application.

**Comment by martin-g** [comment]
A Pull Request would be welcome!
See http://plugins.krajee.com/file-input#translations
