### ISSUE TITLE
Questions about BootstrapFileInput 

### ISSUE THREAD

**Issue by dermitdemwolftanzt** [l0rdn1kk0n/wicket-bootstrap#630]
Have some questions about BootstrapFileInput,
1. the field is shrinked in firefox but it looks good in chrome. Do you have any bugfixes for firefox?
(To reproduce this: http://wb-mgrigorov.rhcloud.com/extensions/BootstrapFileInput)
2. Are there any possibilities to limit the number of files (for eg. : only one) to be uploaded without using javascript?

Thank you in advance

**Comment by martin-g** [comment]
Please see the linked commits.
Thank you for the questions/report!

**Comment by dermitdemwolftanzt** [comment]
Great, thank you :D
