### ISSUE TITLE
BootstrapMultiSelect

### ISSUE THREAD

**Issue by mikey75** [l0rdn1kk0n/wicket-bootstrap#633]
Would someone please post a gist or an example of how to use BootstrapMultiSelect with a backing model, with ajax update (no page reload on submit)

**Comment by martin-g** [comment]
Hi @mikey75,

What have you tried ?
Please create a demo application that doesn't work and we will either fix it for you or improve Wicket Bootstrap to support your use case.

**Comment by mikey75** [comment]
I want to use BootstrapMultiSelect outside of a form, as a standalone component. So when I clicked an option, i'd like a model to update. But I already resolved it. Just added AjaxEventBehavior("changed.bs.select") (which is an ajax event fired from the bootstrap-select.js after selecting an option) and do processInput() there. Maybe it will be useful to someone.

**Comment by martin-g** [comment]
Thank you for sharing your solution!
