### ISSUE TITLE
BootstrapFileInput : how to set the file extensions

### ISSUE THREAD

**Issue by dermitdemwolftanzt** [l0rdn1kk0n/wicket-bootstrap#634]
How could set the file extensions for BootstrapFileInput (analogoes to _allowedFileExtensions_ parameter) ? It seems to me the FileInputConfig does't support it yet, is it correct?
When I tried to make a workaround to this, I found other issue about getMarkupId() Method. Not sure if it's only related to BootstrapFileInput Component. To  reproduce this problem:
//**bfi** is your BootstrapFileInput instance
...
bfi.setOutputMarkupId(true);
...
                       @Override
			public void renderHead(IHeaderResponse response) {
				super.renderHead(response);
			        String initScript = "$('#"+bfi.getMarkupId()+"').fileinput({ \"allowedFileExtensions\": [\"jpeg\", \"jpg\", \"tiff\", \"gif\", \"png\"]}";
				response.render(OnLoadHeaderItem.forScript(initScript));
			}
The problem here: I got **different markup id**. Is it an known Issue? I haven't find anything about this.
For any tips or helps to set _allowedFileExtensions_ parameter properly, thank you in advance

**Comment by dermitdemwolftanzt** [comment]
by the way I'm using wicket version 7.4.0 and wicket bootstrap version 0.10.8-SNAPSHOT

**Comment by martin-g** [comment]
Hi,

I'll take a deeper look next week!

In the meantime you should extend the Config and use your specialization
instead.

PR is very welcome too!
Thanks!

**Comment by martin-g** [comment]
Did my suggestion work ?

**Comment by dermitdemwolftanzt** [comment]
No unfortunately not, seems not applied and I can't see them in HTML output. If I put in renderHead method, I can see them in HTML output, but it doesn't apply. Only if I put them in my HTML page, then it gets apply, _the same code_. 
`<script>$("#id14").fileinput({ "allowedFileExtensions": ["jpeg", "jpg", "tiff", "gif", "png"]});</script>`
And I need to hardcode the markupid, since the method getMarkupId() doesn't return the same value. Have you any ideas ?

**Comment by martin-g** [comment]
There you go!
I've also added support for `allowedFileTypes`.

**Comment by dermitdemwolftanzt** [comment]
Thank you :+1:
