### ISSUE TITLE
Cached URLSources in LessCacheManager are causing issues

### ISSUE THREAD

**Issue by strido** [l0rdn1kk0n/wicket-bootstrap#635]
The cached URLSources in LessCacheManager is problems during the compilation, see http://mail-archives.apache.org/mod_mbox/wicket-users/201609.mbox/%3CCAMomwMpCe3B2sCjEnvAQtbjKt-7trHzK%3DHVgUdPC%2BzxO3RZLKA%40mail.gmail.com%3E for some background information for this issue.

The compilation in LessCacheManager will add imports to the cached URLSource.importedSources, if multiple threads are compiling the same URLSource will add imports in the less files multiple times. This can easily be illustrated by compiling the same URLSource twice and clearing the cache in the LessCacheManager in between, see the added tests in this commit https://github.com/strido/wicket-bootstrap/commit/2be0d8d4294162bd103e63c74198d90457e6069e .
It is also possible for a race conditon in the AbstractHierarchicalSource.addImportedSource when using cached URLSources. The list that imports are added to is not thread safe and it is possible for null items in the list.

I think the reason for the cached URLSources is to make it possible to fetch a correct last modified time of all files included in the compilation. This is however only true after the first compilation and the time returned by LessCacheManager.getLastModifiedTime.

I have been trying to figure out how to fix this myself but I have not been able to find a solution that will work in all cases.

**Comment by strido** [comment]
I have created a branch where I'm trying to solve this issue, see https://github.com/strido/wicket-bootstrap/tree/clear-cache

**Comment by martin-g** [comment]
Merged! Thanks, Erik!
