### ISSUE TITLE
Carousel and CarouselImages

### ISSUE THREAD

**Issue by dermitdemwolftanzt** [l0rdn1kk0n/wicket-bootstrap#637]
Would like to use CarouselImage but it has string url in constructor. My Question: Is there any way to convert Image to CarouselImage, so that I could use them. Background: I have Images which come from services as byte[]. I have used DynamicImageResource to create Images for them, and now I would like to use carousel to display them. What is the best way to implement this? Thank you in advance.

**Comment by martin-g** [comment]
You just need to override de.agilecoders.wicket.core.markup.html.bootstrap.carousel.Carousel#newImageList() and return a ListView that uses your list of images.
