### ISSUE TITLE
Alert does not render message body

### ISSUE THREAD

**Issue by Shengche** [l0rdn1kk0n/wicket-bootstrap#644]
As I upgrade Wicket from 6.24.0 to 6.25.0 with wicket-bootstrap 0.9.20, the alert component doesn't render message correct (empty string in web page). I checked the server log, the message did send to server! When I fall back wicket with 6.24.0, it works correctly.

**Comment by martin-g** [comment]
Can you provide a quickstart app? Or modify the samples application to show the regression.
Thanks!

**Comment by Shengche** [comment]
Sure, as the attachment.

--------------------------------------------------------------------
----------------------------------->
To boldly go where no man has gone before.
--------------------------------------------------------------------
----------------------------------->
We do this not because it is easy. We do this because it is hard.
-----------------------------------------------------------------
-------------------------------------->
If I have seen further it is by standing on the shoulders of giants.
----------------------------------------------------------
--------------------------------------------->
front713@gmail.com
--------------------------------------------------------------------------------------------->

**Comment by Shengche** [comment]
Sure,

**Comment by Shengche** [comment]
Sure, thanks.

[isssues.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/571810/isssues.zip)

**Comment by Shengche** [comment]
Hey, buddy!

Do you have any suggestion?

And the component BootstrapAjaxPagingNavigator also has the same issue, the page number doesn't render!

**Comment by martin-g** [comment]
I'll take a look at the coming days.
I've forgotten about this issue ...

**Comment by martin-g** [comment]
I see no difference in the behavior of your demo application in 6.24 and 6.25.
What do you expect to happen with `alert.info("TEST MSG");` ? This message will appear only in FeedbackPanel/NotificationPanel but not in Alert itself.

**Comment by martin-g** [comment]
Please create a separate issue for the problem with BootstrapAjaxPagingNavigator.
With a demo application!
