### ISSUE TITLE
Apache Wicket 8.0.0.M2 - Wicket Bootstrap 0.10.11 - Summernote - error after Ajax call on Firefox

### ISSUE THREAD

**Issue by francois92** [l0rdn1kk0n/wicket-bootstrap#645]
Hi Martin,

With Apache Wicket 8.0.0.M2 and Wicket Bootstrap 0.10.11 I get an error when I use Summernote after an Ajax call with Firefox 49.0.2 on max OSX.
Everything is ok with Safari.

ERROR: Wicket.Ajax.Call.processEvaluation: Exception evaluating javascript: TypeError: node is null, text: (function(){;(function() {
    var summernoteConfig = {"ToolbarOptions":{"Style":["style","fontname","fontsize","color","bold","italic","underline","strikethrough","clear"],"Layout":["ul","ol","paragraph","height"],"Insert":["link","table","hr"],"Misc":["fullscreen","codeview","undo","redo","help"]},"overlayTimeout":2000,"maxFilesize":2097152,"height":350,"airMode":false,"imageUploadUrl":"./?0-1.0-OfferDescriptionEditionPanelView-form-text","summernoteEditorId":"text"};
    var summernote = $('#'+summernoteConfig.summernoteEditorId);
    
I made a quickstart.  

François
[quickstart.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/578726/quickstart.zip)

**Comment by martin-g** [comment]
Hi François,

See the README for the correct version you should use with Wicket 8.0.0

**Comment by francois92** [comment]
Hi Martin,

This is the one I use : 8.0.0.M2

**Comment by francois92** [comment]
Sorry I understand I should use the 0.10.6

**Comment by martin-g** [comment]
No, I meant https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-7.x/README.md: `Wicket 8.x and Bootstrap 3.3.7: 2.x`.
I.e. you need to use Wicket Bootstrap 2.x for Wicket 8.x.
I'll promote 0.10.x to 1.0.0 together with 2.0.0.

**Comment by martin-g** [comment]
Everything works fine with 2.0.0-M2-SNAPSHOT.

**Comment by martin-g** [comment]
I'll release 2.0.0-M3 because it has the fix for the Fragments.

**Comment by martin-g** [comment]
Done!

**Comment by francois92** [comment]
super thanks a lot !

François
