### ISSUE TITLE
Opinion? Overridable header close button markup for BootstrapModal

### ISSUE THREAD

**Issue by mikey75** [l0rdn1kk0n/wicket-bootstrap#646]
Hi,

What do you say to an idea of having the close button in the header overridable. For now the only way to make it something other than:

`<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>`

is to create own markup for the whole modal. But suppose you want to have a button with an image and perhaps some custom ajax event on it. There's no way to do it without copying whole modal markup to your own instead of just extending the body part.

The idea od having most of the modal parts overridable (buttons, header label etc) is very cool but why the damn close button in the header has no wicket:id and the factory method? There is however an overridable createHeader() method but I don't get the idea of what it is for, since you cannot create a whole new header (both label and button) with it. Or maybe I can't see how. (hint me) 

Anyway what do you think? 
M.

**Comment by martin-g** [comment]
Hint: send us a Pull Request! :-)
Thank you in advance!

**Comment by mikey75** [comment]
I meant to, but first I need to know if that functionality is ever needed to anyone but me :)

**Comment by mikey75** [comment]
https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/647

**Comment by mikey75** [comment]
Hello @martin-g :) bump. Any comments?
