### ISSUE TITLE
Jquery on 

### ISSUE THREAD

**Issue by dutrieux** [l0rdn1kk0n/wicket-bootstrap#649]
I try to use the classe JQuery to build javascript 'on' function :
```javascript
$("#component").on("dp.change", function (e) {
...
})
```
but the method 'on' of Jquery class accept only JavaScriptInlineFunction parameter and JavaScriptInlineFunction not accept to build function with parameter

Could you please change the signature of method to accept IFunction rather than JavaScriptInlineFunction

Best regards

Duto

**Comment by martin-g** [comment]
Moved to https://github.com/l0rdn1kk0n/wicket-jquery-selectors/issues/21
