### ISSUE TITLE
de.agilecoders.wicket.jquery.Attr not serializable

### ISSUE THREAD

**Issue by dutrieux** [l0rdn1kk0n/wicket-bootstrap#650]
Hello,

It would be really nice if `de.agilecoders.wicket.jquery.Attr` could me implement `IClusterable` for Serializable.

Thx advance

Duto

**Comment by martin-g** [comment]
Hi!

Do you mind send us Pull Requests for your suggestions at https://github.com/l0rdn1kk0n/wicket-jquery-selectors ?

Thanks!

**Comment by dutrieux** [comment]
https://github.com/l0rdn1kk0n/wicket-jquery-selectors/pull/19
