### ISSUE TITLE
wicket 6.25 breaks ButtonGroup

### ISSUE THREAD

**Issue by gsaviane** [l0rdn1kk0n/wicket-bootstrap#652]
Wicket-bootstrap 0.9.20 and Wicket 6.25.0 together makes ButtonGroup component to throw an exception:

`org.apache.wicket.WicketRuntimeException: The component(s) below failed to render...`

Reverting back the project reference to Wicket 6.24 make it working. See attached quickstart

[broken-buttonList.tar.gz](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/666624/broken-buttonList.tar.gz)

**Comment by johnjcool** [comment]
we also have this issue

**Comment by martin-g** [comment]
Indeed the problem is related to https://issues.apache.org/jira/browse/WICKET-6219.
I'll release 0.9.21!

**Comment by martin-g** [comment]
0.9.21 is released!

Happy New Year!
