### ISSUE TITLE
Add DropDownSubMenu to version 0.10.x Bootstrap 3.x

### ISSUE THREAD

**Issue by mavortius** [l0rdn1kk0n/wicket-bootstrap#656]
I don't found a DropDownSubMenuButton to version 0.10.x. Is it possible?

**Comment by martin-g** [comment]
Please be a bit more detailed.

**Comment by mavortius** [comment]
I'm referring to [#144](https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/144) but in the latest versions it was apparently removed. I have found [this](https://vsn4ik.github.io/bootstrap-submenu/) and I think it could be implemented.

**Comment by martin-g** [comment]
I don't see anything related to this in the huge PR #144.
Do you want to contribute this feature ?

**Comment by mavortius** [comment]
I could but I don't have time at this moment. Perhaps in the future... It could be included in future releases I think.

**Comment by martin-g** [comment]
OK. I'll close the issue for now.
Ping us to reopen it when you have something!
Thanks!
