### ISSUE TITLE
brandImage is stateful if no image is defined

### ISSUE THREAD

**Issue by ursjoss** [l0rdn1kk0n/wicket-bootstrap#663]
If you don't set a resource reference for the brandImage, the component is stateful. This prevents e.g. using a stateless form in a login page with the navbar on the same page. For any navbar with no visible brandImage, the component should be stateless IMHO.

**Comment by ursjoss** [comment]
See https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/664

**Comment by martin-g** [comment]
#664 has been merged!
