### ISSUE TITLE
Font Awesome Problems

### ISSUE THREAD

**Issue by felixh85** [l0rdn1kk0n/wicket-bootstrap#665]
Hi guys,

I really like your project and I am currently trying to setup my first wicket-bootstrap application. However, I have some problems integrating the Font Awesome extension and I would really appreciate if you could help me out.

I am trying to implement some kind navigation strip where I want to add some links which are represented by some Icons. My code looks like this:

HTML:
`<a wicket:id="editProject" href="#" style="margin-left: 300px">
<i wicket:id="editProjectIcon"></i>
</a>
 <a wicket:id="addProject" href="#">
<i wicket:id="addProjectIcon"></i> 
</a>`

Java:
`AjaxLink<Void> editProjectLink = new AjaxLink<Void>("editProject") {
			@Override
			public void onClick(AjaxRequestTarget target) {
				//Do something
			}
		};
		editProjectLink.setOutputMarkupId(true);
		editProjectLink.add(new Icon("editProjectIcon", FontAwesomeIconTypeBuilder.on(FontAwesomeGraphic.edit).size(Size.large).build()));
		projectContainer.add(editProjectLink);

		AjaxLink<Void> addProjectLink = new AjaxLink<Void>("addProject") {
			@Override
			public void onClick(AjaxRequestTarget target) {
				//Do something
			}
		};
		addProjectLink.setOutputMarkupId(true);
		addProjectLink.add(new Icon("addProjectIcon",FontAwesomeIconTypeBuilder.on(FontAwesomeGraphic.plus).size(Size.large).build()));
		projectContainer.add(addProjectLink);`

However, with this code the Icons are not shown. If I add Text to the links in the HTML it is shown. Could you please give me a hint what I am doing wrong. Thank you!

**Comment by martin-g** [comment]
I believe your question is to FontAwesome project itself, not to Wicket-Bootstrap. It is a CSS issue.
Try by making the icon with fixed width: FontAwesomeIconTypeBuilder.on(FontAwesomeGraphic.plus).size(Size.large)`.fw()`.build()

**Comment by felixh85** [comment]
Thank you for your quick answer. Thanks to your advice I figured out my problem. You were right that it was a CSS problem. The font-awesome.css was missing. I added the following Code to the renderHead method of my BasePage and now it works fine.
`response.render(CssHeaderItem.forReference(FontAwesomeCssReference.instance()));`
Thanks again for your support!
