### ISSUE TITLE
SummernoteEditor forces CDN resource reference for Font Awesome

### ISSUE THREAD

**Issue by mpostelnicu** [l0rdn1kk0n/wicket-bootstrap#673]
Hi,

Any reason we are forcing CDN resource reference in `SummernoteEditor` renderHead method ? 

` response.render(CssHeaderItem.forReference(FontAwesomeCDNCSSReference.instance()));`

isn't this something that can be controlled via 

`BootstrapSettings.useCdnResources(true);`  ? 

I'd like to remove all external resource references, and SummernoteEditor is the only component i found that is loading this CDN resource forcefully. 

Thanks

**Comment by martin-g** [comment]
It is an oversight!
Please send a Pull Request and I'll apply it!
Thank you!

**Comment by mpostelnicu** [comment]
@martin-g  thanks again for integrating the fix. any plans to release `0.10.14` soon ? 

thx

**Comment by martin-g** [comment]
It is on its way to Maven Central!
Enjoy!

**Comment by mpostelnicu** [comment]
thanks !
