### ISSUE TITLE
ConfirmationBehavior removes original title

### ISSUE THREAD

**Issue by eximius313** [l0rdn1kk0n/wicket-bootstrap#684]
I have a simple link:

HTML: ```<a wicket:id="delete"><i class="fa fa-trash"></i></a>```
JAVA:
```
AjaxLink<String> delete = new AjaxLink<String>("delete") {
	@Override
	public void onClick(AjaxRequestTarget target) {
		System.out.println("CLICK!");
	}
};
delete.add(AttributeAppender.append("title", "Delete"));
add(delete);
```

When I open the page and hover the mouse over the link - browser displays proper title.
Unfortunately, if I add ```ConfirmationBehavior```
```
delete.add(new ConfirmationBehavior(new ConfirmationConfig().withTitle("Are you sure?")));
```
title is no longer displayed. Moreover, instead ```Confirmation header``` I see ```My title```
As far as I can see in [bootstrap-confirmation documentation](http://bootstrap-confirmation.js.org/#ex-link) ```title``` is something different than ```data-title``` (which is absolutly corrent, because Link can have ```title="Delete"``` and ```data-title="Are you sure?"```)

Could you please fix this behaviour in Wicket Bootstrap

**Comment by martin-g** [comment]
This is how `bootstrap-confirmation.js` works - it copies its options as attributes: https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-7.x/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/confirmation/bootstrap-confirmation.js#L49.
You should suppress with option `copyAttributes: false`.

**Comment by martin-g** [comment]
Actually this should copy just `href` and `target`, so `title` should stay as is.
`ConfirmationBehavior` doesn't do anything with the attributes. So it must be the JavaScript.
Are you able to reproduce this in the samples application ?

**Comment by eximius313** [comment]
I have my showcase, but I completly removed Lombok and unnecessary components and added LocalRepository as you asked so you shouldn't have any problems... just run ```./gradlew bootRun```
[wicket-showcase-confirmation.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/1071652/wicket-showcase-confirmation.zip)

**Comment by martin-g** [comment]
Here is what happens:
1) bootstrap-confirmation depends on Bootstrap Popover
2) Popover depends on Bootstrap Tooltip
3) Tooltip "eats" your title

I don't see any way to opt out at http://getbootstrap.com/javascript/#tooltips.
So you have two options:
1) add `deleteConfirm.add(new TooltipBehavior(Model.of("Delete")));` and enjoy Bootstrap styled tooltip
2) create an issue at Bootstrap tracker and ask them to add a way to opt-out

**Comment by eximius313** [comment]
@martin-g, I will create ticket in Bootstrap, but could you please elaborate a bit about this opt-out? What do you mean by that? 
I was trying to understand how "opt-out" is related to "eating" my title, but I still don't :(

**Comment by martin-g** [comment]
I've debugged it again and after all the seems to be in bootstrap-confirmation.js.
Here is the stacktrace and the method in Bootstrap's tooltip.js that unsets the title.
![title-lost-issue](https://user-images.githubusercontent.com/232002/27456144-331ef15e-57a0-11e7-9bb1-a664e4864747.png)

**Comment by martin-g** [comment]
IMO the problem is that bootstrap-confirmation.js passes `options` object to tooltip.js without `options.selector` property:
```javascript
    this.options.selector ?
      (this._options = $.extend({}, this.options, { trigger: 'manual', selector: '' })) :
      this.fixTitle()
```
 and this leads to the call to `fixTitle()`
