### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by jchappelle** [l0rdn1kk0n/wicket-bootstrap#687]
The link is located on the project home page here: http://wb-mgrigorov.rhcloud.com/

Here's the link's destination:
https://codeload.github.com/l0rdn1kk0n/wicket-bootstrap/tar.gz/bootstrap-parent-0.10.7-SNAPSHOT

**Comment by martin-g** [comment]
Fixed by removing this useless link!
Thanks!
