### ISSUE TITLE
ConfirmationBehavior doesn't work in onInitialize

### ISSUE THREAD

**Issue by eximius313** [l0rdn1kk0n/wicket-bootstrap#694]
Having ```ConfirmationBehavior``` in onInitialize causes Tooltip to display, but action is invoked anyway.
Having ```ConfirmationBehavior``` in constructor causes a lot of:
```Tried to retrieve a localized string for a component that has not yet been added to the page. This can sometimes lead to an invalid or no localized resource returned. Make sure you are not calling Component#getString() inside your Component's constructor.```

test case in [attachment](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/1222790/showcase-confirmationInOnInitialize.zip):
```Submit Good``` works, but causes warnings
```Submit Bad``` fires the action immediately

**Comment by eximius313** [comment]
BTW - please look at HomePage.html source

**Comment by Stmated** [comment]
@eximius313 Not sure if you figured out a solution to this or not, but for me it worked by registering the ConfirmationBehavior before `super.onInitialize()` of the component you are adding the Behavior to.

I guess this has to do with the order that the JavaScript listening to "click" is added to the DOM... so the confirmation behavior must be added before the Ajax Form Component Updating Behavior or whatnot.

**Comment by eximius313** [comment]
@Stmated 
I confirm that your workaround is working

**Comment by martin-g** [comment]
Closing, since there is a workaround.

**Comment by eximius313** [comment]
Since this is a workaround and not an actual fix - maybe it's a good idea to describe that in documentation?
