### ISSUE TITLE
Incorrect doco on the wiki page regarding metro theme

### ISSUE THREAD

**Issue by chrisco484** [l0rdn1kk0n/wicket-bootstrap#698]
wicket-bootstrap has a metro theme and it's sourced from "idleberg" at:

https://github.com/idleberg/m8tro-bootstrap

however, the wicket-bootstrap home page, when referring to the metro theme has a link to "TalksLab's" metro theme (a different metro theme altogether) at:

https://github.com/TalksLab/metro-bootstrap

This is misleading and incorrect. I started filing some issues with the metro theme against the TalksLab metro-bootstrap project believing it was the one I was using because the above link implied that's where wicket-bootstrap's 'metro' theme is sourced - whooops! :)

I think the wicket-bootstrap home page should be changed to link to the IdleBerg metro project instead.

**Comment by martin-g** [comment]
Fixed!
Thanks!
