### ISSUE TITLE
For components that call instance methods during initialization, move initialization from the constructor to onInitialize()

### ISSUE THREAD

**Issue by ageery** [l0rdn1kk0n/wicket-bootstrap#699]
Here's a concrete example. 

I would like to create a non-abstract sub-class of DropDownButton which, rather than having to sub-class DropDownButton to provide the list of buttons, would pass a lambda in the constructor to provide the list of buttons.

However, I can't do this because the constructor of DropDownButton calls newSubMenuButtons. The DropDownButton constructor is called before the constructor for my sub-class is called. This means that my sub-class, which implements the newSubMenuButtons method, can't see the lambda that has been passed in via the constructor because the sub-class's constructor hasn't yet been executed which sets an instance variable with the value of the constructor parameter.

The solution to this is simply to move the logic from the constructor and put it into the Wicket onInitialize() method. Everything should work exactly the same; the only difference is that the component is a little more flexible for sub-classing.

Does that make sense? I can send some pull requests of components I'm interested in changing (another example is Modal).

See also: https://stackoverflow.com/questions/18348797/why-is-it-considered-bad-practice-to-call-a-method-from-within-a-constructor

Thank you!

**Comment by martin-g** [comment]
PR is welcome!

**Comment by martin-g** [comment]
Closing since there is no interest in this improvement.
Please send a PR if you still need it!
