### ISSUE TITLE
Material icons

### ISSUE THREAD

**Issue by tahitiangabriel** [l0rdn1kk0n/wicket-bootstrap#700]
Hi,

I would like to use Material icons from https://material.io/icons/

While glyphicon and fontawesome use the same kind of syntax (icon name is in the class) : 
`<i class="fa fa-address-book"></i>`

Material uses this syntax (the name of the icon is not in the class but between the tags):
`<i class="material-icons">3d_rotation</i>`

I do not see an easy way to provide a MaterialIconType that would works with the actual code.
I guess I would have to refactor Icon, IconBehavior and IconType.

@martin-g Any tought on this?

At least tomorrow I will provide an IIcon interface so one can provide its own implementation in the newIcon() function of the BootstrapButton.

**Comment by martin-g** [comment]
Yes, it seems the current Icon impl won't be able to render such markup.
Some refactoring is required!

**Comment by martin-g** [comment]
PR is merged!
