### ISSUE TITLE
Please upgrade to Wicket-M8

### ISSUE THREAD

**Issue by eximius313** [l0rdn1kk0n/wicket-bootstrap#704]
@martin-g could you please upgrade Wicket-bootstrap to Wicket-M8?

**Comment by chrisco484** [comment]
According to the wiki page if you use version 2.x it is integrated with Wicket 8:

> Wicket 8.x and Bootstrap 3.3.7: 2.x

**Comment by eximius313** [comment]
yes, with Wicket8-M6. Now Wicket8-M8 is out

**Comment by martin-g** [comment]
Is https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/705 a prerequisite for this release or no ?

**Comment by eximius313** [comment]
It would be very good, but not required, I think

**Comment by martin-g** [comment]
I can cut a release now!
But I don't have time to rework the DateTextField.

**Comment by eximius313** [comment]
ok, do it ;)

**Comment by eximius313** [comment]
will you make it also for your dependent libraries like `wicket-jquery-selectors`?

**Comment by martin-g** [comment]
Yes!

**Comment by martin-g** [comment]
Done!

**Comment by eximius313** [comment]
Thanks, @martin-g 
I just tested it and it works fine.
By the way - I see that you directly depend on `joda`:
```
joda-time:joda-time:2.3 -> 2.9.9
+--- de.agilecoders.wicket:wicket-bootstrap-core:2.0.0-M7
|    +--- project :components
|    |    \--- compileClasspath
|    +--- de.agilecoders.wicket:wicket-bootstrap-themes:2.0.0-M7
|    |    \--- project :components (*)
|    \--- de.agilecoders.wicket:wicket-bootstrap-extensions:2.0.0-M7
|         \--- project :components (*)
\--- de.agilecoders.wicket:wicket-bootstrap-extensions:2.0.0-M7 (*)
```
Maybe it would be good to depend on `org.wicketstuff:wicket-datetime:8.0.0-M8` instead?

**Comment by martin-g** [comment]
Or maybe Joda is needed in WB ?!

**Comment by eximius313** [comment]
of course, but I thought that it is required for date fields, that are taken from `wicket-datetime`. 
But maybe I'm wrong ;)
