### ISSUE TITLE
Demo site down

### ISSUE THREAD

**Issue by Shengche** [l0rdn1kk0n/wicket-bootstrap#706]
Deas

http://wb-mgrigorov.rhcloud.com/

the demo site have down for days, please reactive it , thanks.

**Comment by martin-g** [comment]
Unfortunately RedHat dropped their free hosting at OpenShift.
Do you know of another free hosting for Java Servlet apps ?

**Comment by Shengche** [comment]
I have own server to host it, do you need it ?

Url may be https://wb.teliclab.info ?

--------------------------------------------------------------------
----------------------------------->
To boldly go where no man has gone before.
--------------------------------------------------------------------
----------------------------------->
We do this not because it is easy. We do this because it is hard.
-----------------------------------------------------------------
-------------------------------------->
If I have seen further it is by standing on the shoulders of giants.
----------------------------------------------------------
--------------------------------------------->
front713@gmail.com
--------------------------------------------------------------------------------------------->

**Comment by martin-g** [comment]
That would be awesome!
Please deploy 7.x or 8.x!

**Comment by Shengche** [comment]
OK, a moment!

--------------------------------------------------------------------
----------------------------------->
To boldly go where no man has gone before.
--------------------------------------------------------------------
----------------------------------->
We do this not because it is easy. We do this because it is hard.
-----------------------------------------------------------------
-------------------------------------->
If I have seen further it is by standing on the shoulders of giants.
----------------------------------------------------------
--------------------------------------------->
front713@gmail.com
--------------------------------------------------------------------------------------------->

**Comment by chrisco484** [comment]
We've just signed up for a few more Rack Units so we would have some
capacity to host the sample pages if you like.

 

 

________________________________

**Comment by martin-g** [comment]
@chrisco484 Yes, please!

**Comment by chrisco484** [comment]
Do you know roughly how much traffic the pages were getting before?

 

Were they all served from a single tomcat?

 

________________________________

**Comment by chrisco484** [comment]
Would it be ok to put an advertising banner in there somewhere? It would
help recover some of our costs ;) 

 

________________________________

**Comment by chrisco484** [comment]
Presumably there's one or more .war files that need to be hosted.

 

Do you know where I could find them or build them?

 

I really want to get these samples back online quickly before they lose
all their SEO weights with the search engines (well, there is only one
that counts ;) )

 

________________________________

**Comment by martin-g** [comment]
> Do you know roughly how much traffic the pages were getting before?

No idea, but I guess it is not much.


> Were they all served from a single tomcat?

Yes.


> Would it be ok to put an advertising banner in there somewhere? It would
> help recover some of our costs ;)

Yes!


> Presumably there's one or more .war files that need to be hosted.

Just one. The artifact from samples module.

**Comment by chrisco484** [comment]
We should probably take this offline but we don't have each other's
private emails so if you go to this page I will get an email and then
I'll send you a direct email so you'll have mine:

 

https://www.stepaheadsoftware.com/contact

 

 

 

________________________________

**Comment by chrisco484** [comment]
I will supply the IP address of we webservers that will hosting it and
you can reconfigure the domain name's DNS settings and we should be able
to get it live again within a few hours.

 

________________________________

**Comment by martin-g** [comment]
The DNS name was provided by OpenShift ...
I do not own it.

**Comment by chrisco484** [comment]
Doh! I had not set up an admin email for the stepaheadsoftware.com
contact page so I didn't get the email!

 

I have configured it properly now, can you try this form again now?

 

https://www.stepaheadsoftware.com/contact

 

Regards,

Chris

 

 

 

 

________________________________

**Comment by chrisco484** [comment]
Ah, I see what you mean. The URL is http://wb-mgrigorov.rhcloud.com/

 

rhcloud.com is presumably Red Hat Cloud I can see they probably aren't
interested in having a URL with their name in it pointing to a webserver
they don't control.

 

That means all those existing links on the web will continue to be
broken. Is it possible to ask them to set up a permanent redirect to the
new website for all requests that come to that old URL:
wb-mgrigorov.rhcloud.com?

 

That way people we will avoid people being hit with a 'page not found'
error - which looks really bad.

 

________________________________

**Comment by chrisco484** [comment]
Do you know what this site was meant to be?

 

It's also down at the moment:

 

http://wicketconsole.appspot.com/

 

 

________________________________

**Comment by martin-g** [comment]
The is https://github.com/wicketstuff/core/tree/master/console-parent/console-examples.
This module in WicketStuff is not maintained since a long time. Its contributor doesn't use Wicket in his new job and stopped maintaining it.

**Comment by chrisco484** [comment]
So should we host this as well as the one that was on rhcloud?

 

________________________________

**Comment by martin-g** [comment]
I don't think so. No one asked for this demo for the last few years. Just recently someone noticed that it is gone.

**Comment by Shengche** [comment]
Dears

http://coding.teliclab.info/wicket-7.x/

http://coding.teliclab.info/wicket-8.x/

--------------------------------------------------------------------
----------------------------------->
To boldly go where no man has gone before.
--------------------------------------------------------------------
----------------------------------->
We do this not because it is easy. We do this because it is hard.
-----------------------------------------------------------------
-------------------------------------->
If I have seen further it is by standing on the shoulders of giants.
----------------------------------------------------------
--------------------------------------------->
front713@gmail.com
--------------------------------------------------------------------------------------------->

**Comment by martin-g** [comment]
Thank you, @Shengche !

I will add the links to the READMEs in the respective branches!

@l0rdn1kk0n Hi! Could you please remove the obsolete link in the project description ? I do not have permissions to do it myself. Thank you!

**Comment by Shengche** [comment]
No problem, this is my honor!

--------------------------------------------------------------------
----------------------------------->
To boldly go where no man has gone before.
--------------------------------------------------------------------
----------------------------------->
We do this not because it is easy. We do this because it is hard.
-----------------------------------------------------------------
-------------------------------------->
If I have seen further it is by standing on the shoulders of giants.
----------------------------------------------------------
--------------------------------------------->
front713@gmail.com
--------------------------------------------------------------------------------------------->

**Comment by martin-g** [comment]
@l0rdn1kk0n Ping!

**Comment by UlrichKnaack** [comment]
Hi,
what is the reason the link  http://wb-mgrigorov.rhcloud.com/ ist still present in the header section?

**Comment by martin-g** [comment]
I have no Admin rights for the project to remove it.

**Comment by martin-g** [comment]
@l0rdn1kk0n Ping!
