### ISSUE TITLE
Font Awesome 5

### ISSUE THREAD

**Issue by vrozkovec** [l0rdn1kk0n/wicket-bootstrap#707]
Hi, would you be interested in creating icon types for Font Awesome 5?
It is paid version, so including proper resources would be up to the user.

**Comment by martin-g** [comment]
Sure! Why not!
But as far as I can see it is not finished yet (https://fontawesome.com/)

**Comment by vrozkovec** [comment]
They have RC4 out. I can prepare a script and then just update generated classes, I guess it won't change much, just new icons will appear.

**Comment by martin-g** [comment]
:+1:

**Comment by ilgrosso** [comment]
Any update? Font Awesome 5 has been out for a while now...

**Comment by mat-ale** [comment]
+1 for the upgrade!

**Comment by ursjoss** [comment]
I'm working on this. PR expected this week-end.

**Comment by martin-g** [comment]
Done with #790
