### ISSUE TITLE
Bootstrap Wizard

### ISSUE THREAD

**Issue by vrozkovec** [l0rdn1kk0n/wicket-bootstrap#708]
Hi, would you be interested in Wizard component in Bootstrap style? 
For view I'd use Bootstrap's panels and for links Bootstrap buttons.

**Comment by martin-g** [comment]
Sure!

You mean Wicket Extensions' Wizard component, right ? Just styled with Bootstrap.
Or completely new one ?

**Comment by vrozkovec** [comment]
The one from the Extensions.

**Comment by martin-g** [comment]
Implemented with #712
