### ISSUE TITLE
Font Awesome 4.7.0

### ISSUE THREAD

**Issue by heryqk** [l0rdn1kk0n/wicket-bootstrap#717]
Good afternoon, what would the work effort be to upgrade to Font Awesome 4.7.0 in all branches ?

**Comment by martin-g** [comment]
Upgrading to 4.7.0 is as simple as touching the pom.xml files. 
But the new icons should be added manually.

**Comment by tahitiangabriel** [comment]
4.7.0 icons are already in the wicket-7 and wicket-8 branches.
In which branches do you want to add them? The master one I guess?

**Comment by heryqk** [comment]
I was hoping for wicket 6 support. 

Eric H.

**Comment by martin-g** [comment]
Then it is as simple as cherry-picking the change from 7.x/8.x into master and create a Pull Request!

**Comment by h0l0gram** [comment]
True, here we go: #724 
(unfortunately travis build fails due to the same issues with 7.x/8.x branch, but has nothing to do with this modifications)

**Comment by martin-g** [comment]
Merged it!
Thank you!
I'll cut a new release soon!

**Comment by h0l0gram** [comment]
awesome thanks! :-)
