### ISSUE TITLE
Please upgrade to M9

### ISSUE THREAD

**Issue by eximius313** [l0rdn1kk0n/wicket-bootstrap#719]
@martin-g - M9 is now released
Could you please upgrade?

**Comment by martin-g** [comment]
I'm having issues with maven-release-plugin and Sonatype OSS.
For some reason it doesn't upload `.asc` files and Sonatype rejects the closing of the staged release.

**Comment by martin-g** [comment]
Done!

**Comment by lludwa** [comment]
While upgrading wicket bootstrap from M7 to M8 in my project, building project with updated wicket-bootstrap failed, gives incoming cut stack trace:
``
 Could not find de.agilecoders.wicket:jquery-selectors:2.0.0-M5.
  Required by:
      project :components > de.agilecoders.wicket:wicket-bootstrap-core:2.0.0-M8
      project :components > de.agilecoders.wicket:wicket-bootstrap-themes:2.0.0-M8
      project :components > de.agilecoders.wicket:wicket-bootstrap-extensions:2.0.0-M8
 Could not find de.agilecoders.wicket.webjars:wicket-webjars:2.0.5.
  Required by:
      project :components > de.agilecoders.wicket:wicket-bootstrap-core:2.0.0-M8
      project :components > de.agilecoders.wicket:wicket-bootstrap-themes:2.0.0-M8
      project :components > de.agilecoders.wicket:wicket-bootstrap-less:2.0.0-M8
``
``
Cause 1: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find de.agilecoders.wicket:jquery-selectors:2.0.0-M5.
Required by:
    project :components > de.agilecoders.wicket:wicket-bootstrap-core:2.0.0-M8
    project :components > de.agilecoders.wicket:wicket-bootstrap-themes:2.0.0-M8
    project :components > de.agilecoders.wicket:wicket-bootstrap-extensions:2.0.0-M8
Cause 2: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find de.agilecoders.wicket.webjars:wicket-webjars:2.0.5.
Required by:
    project :components > de.agilecoders.wicket:wicket-bootstrap-core:2.0.0-M8
    project :components > de.agilecoders.wicket:wicket-bootstrap-themes:2.0.0-M8
    project :components > de.agilecoders.wicket:wicket-bootstrap-less:2.0.0-M8
``
I attached full stack trace of this problem.

[bootstrap-M8-stacktrace.txt](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/1748713/bootstrap-M8-stacktrace.txt)

**Comment by martin-g** [comment]
Re-released it!

**Comment by lludwa** [comment]
Still not working. Probably, your build failed.

**Comment by martin-g** [comment]
For some reason OSS Sonatype releases it only to https://oss.sonatype.org/content/repositories/releases/de/agilecoders/wicket/jquery-selectors/2.0.0-M5/ but it doesn't push it to Maven Central ...

**Comment by martin-g** [comment]
I've asked at https://issues.sonatype.org/browse/MVNCENTRAL-3184

**Comment by eximius313** [comment]
@martin-g - sounds simmilar to this issue: https://github.com/schaloner/deadbolt-2/issues/74#issuecomment-295606294

**Comment by martin-g** [comment]
jquery-selectors:2.0.0-M5 has been fixed by Sonatype guys.
Just released wicket-webjars:2.0.6 as well.
