### ISSUE TITLE
NullPointerException when not passing a ChoiceRenderer to BootstrapRadioGroup

### ISSUE THREAD

**Issue by Rentier** [l0rdn1kk0n/wicket-bootstrap#722]
If I use the constructor

```
    public BootstrapRadioGroup(String id, List<T> options) {
        this(id, null, options, null);
    }
```

for a `BootstrapRadioGroup`, then the call on `detachModel` throws a NPE:

```
    @Override
    protected void detachModel() {
        super.detachModel();
        for (IModel<? extends T> model: options) {
            model.detach();
        }
        choiceRenderer.detach();
    }
```

**Comment by Rentier** [comment]
The same is true for the model. I would propse to not pass null, but sane defaults, like `Model.of()` and `new DefaultRadioChoiceRenderer(Default, "")`

**Comment by martin-g** [comment]
I agree!
Do you want to send a Pull Request ?

**Comment by Rentier** [comment]
I will. Against which branch?

**Comment by martin-g** [comment]
`wicket-7.x`
I will port it to `wicket-8.x`

**Comment by martin-g** [comment]
The PR is merged!
