### ISSUE TITLE
Demo Application Navbar Dropdowns not working

### ISSUE THREAD

**Issue by namtar** [l0rdn1kk0n/wicket-bootstrap#739]
If I build the demo application locally I have the problem that the Dropdowns in the navbar are not working. It seems to have to do with the CodeBehavior used by the Code class that is added in the BasePage to a "pre" Tag with the wicket:id=code-internal.
The screenshots show the difference. All of the jquery javascript stuff is missing and I don´t know why.  

But if I call a missing query resource manually like this:
"http://localhost:8080/demo/wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-1.12.4.js" I get the correct javascript. I assume that the war artifact contains all what is needed.

Is there any special to do when building the demo application or when deploying it?

I built the whole project with "mvn clean install".
I tested both branches wicket-8.x and wicket-7.x.
I used a wildfly10.1.0 and a Tomcat8.5 and a Tomcat8.5 Docker Container on a Windows 10 System.
I tried a tomcat8.5 on a mac os x too.
I tried Java 8 and 10 for compiling and for running the tomcats.

Fail:
![demodropdownfail](https://user-images.githubusercontent.com/5657636/39260284-4a563372-48b9-11e8-8066-8b555f0d4e0d.PNG)
Working:
![demodropdownworking](https://user-images.githubusercontent.com/5657636/39260297-5151846a-48b9-11e8-9f55-7e33ef02c3cd.PNG)

**Comment by martin-g** [comment]
Fixed with https://github.com/l0rdn1kk0n/wicket-bootstrap/commit/cc32c65ecf222011485deb5d93401ede90a6380e
