### ISSUE TITLE
IncompatibleClassChangeError with Version 2.0.0

### ISSUE THREAD

**Issue by namtar** [l0rdn1kk0n/wicket-bootstrap#743]
When upgrading from Version 2.0.0-M7 to 2.0.0 I get an IncompatibleClassChangeError on Application Startup.
This is because Guava was removed from the jquery-selectors library and the "Generics2.transform(types, new Function<Type, String>()" Method now consumes a java.util.Function instead of the Guava one. But the TableBehavior still has the Guava function import. I don´t know why the project compiles although. Normally it should not I think.
Interestingly the Demo Application compiles and works, but my Application doesn´t.

I if replace the Guava import in the TableBehavior with java.util.Function all works as expected.

I am also able to remove the Guava maven dependency (com.google.guava:guava) without having any problems from the bootstrap-parent pom.xml.

Is this an appropriate solution or will this cause any errors I am not aware of? If you want I will provide a pull request that contains the two named changes.

Is it possible to do a minor release for the fix? That would be nice. Thank you for your effort.

Stracktrace:
`java.lang.IncompatibleClassChangeError
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
de.agilecoders.wicket.jquery.util.Generics2.transform(Generics2.java:144)
de.agilecoders.wicket.core.markup.html.bootstrap.table.TableBehavior.createCssClassNames(TableBehavior.java:86)
de.agilecoders.wicket.core.markup.html.bootstrap.table.TableBehavior.onComponentTag(TableBehavior.java:100)
org.apache.wicket.Component.renderComponentTag(Component.java:3924)
org.apache.wicket.Component.internalRenderComponent(Component.java:2478)
org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1592)
org.apache.wicket.Component.internalRender(Component.java:2287)
org.apache.wicket.Component.render(Component.java:2218)
org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1453)
org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1653)
org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1628)
org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:797)
org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:77)
org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112)`

**Comment by martin-g** [comment]
Guava has been removed from `jquery-selectors` project but it is still a dependency for WB.
The build of WB passes successfully. 
Does your project depend on a different version of Guava ?

**Comment by martin-g** [comment]
Which version of Java do you use ?

**Comment by namtar** [comment]
I am currently on JDK 1.8.0_131 (Oracle JDK). 
My project does not use any Guava dependency.

**Comment by martin-g** [comment]
I'll release 2.0.1 now!

**Comment by namtar** [comment]
Thank you very much. Have a nice weekend.

**Comment by martin-g** [comment]
Done!
Have a nice weekend, @namtar !
Thank you for the report!
