### ISSUE TITLE
Version 2.0.1 wicket-8.x Navbar: Guava clashes with java.util.function

### ISSUE THREAD

**Issue by namtar** [l0rdn1kk0n/wicket-bootstrap#745]
In the Navbar component I have an error at runtime (IncompatibleClassChangeError). 
The cause is similar to https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/743

The two private inner classes
* de.agilecoders.wicket.core.markup.html.bootstrap.navbar.Navbar.PositionFilter
* de.agilecoders.wicket.core.markup.html.bootstrap.navbar.Navbar.NavbarComponentToComponentFunction
are used in the _de.agilecoders.wicket.core.markup.html.bootstrap.navbar.Navbar#newPositionDependedComponentModel_ method as parameters for the _Generics2.filter_ and _Generics2.transform_ method calls.

The _filter_ method expects a java.util.function.Predicate and
the _transform_ method expects a java.util.function.Function 
but the two inner classes implement the guava counterparts which causes an error at runtime.

The BS wicket-8.x build passes successfully for some reason.
I am on JDK 1.8.0_131 (Oracle JDK) and my project does not use any guava.

Would it be a solution to remove the guava imports from the Navbar class und use only the java.util.function.* interfaces? Only the two inner classes are using these imports at the moment.

I searched the project for usages of Generics2 and the Navbar seems to be the last remaining place where this problem can occur.

Thank you.

**Comment by martin-g** [comment]
2.0.2 is on its way to Maven Central!

Thanks for reporting!
