### ISSUE TITLE
[bs4] Navbar issue with wicket:panel tag

### ISSUE THREAD

**Issue by mweirauch** [l0rdn1kk0n/wicket-bootstrap#753]
Versions: `wicket-bootstrap:3.0.0-M1` (with `spring-boot:2.0.4.RELEASE` and `wicket-spring-boot:2.1.1`)

When `MarkupSettings#stripWicketTags==false` the `<wicket:panel>` tag within the `<nav>` tag which holds the navbar components seems to break some css rules to the extend, that the navbar components are rendered below the navbar brand and not right next to it.

Stripping the wicket tags fixes the "issue". Unsure if this qualifies as a bug and even more so if there's an easy fix for this, if it needs fixing at all. Just wanted to mention.

**Comment by martin-g** [comment]
Thanks for the report, @mweirauch !
This is a known issue. I will add a note to the project README about it. If `<wicket:xyz>` elements are not stripped then the Bootstrap CSS rules are broken and many things do not render properly.

PR is welcome too!

**Comment by mweirauch** [comment]
Is #754 in the style you imagined?

**Comment by martin-g** [comment]
Yep! Perfect!
