### ISSUE TITLE
New version of wicket-boostrap example

### ISSUE THREAD

**Issue by Shengche** [l0rdn1kk0n/wicket-bootstrap#758]
Dears, I can find the latest version is 0.10.4, where can I get the 0.10.17 or 2.x even 3.x ?

**Comment by martin-g** [comment]
Reopening because we have to update the READMEs with the new urls.

**Comment by Shengche** [comment]
Thans, @martin-g

**Comment by martin-g** [comment]
Updated them!

Thank you, @Shengche !

**Comment by martin-g** [comment]
Updated them!

Thank you, @Shengche !

**Comment by martin-g** [comment]
Updated the READMEs!

Thank you, @Shengche !

**Comment by Shengche** [comment]
Hooray ~
--------------------------------------------------------------------
----------------------------------->
To boldly go where no man has gone before.
--------------------------------------------------------------------
----------------------------------->
We do this not because it is easy. We do this because it is hard.
-----------------------------------------------------------------
-------------------------------------->
If I have seen further it is by standing on the shoulders of giants.
----------------------------------------------------------
--------------------------------------------->
front713@gmail.com
--------------------------------------------------------------------------------------------->
