### ISSUE TITLE
Readme contains two "Current release versions" sections

### ISSUE THREAD

**Issue by chrisco484** [l0rdn1kk0n/wicket-bootstrap#765]
Hi guys,

I just noticed that the Readme.md contains two sections marked "Current release versions". The first does not mention Bootstrap 4 but the second section does.

Will the real "Current release versions" section please step forward? :)

**Comment by martin-g** [comment]
Everything is correct! There are two `current` versions - both with Wicket 8.x, but one with Bootstrap 3. and another with Bootstrap 4.x.
One day the one with Bootstrap 4.x should become the only one but most people still use Bootstrap 3.x for now.
