### ISSUE TITLE
Please upgrade to 8.2.0

### ISSUE THREAD

**Issue by eximius313** [l0rdn1kk0n/wicket-bootstrap#769]
8.2.0 is now released :)
http://wicket.apache.org/news/2018/11/17/wicket-8.2.0-released.html

**Comment by martin-g** [comment]
Someone should show you how to create Pull Requests instead of just issues.

**Comment by eximius313** [comment]
Do you really care about my knowledge or is it just a pleasant way to say "don't bother me"?

**Comment by chrisco484** [comment]
Hi @eximius313,

I'm not sure how long you've been working with open source projects on github so please forgive me if this is stating the obvious:

- Issues are for when you don't know what's wrong and you can't resolve a problem yourself and you want someone else to help out.
- Pull requests are when you already know what's wrong so it's possible for you to make the change yourself and test it, commit it and then make that change available to the community via a pull request.

Your initial comment suggests that you know what's wrong.

Your second comment expresses that you are a smart person with a lot of knowledge.

I think @martin-g 's comment is acknowledging your knowledge and skill and he is encouraging you to help contribute to the community.

**Comment by eximius313** [comment]
And what If I'm not working with this project anymore and don't have possibility to test it?
I could:
a) Just ignore it
b) Issue a feature request so maybe somebody who can contribute will spot it and do it.

Isn't it what isses are also for?
Which one would you choose @chrisco484?

**Comment by martin-g** [comment]
> Do you really care about my knowledge or is it just a pleasant way to say "don't bother me"?

I've asked you because the change is simple enough to create a PR instead of an issue.
But also so you can see that even simple PRs like this one is not that simple. Wicket-Bootstrap depends also on WicketStuff Core which is not yet released.



> Issue a feature request so maybe somebody who can contribute will spot it and do it.

Be sure that I follow Wicket and its ecosystem and I will make a release once everything is ready.

**Comment by eximius313** [comment]
> I've asked you because the change is simple enough to create a PR instead of an issue.
But also so you can see that even simple PRs like this one is not that simple.

I'm absolutely aware that it's not `simple change`, that is why I thought that it's better to open this issue

> Be sure that I follow Wicket and its ecosystem.

and I'm absolutely aware of this too, but thanks to this issue now everyone can know that:

> Wicket-Bootstrap depends also on WicketStuff Core which is not yet released [...] and I will make a release once everything is ready.

**Comment by martin-g** [comment]
Blocked by https://github.com/l0rdn1kk0n/wicket-webjars/pull/57#issuecomment-440164385

**Comment by martin-g** [comment]
2.0.6 and 3.0.0-M7 have been released

**Comment by eximius313** [comment]
Thank you
