### ISSUE TITLE
Upgrade to latest bootstrap-select

### ISSUE THREAD

**Issue by reckart** [l0rdn1kk0n/wicket-bootstrap#771]
Upgrade to latest bootstrap-select to make the `data-container` attribute available which was introduced in the following commit:

https://github.com/snapappointments/bootstrap-select/commit/f2358a15e7b3cdba519a22ada9b7654ab6775255

**Comment by martin-g** [comment]
Please create a Pull Request!

**Comment by martin-g** [comment]
Done!

**Comment by reckart** [comment]
Thanks :) Sorry for not getting around to providing the PR...
