### ISSUE TITLE
[3.0.0-M8] Class not found: de.agilecoders.wicket.extensions.markup.html.bootstrap.form.select.BootstrapSelect

### ISSUE THREAD

**Issue by ilgrosso** [l0rdn1kk0n/wicket-bootstrap#772]
The above mentioned class seems to not be found in 3.0.0-M8: is there any upgrade guide I forgot to follow?

**Comment by martin-g** [comment]
From which version do you come ? 2.0.7 ?

It has been removed with https://github.com/l0rdn1kk0n/wicket-bootstrap/commit/e8cb937bdacc97769bf0f7436c1000a8606325fe#diff-4e3dc438ed62076a9d9c100e9360e74d because at the time the widget was not available for Bootstrap 4.x.
I see that it is available now (https://developer.snapappointments.com/bootstrap-select/) so we need to add it back.
PR is welcome!

**Comment by martin-g** [comment]
The code is reinstated!
Please test it when you have a chance!

**Comment by ilgrosso** [comment]
From which Maven repository are the `3.0.0-M9-SNAPSHOT` artifacts available?
It seems I cannot find them from Sonatype: https://oss.sonatype.org/content/repositories/snapshots/de/agilecoders/wicket/wicket-bootstrap-core/ (last is `2.0.0-M7-SNAPSHOT` there)

**Comment by martin-g** [comment]
I just deployed 3.0.0-M9-SNAPSHOT !

**Comment by ilgrosso** [comment]
Any reason why the [GlyphIconType](https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-8.x/bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/image/GlyphIconType.java) class was removed? Is there a replacement?

**Comment by ilgrosso** [comment]
I replaced

```java
DropDownButton realms = new DropDownButton(
                "realms", new ResourceModel("select", ""), new Model<IconType>(GlyphIconType.folderopen)) {
```

with

```java
DropDownButton realms = new DropDownButton(
                "realms", new ResourceModel("select", ""), new Model<IconType>(new IconType("folder-open") {

                    private static final long serialVersionUID = -766102819082263718L;

                    @Override
                    public String cssClassName() {
                        return "glyphicon glyphicon-" + getCssClassName();
                    }
                })) {
```

and build passes - let's if it also works as expected...

**Comment by martin-g** [comment]
> Any reason why the [GlyphIconType](https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-8.x/bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/image/GlyphIconType.java) class was removed? Is there a replacement?

If I remember correctly Bootstrap 4.x doesn't provide the fonts anymore.

**Comment by ilgrosso** [comment]
> If I remember correctly Bootstrap 4.x doesn't provide the fonts anymore.

Ah, I see - then my workaround above - which works, I could verify it in the meanwhile - is adequate, as I am adding such fonts in my local project.

Thanks for your support!
