### ISSUE TITLE
Replace junit 4 with junit 5 and mockito-core 1.x with 2.x

### ISSUE THREAD

**Issue by ursjoss** [l0rdn1kk0n/wicket-bootstrap#775]

**Comment by ursjoss** [comment]
I will have a go at this this or next week.

**Comment by martin-g** [comment]
I have done this recently at work and I can do it almost mechanically.
@ursjoss please let me know if you don't prefer to spend your time on something more interesting!

**Comment by ursjoss** [comment]
Ok @martin-g, please go ahead, thanks

**Comment by martin-g** [comment]
Done!
