### ISSUE TITLE
Housekeeping with old branches

### ISSUE THREAD

**Issue by ursjoss** [l0rdn1kk0n/wicket-bootstrap#789]
Not sure what the policy in this repo is. There's quite a lot of old branches slumbering in the repo. Would it make sense to delete those?

**Comment by martin-g** [comment]
Sure! I will delete most of them!

**Comment by martin-g** [comment]
Done!

**Comment by ursjoss** [comment]
Thanks @martin-g . You're really very quick and responsive.
