### ISSUE TITLE
Problem with customizing theme

### ISSUE THREAD

**Issue by VaclavC** [l0rdn1kk0n/wicket-bootstrap#794]
Hello,

  I'am trying to customize theme with wicket-bootstrap-3.0.0-M8. I have created my own theme using a custom.scss file. This file contains only

`@import "webjars!bootstrap/current/scss/bootstrap.scss"`

line for now. But I'am getting 

`Error: File to import not found or unreadable: functions.`

from Sass compiler. When I try to import functions.scss, I get no error. What I'am doing wrong?

**Comment by martin-g** [comment]
Please provide a quickstart application and we will take a look

**Comment by VaclavC** [comment]
Here:

https://github.com/VaclavC/Test-BootstrapCustomTheme

**Comment by martin-g** [comment]
Gradle :disappointed:

**Comment by VaclavC** [comment]
It's a problem?

**Comment by martin-g** [comment]
Yes, it is hard for me to link it with Wicket-Bootstrap -SNAPSHOT module in
the IDE because it is Maven based. And harder to debug any fixes.

I can copy your files in Maven based quickstart project.

**Comment by VaclavC** [comment]
Ah, sorry. I don't even have Maven installed in my Eclipse. But next time I probably can create it with Maven for you.

**Comment by VaclavC** [comment]
I have created a maven based quickstart:

https://github.com/VaclavC/Test-BootstrapCustomTheme-MVN

Hope that it is all right ...

**Comment by martin-g** [comment]
Thank you!
This will help processing it faster!

**Comment by VaclavC** [comment]
Great. I want to use it ;-)

**Comment by martin-g** [comment]
Asked at https://gitlab.com/jsass/jsass/issues/82

**Comment by martin-g** [comment]
@iref Since you implemented this - do you have an idea why it does not work now ? I see logic to add second import with the underscore at de.agilecoders.wicket.sass.UrlImporter but JSass still complains about the missing import.

**Comment by iref** [comment]
hmm might be a problem with import traversal, because UrlImporter expands the absolute path from previous Import. I'll try to do more research.

**Comment by iref** [comment]
Looks like `URI.resolve` builds incorrect path when joining `webjar://../bootstrap/scss/` with `functions.scss`. Result is `functions.scss` instead of absolute path, so file isn't found at classpath.
I will try to fix it during the weekend.

**Comment by VaclavC** [comment]
So I have read the response to jsass issue at GitLab. Now I'am not sure, if I should solve it somehow in my application or if it will be solved in wicket-bootstrap?

**Comment by martin-g** [comment]
It will be solved in Wicket-Bootstrap.

**Comment by iref** [comment]
I created PR with the fix. Sorry, it took so long, I've been busy at work.

**Comment by martin-g** [comment]
The PR is merged!
@VaclavC please try with 3.0.0-M9-SNAPSHOT. I've just deployed it to Sonatype Snapshots repo.
