### ISSUE TITLE
Wicket 8 branch + bootstrap 4.3.1 ConfirmationBehavior 

### ISSUE THREAD

**Issue by nmwael** [l0rdn1kk0n/wicket-bootstrap#799]
Seems to suffer this issue:
https://github.com/mistic100/Bootstrap-Confirmation/issues/100

upgrading to 4.0.3 should fix it. id be happy to open a PR if it speeds up the process :)

**Comment by martin-g** [comment]
PRs definitely speed up the process!

**Comment by nmwael** [comment]
I've upgraded to 4.1.0 and made a pr

**Comment by martin-g** [comment]
Thank you for the PR!
3.0.0-M10 has been released and soon will be at Maven Central!
