### ISSUE TITLE
Bootstrap Confirmation [wicket-bootstrap-extensions] + AjaxCheckBox

### ISSUE THREAD

**Issue by nmwael** [l0rdn1kk0n/wicket-bootstrap#801]
Does not stop Wicket event from happening, any idea on howto stop it? 

updateAjaxAttributes in AjaxCheckBox does support a precondition via ajaxCallListener but that needs to return true of false. But I cannot see howto use it via Bootstrap confirmation..

**Comment by martin-g** [comment]
Please use users@wicket.apache.org or StackOverflow.com for questions
