### ISSUE TITLE
Modal close handler event 'hidden' is incorrect 

### ISSUE THREAD

**Issue by ganzd** [l0rdn1kk0n/wicket-bootstrap#803]
In de.agilecoders.wicket.core.markup.html.bootstrap.dialog.Modal method addCloseHandlerScript is used incorrect event name, it should be 'hidden.bs.modal' instead of currently used 'hidden'. This causes close handler not to be triggered.

Version 0.10.18.

**Comment by martin-g** [comment]
Please send a Pull Request!
Also please provide a link to the Bootstrap documentation about this event.
Thank you!

**Comment by ganzd** [comment]
`$('#myModal').on('hidden.bs.modal', function (e) {
  // do something...
})`

See https://getbootstrap.com/docs/3.4/javascript/#modals

**Comment by ganzd** [comment]
I'll create, no problem. Thank you!

**Comment by martin-g** [comment]
Fixed it!
Thank you!
