### ISSUE TITLE
LabelBehavior and LabelType Deprecation in Bootstrap 4

### ISSUE THREAD

**Issue by heryqk** [l0rdn1kk0n/wicket-bootstrap#808]
With Bootstrap 4, labels (label label-style) are replaced with Badge. Would it make sense to deprecate LabelBehavior and LabelType in Wicket 8 + Bootstrap 4 branch and replace the implementation with BadgeBehavior instead ?

**Comment by martin-g** [comment]
Sure! Please send us a Pull Request!

For the record, please provide a link to Bootstrap docs where they explain that labels are replaced.
