### ISSUE TITLE
DateTable with NavigationToolbar that displays a textbox to jump to a page of records directly

### ISSUE THREAD

**Issue by ursjoss** [l0rdn1kk0n/wicket-bootstrap#813]
Hi

I am probably overlooking something. I ought to modify the navigation toolbar to also offer jumping to a page of records by entering a number directly. I guess this corresponds to `"pagingType": "full_numbers"`.

What's the way to achieve this? Would I have to create my own implementation of the `BootstrapDefaultDataTable` referencing my own implementation of `BootstrapNavigationToolbar` or is there a way to configure the pagingType used in the default implementation provided by wicket-bootstrap?

Thanks up-front for some hints
Urs

**Comment by martin-g** [comment]
Hi,

I have the feeling you talk about this JS plugin : https://mdbootstrap.com/docs/jquery/tables/pagination/
If this is the case then I'm afraid there is no integration for it yet in Wicket-Bootstrap.

But you don't need to use this JS plugin to have this functionality. You need to customize `de.agilecoders.wicket.core.markup.html.bootstrap.navigation.BootstrapPagingNavigator` and plug it at `de.agilecoders.wicket.extensions.markup.html.bootstrap.table.toolbars.BootstrapNavigationToolbar#newPagingNavigator()`

**Comment by ursjoss** [comment]
Thank you, @martin-g, for the quick response. Yes I was talking about the JS plugin as an analogy. I'll give it a try, closing this issue for now.
