### ISSUE TITLE
Wicket 9 Compatibility

### ISSUE THREAD

**Issue by theigl** [l0rdn1kk0n/wicket-bootstrap#827]
Hi,

I wanted to verify my application against the latest build of Wicket 9 (M4). Startup currently fails with the following stacktrace:

`
java.lang.NoSuchMethodError org.apache.wicket.util.time.Time org.apache.wicket.util.io.Connections.getLastModified(java.net.URL)
de.agilecoders.wicket.less.LessCacheManager.findLastModified(LessCacheManager.java:181)
`

`Connections.getLastModified(java.net.URL)` now returns a `java.time.Instant` instead of `org.apache.wicket.util.time.Time`.

Would it be possible to create a new branch that compiles against Wicket 9?

**Comment by martin-g** [comment]
The branch is already here: https://github.com/l0rdn1kk0n/wicket-bootstrap/tree/wicket-9.x
Which version of Wicket Bootstrap did you use ?
You have to use https://search.maven.org/artifact/de.agilecoders.wicket/wicket-bootstrap-core/4.0.0-M3/bundle

**Comment by theigl** [comment]
@martin-g: Sorry i totally missed that! I'll test against that branch.

**Comment by bgooren** [comment]
Hi!

Sorry for hijacking this thread, but we are having the same issue as the OP; After upgrading some of our internal libraries to wicket 9.0.0-M4 and wicket-bootstrap-core 4.0.0-M3, simple unit tests started failing on our build server; I am also getting these locally when I run the test suite:

```
java.lang.NoSuchMethodError: org.apache.wicket.markup.head.JavaScriptHeaderItem.forReference(Lorg/apache/wicket/request/resource/ResourceReference;Lorg/apache/wicket/request/mapper/parameter/PageParameters;Ljava/lang/String;Z)Lorg/apache/wicket/markup/head/JavaScriptReferenceHeaderItem;
	at de.agilecoders.wicket.core.markup.html.bootstrap.behavior.BootstrapJavascriptBehavior.renderHead(BootstrapJavascriptBehavior.java:33)
	at de.agilecoders.wicket.core.markup.html.bootstrap.behavior.BootstrapResourcesBehavior.renderHead(BootstrapResourcesBehavior.java:42)
	at de.agilecoders.wicket.core.markup.html.bootstrap.behavior.BootstrapBaseBehavior.renderHead(BootstrapBaseBehavior.java:79)
	at org.apache.wicket.Component.internalRenderHead(Component.java:2654)
...
```
If have double-checked that we are loading the correct libraries, and the dependency tree is clean;
To triple check I added some debugging logs to a failing test:

```
System.out.println( BootstrapJavascriptBehavior.class.getResource( "BootstrapJavascriptBehavior.class" ) );
        System.out.println( JavaScriptHeaderItem.class.getResource( "JavaScriptHeaderItem.class" ) );
```
which outputs:
```
jar:file:/Users/bas/.m2/repository/de/agilecoders/wicket/wicket-bootstrap-core/4.0.0-M3/wicket-bootstrap-core-4.0.0-M3.jar!/de/agilecoders/wicket/core/markup/html/bootstrap/behavior/BootstrapJavascriptBehavior.class
jar:file:/Users/bas/.m2/repository/org/apache/wicket/wicket-core/9.0.0-M4/wicket-core-9.0.0-M4.jar!/org/apache/wicket/markup/head/JavaScriptHeaderItem.class
```

Finally, I tried refreshing the jars; Alas, none of the above helped to fix this.
We are running our build job on openjdk 11.0.5 (centos 7)
I am running locally on oracle jdk 11.0.1 (mac os)

To help debug this I have created a quickstart which demonstrates this issue (on my computer).

[myproject-quickstart.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/4077879/myproject-quickstart.zip)

**Comment by bgooren** [comment]
PS We are in the process of upgrading to wicket 9 and bootstrap 4 - I noticed that the wicket 9 bootstrap version is (only) available for bootstrap 3.4.0; Is it possible to publish a bootstrap 4 version as well?

**Comment by martin-g** [comment]
I'll cut a new release these days.
There are some API breaks in latest Wicket milestone.

**Comment by martin-g** [comment]
On Fri, Jan 17, 2020, 19:14 Sebastian Gooren <notifications@github.com>
wrote:

> PS We are in the process of upgrading to wicket 9 and bootstrap 4 - I
> noticed that the wicket 9 bootstrap version is (only) available for
> bootstrap 3.4.0; Is it possible to publish a bootstrap 4 version as well?
>
This will take me some time.
Pull request is welcome!
