### ISSUE TITLE
Wicket 9.x version of bootstrap 4.x

### ISSUE THREAD

**Issue by bgooren** [l0rdn1kk0n/wicket-bootstrap#828]
I am creating this ticket in response to a short conversation in ticket #827

> PS We are in the process of upgrading to wicket 9 and bootstrap 4 - I
> noticed that the wicket 9 bootstrap version is (only) available for
> bootstrap 3.4.0; Is it possible to publish a bootstrap 4 version as well?
>
This will take me some time.
Pull request is welcome!

Can you let me know what would be the easiest way to make this happen? Would you recommend branching "wicket-8.x-bootstrap-4.x" and upgrading that to wicket 9, or starting with the "wicket-9.x" branch and cherry picking all changes from the "wicket-8.x-bootstrap-4.x" branch? Probably starting with the bootstrap 4.x branch is best since the upgrade to wicket 9.x has been very smooth in my experience. But I just want to make sure before I do any work on this. Thanks!

**Comment by martin-g** [comment]
Upgrading wicket-8.x-bootstrap-4.x to Wicket 9 should be easier.

I'll create the new branch tomorrow!

**Comment by martin-g** [comment]
`wicket-9.x-bootstrap-4.x` is created!

**Comment by bgooren** [comment]
Thanks! I'll try do some work on it this week :-)

**Comment by solomax** [comment]
Hello @martin-g,
I'm new to Webjars
I have issues with `popper.js` It is referenced as follows https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-9.x-bootstrap-4.x/bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/references/PopperJavaScriptReference.java#L24

BUT the jar itself doesn't have `"popper.js/current/umd/popper.js"` it has `"popper.js/1.14.1/umd/popper.js"`

Should it work?

**Comment by martin-g** [comment]
Yes! Wicket-webjars should handle it

**Comment by martin-g** [comment]
@bgooren In case you didn't notice: @solomax upgraded Wicket to 9.0.0-M4!
Try with a local build and if everything is OK then I can cut the first release of this branch.

**Comment by solomax** [comment]
@martin-g it seems version need to be changed
I found 4.0.0-M* at https://repo1.maven.org/maven2/de/agilecoders/wicket/wicket-bootstrap-core/4.0.0-M3/

And I have 1 question `mvn clean install` is not creating source artifacts
How it can be created?

**Comment by bgooren** [comment]
Thank you for beating me to it, @solomax :-) (and @martin-g for letting me know)
Will have a look.

**Comment by martin-g** [comment]
> I found 4.0.0-M* at

I've changed it to 5.0.0-M1-SNAPSHOT!



> And I have 1 question `mvn clean install` is not creating source artifacts
> How it can be created?

It does create -sources.jar here. It does not create for the common testing module.
If it does not create them for you then please explain in more details what you are doing so I can reproduce it.

Thanks!

**Comment by solomax** [comment]
> I've changed it to 5.0.0-M1-SNAPSHOT!

Please update README :))

> 
> > And I have 1 question `mvn clean install` is not creating source artifacts
> > How it can be created?
> 
> It does create -sources.jar here. It does not create for the common testing module.
> If it does not create them for you then please explain in more details what you are doing so I can reproduce it.

just did `mvn clean install` then search using `find -type f -name *.jar` - found no sources
The problem I'm facing - debugging is useless without sources :(

`mvn -version`
```
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T02:00:29+07:00)
Maven home: /opt/maven
Java version: 11.0.6, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-29-generic", arch: "amd64", family: "unix"
```

**Comment by martin-g** [comment]
Here are my steps:

1. git checkout wicket-9.x-bootstrap-4.x
1. rm -rf ~/.m2/repository/de/agilecoders/wicket/*
1. mvn11 clean install -DskipTests=true
1. find ~/.m2/repository/de/agilecoders/wicket/ -name "*-sources*"
```
/home/martin/.m2/repository/de/agilecoders/wicket/wicket-bootstrap-sass/5.0.0-M1-SNAPSHOT/wicket-bootstrap-sass-5.0.0-M1-SNAPSHOT-sources.jar
/home/martin/.m2/repository/de/agilecoders/wicket/wicket-bootstrap-sass/5.0.0-M1-SNAPSHOT/wicket-bootstrap-sass-5.0.0-M1-SNAPSHOT-sources.jar.asc
/home/martin/.m2/repository/de/agilecoders/wicket/wicket-bootstrap-samples/5.0.0-M1-SNAPSHOT/wicket-bootstrap-samples-5.0.0-M1-SNAPSHOT-sources.jar.asc
/home/martin/.m2/repository/de/agilecoders/wicket/wicket-bootstrap-samples/5.0.0-M1-SNAPSHOT/wicket-bootstrap-samples-5.0.0-M1-SNAPSHOT-sources.jar
/home/martin/.m2/repository/de/agilecoders/wicket/wicket-bootstrap-themes/5.0.0-M1-SNAPSHOT/wicket-bootstrap-themes-5.0.0-M1-SNAPSHOT-sources.jar
/home/martin/.m2/repository/de/agilecoders/wicket/wicket-bootstrap-themes/5.0.0-M1-SNAPSHOT/wicket-bootstrap-themes-5.0.0-M1-SNAPSHOT-sources.jar.asc
/home/martin/.m2/repository/de/agilecoders/wicket/wicket-bootstrap-core/5.0.0-M1-SNAPSHOT/wicket-bootstrap-core-5.0.0-M1-SNAPSHOT-sources.jar
/home/martin/.m2/repository/de/agilecoders/wicket/wicket-bootstrap-core/5.0.0-M1-SNAPSHOT/wicket-bootstrap-core-5.0.0-M1-SNAPSHOT-sources.jar.asc
/home/martin/.m2/repository/de/agilecoders/wicket/wicket-bootstrap-extensions/5.0.0-M1-SNAPSHOT/wicket-bootstrap-extensions-5.0.0-M1-SNAPSHOT-sources.jar.asc
/home/martin/.m2/repository/de/agilecoders/wicket/wicket-bootstrap-extensions/5.0.0-M1-SNAPSHOT/wicket-bootstrap-extensions-5.0.0-M1-SNAPSHOT-sources.jar
```

**Comment by solomax** [comment]
I tried one more time with same result 
Maybe someone else can also try?
Can it be caused by some global maven setting ?

**Comment by mweirauch** [comment]
No "-sources" generated for me either using afforementioned instructions. (mvn `3.5.4`)

**Comment by solomax** [comment]
FTR: this command do the job for me `mvn clean source:jar-no-fork install`

Can someone else try this version?
It seems it works for me and _maybe_ worth a release :)))

**Comment by martin-g** [comment]
I could cut a release anytime you ask me to do it!

As I said before: here there is no problem with the -sources.jar, so I cannot test this myself.

**Comment by solomax** [comment]
If there is no objection: Let it be release :))

BTW according to https://mvnrepository.com/artifact/de.agilecoders.wicket/wicket-bootstrap-core lots of releases has `M` suffix ... 
is it on purpose?

**Comment by martin-g** [comment]
> is it on purpose

yes, the migration to Bootstrap 4.x was work in progress.
I personally do not use it so I cannot say whether it is stable or not.
If the users say it is stable enough for a proper non-milestone release then I will remove the `M`.

**Comment by solomax** [comment]
Actually all 3.x releases are also have M suffix ...

**Comment by martin-g** [comment]
Yes, all Bootstrap 4.x releases were WIP.
I am aware of just 2 people using them (from the bug reports). You are the third one :-)

**Comment by martin-g** [comment]
5.0.0-M1 has been released!
