### ISSUE TITLE
Active tab in BootstrapTabbedPanel not styled correctly

### ISSUE THREAD

**Issue by perjo** [l0rdn1kk0n/wicket-bootstrap#830]
An active tab within a BootstrapTabbedPanel is not styled with a rounded border indicating that it is active. It seems the active class added to the wrong element. In [the bootstrap docs ](https://getbootstrap.com/docs/4.0/components/navs/) it is added to with the a.nav-link element. Wicket-bootstrap adds the active class to the li.nav-item element.

**Comment by martin-g** [comment]
Thanks for the report, @perjo !
Do you like to send a Pull Request with a fix ?
