### ISSUE TITLE
BootstrapFileInputField does not allow setting the icon for cancelling

### ISSUE THREAD

**Issue by reckart** [l0rdn1kk0n/wicket-bootstrap#850]
BootstrapFileInputField uses glyphicon by default, but that is not available by default with Bootstrap 4. While overriding the icons for most buttons, the icon for the cancel button cannot be set.

**Comment by martin-g** [comment]
Do you like to send a Pull Request ?
Some third party widgets (like Bootstrap FileInput) may not have a version for Bootstrap 4 or may just need an update.
Help is welcome!

**Comment by reckart** [comment]
I have the changes locally already - so yes, expect a PR for this one. Whatever I'm using atm in terms of widgets looks okish, although I had to set up a shim SCSS mapping some old Bootstrap 3 names to corresponding Bootstrap 4 classes.

**Comment by reckart** [comment]
Change has been merged.
