### ISSUE TITLE
BootstrapTabbedPanel has missing css attributes

### ISSUE THREAD

**Issue by igorky** [l0rdn1kk0n/wicket-bootstrap#858]
In bootstrap v4.4 tabs should have more css attributes to be displayed correctly.
Every 'a' tag should have 'nav-item nav-link' classes.

https://getbootstrap.com/docs/4.4/components/navs/#tabs

**Comment by martin-g** [comment]
https://getbootstrap.com/docs/4.4/components/navs/#tabs actually says:

```
ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
```

And WB follows the same structure: https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-8.x-bootstrap-4.x/bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/tabs/BootstrapTabbedPanel.html#L8

**Comment by martin-g** [comment]
Closing this.
We will reopen if needed!

**Comment by igorky** [comment]
@martin-g , sorry, by mistake I updated dependency to 4.0.0-M5. Rolled back to 3.0.0 and it's good now.

**Comment by igorky** [comment]
@martin-g, looks like there an another issue with tabs panel.
When you select a tab the 'active' class should appear on a link 'a' tag, but now I see it on a parent 'li' tag. That actually causes that no tabs are actually selected for a user.
