### ISSUE TITLE
ButtonList should not add .dropdown-item class

### ISSUE THREAD

**Issue by webD97** [l0rdn1kk0n/wicket-bootstrap#861]
In the wicket-8.x-bootstrap-4.x branch, the ButtonList adds a `.dropdown-item` CSS class to every button:

https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/cd5ed65cea93267be72f8faa871071e25625f777/bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/button/ButtonList.java#L86

This breaks the styling of ButtonGroups. You can see the effect if you manually add the class on the Bootstrap demo page: https://getbootstrap.com/docs/4.3/components/button-group/#basic-example.

I am wondering why this class is added in the first place. Why should the buttons in a button group be dropdown items?

**Comment by martin-g** [comment]
Fixed!
Thanks for the report, @webD97 !
