### ISSUE TITLE
Menu is broken in 5.0.0

### ISSUE THREAD

**Issue by solomax** [l0rdn1kk0n/wicket-bootstrap#866]
All menu links doesn't have `nav-link` CSS class, so the styling is broken
The issue is caused by this 1bda15b7411186cff1b08eb568aa8b539684a0f6 commit

**Comment by webD97** [comment]
I removed the `.nav-link` class from Buttons.Type because it is not a "type of button" (https://getbootstrap.com/docs/4.5/components/buttons/#examples) but a class specific to building menus, see https://getbootstrap.com/docs/4.5/components/navs/#base-nav. I think we should not add the class in Buttons.Type again as it issemantically incorrect.

I did a quick search in the code base on the master branch and found the [MenuButton](https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-9.x/bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/button/dropdown/MenuButton.java) class. Maybe it would be appropriate to add the `.nav-link` class there and then use this component in your code?

Edit: Hm, this class seems to be dropdown related so this might not be ideal as well.

**Comment by solomax** [comment]
From what I can see `NavbarAjaxButton`, `NavbarAjaxLink`, `NavbarButton`, `NavbarExternalLink` are all sort of buttons of type `Menu`

I see no bit deal to have this special type of navigation button

Some bigger refactoring is required to make things better alligned with bootstrap ideology

**Comment by solomax** [comment]
This issue blocks release for us
Can we agree for a quick fix, or should i revert to 5.0.0-M2?

**Comment by webD97** [comment]
I think we should work on a proper solution here i.e. a solution that works for everyone. Would shadowing the class and adding the CSS class there be an option for your release?

**Comment by solomax** [comment]
i'm with reverting to M2 :)

btw what problem are you solving with 1bda15b commit?

**Comment by webD97** [comment]
Okay :) I submitted this change because the `.nav-link` CSS class was not present in the Bootstrap 3 variant of wicket-bootstrap. When we upgraded to a wicket-bootstrap release with Bootstrap 4, this class broke our layout (it basically adds `display: block` to the button if I remember correctly). We did not find out why it was added in the first place and assumed it being a bug.

**Comment by solomax** [comment]
i see :)
OK, let's refactoring begins :)

**Comment by solomax** [comment]
Would it be OK for you 
if we will add `Buttons.type.NavLink` and will use where it is appropriate?

**Comment by mweirauch** [comment]
I am facing this issue in a `NavBar` with `NavbarButton`s. I had to explicitely add an `AttributeModifier` with the desired CSS class `nav-link`.

```
        final NavbarButton<Void> homeButton = new NavbarButton<>(HomePage.class, Model.of("Home"));
        homeButton.setIconType(FontAwesome5IconType.home_s);
        homeButton.add(AttributeModifier.append("class", "nav-link"));
```

I quick thought was to add some kind of `Buttons.Type.Nav` but this would collide with Bootstraps button definitions, which do explicitely not list a "nav" button. And as I just see @solomax has the same thought. But we'll never get rid of this once introduced. Can't think of anything more elegant.

**Comment by solomax** [comment]
Alternatively way:
All `NavbarAjaxButton`, `NavbarAjaxLink`, `NavbarButton`, `NavbarExternalLink` do have `onComponentTag` method patching classes
we can add `nav-link` to it

this method will require more careful testing

**Comment by solomax** [comment]
Just did the search of usages of `Buttons.Type.Menu` it is being used in multiple places including `ButtonBehavior`
Additional `Buttons.Type.` seems to be easiest solution :)

**Comment by webD97** [comment]
I think that would be a simple and feasible solution

**Comment by mweirauch** [comment]
Tinkered around a bit without applying any "fixes" in my demo project itself. (Only tested Navbar stuff. Might be regular menus and buttons got seriously broken.)

Also found some "strange" things in `NavbarDropDownButton` removing "nav-link" (via `Buttons.Type.Menu` enum when it still had it).

With 5.0.0:
![image](https://user-images.githubusercontent.com/1134031/90428005-a2a22000-e0c3-11ea-81a5-ab594b807466.png)

With 5.0.1-SNAPSHOT local:
![image](https://user-images.githubusercontent.com/1134031/90427756-44753d00-e0c3-11ea-96a5-66a5d3a6997e.png)

**Comment by solomax** [comment]
Shall I create PR? or are there other volunteers? :)))

**Comment by mweirauch** [comment]
I already got some parts going as can be seen from above, but likely won't manage to provide something well tested today. So just go ahead and we can have a look at it together.

**Comment by webD97** [comment]
I also do not have a lot of time right now, I'd be glad if you can do you it, @solomax

**Comment by solomax** [comment]
PR https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/867

**Comment by mweirauch** [comment]
I wen't ahead and came up with #868 based on your work @solomax and hopefuly gave enough credit where credit is due. Hope you don't mind.

I'll likely come up with a follow-up PR for fixing the broken vertical button groups when this is done.

If somebody could give the PR a try?

**Comment by solomax** [comment]
I can check it tomorrow/at the weekend, a bit busy with personal stuff :(

**Comment by mweirauch** [comment]
I guess this one can be closed then with the release of 5.0.1?

**Comment by solomax** [comment]
@mweirauch It seems fix is incomplete :(
As you can see here https://getbootstrap.com/docs/4.5/components/navbar/#supported-content
Dropdown items in navbar should have `dropdown-item` class only

wicket-bootstrap sets `nav-link dropdown-item`
and it looks differently :(

this is not show-stopper, but need to be fixed ....

**Comment by mweirauch** [comment]
Are you sure @solomax? I double checked my demo app and the Wicket Bootstrap sample application before and after the PR merge and with 5.0.1 and 5.0.2-SNAPSHOT state from the current w9b4 branch state. Can't find anything deviating from the Bootstrap docs.
Anything in your app which was introduced to fix the erroneous 5.0.0 code which is now superfluous or rather contributing to what you see?

**Comment by solomax** [comment]
Hello @mweirauch,
unfortunately yes :(
To check I've set-up to servers with same codebase and only this dependency changed `5.0.0-M2 -> 5.0.1`
And I can see the difference

I'll try to investigate and report back here ASAP (was busy on other projects ....)

**Comment by solomax** [comment]
@mweirauch Finally I found what was wrong ...

Additional class has been added in my code, `wicket-bootstrap` doesn't need additional fix
Weird enough everything was OK with `5.0.0-M2`

sorry for the noise
