### ISSUE TITLE
Bootstrap datatable example

### ISSUE THREAD

**Issue by smiesnyrobert** [l0rdn1kk0n/wicket-bootstrap#870]
Hi, i was try datatable in /datatable page but sort icons didnt show. Exists some example/component where datatable looks like [this](https://datatables.net/examples/styling/bootstrap4) with num of entries etc? 
Ver. 5.0.0
Thx.

**Comment by martin-g** [comment]
https://github.com/wicketstuff/core/tree/master/datatables-parent provides integration with DataTables.
Wicket-Bootstrap provides Bootstrap-ized versions of Wicket -core and -extensions components
