### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by FANMixco** [l0rdn1kk0n/wicket-bootstrap#892]
I discovered that the link: https://wb-mgrigorov.rhcloud.com is broken. Is it the project still alive?

**Comment by martin-g** [comment]
Yes, the project is alive!
But I (the only active maintainer) have no permissions to edit the project description.
The README is up-to-date!

**Comment by FANMixco** [comment]
Hi @martin-g , the link in the readme is broken also:
https://wb8.teliclab.info/

**Comment by mweirauch** [comment]
Sorry for chiming in in this closed ticket @martin-g, but don't you fear the danger of being able to not maintain the project? Is it possible to hand over some more permissions or even ownership to you by the original creator of the project?

**Comment by martin-g** [comment]
> Hi @martin-g , the link in the readme is broken also:
> https://wb8.teliclab.info/

@Shengche Do you still maintain the demo ?

**Comment by martin-g** [comment]
> Is it possible to hand over some more permissions or even ownership to you by the original creator of the project?

@l0rdn1kk0n ^^

**Comment by Shengche** [comment]
> > Hi @martin-g , the link in the readme is broken also:
> > https://wb8.teliclab.info/
> 
> @Shengche Do you still maintain the demo ?

Yes, I am working on it after workstation crash, give me a moment, thanks

**Comment by Shengche** [comment]
@martin-g 
Sorry for the long time, I just recreated the demo site with wicket 8 and bootstrap 4

https://wicketbootstrap.teliclab.info/

**Comment by martin-g** [comment]
Big thanks!
