### ISSUE TITLE
Boostrap-Themes content security policy

### ISSUE THREAD

**Issue by Bodyash** [l0rdn1kk0n/wicket-bootstrap#899]
Using Bootstrap.getSettings().setCssResourceReference(new BootswatchCssReference("lux"))
causing CSP warning and not loading fonts, cause font url to googleapis is hardcoded to css file.

**Comment by martin-g** [comment]
I am afraid this has to be reported upstream to the Bootswatch project.
Here we don't modify the contents of the themes.
