### ISSUE TITLE
Bootstrap 5: anyone interested?

### ISSUE THREAD

**Issue by keesvandieren** [l0rdn1kk0n/wicket-bootstrap#902]
Bootstrap 5 has been released! 

Is anybody interested in making / having a Bootstrap 5 implementation of Wicket Bootstrap?

We can do some contributions, but we cannot do the major of the effort (as we have only one small application using it).

**Comment by martin-g** [comment]
https://getbootstrap.com/docs/5.0/migration/#grid-updates

**Comment by solomax** [comment]
I was planning to spend some time to migration
@martin-g I guess we need branch and agree on new major version :)

**Comment by martin-g** [comment]
@solomax Awesome! I've just created `wicket-9.x-bootstrap-5.x` for you! 
Later we could create `wicket-10.x-bootstrap-5.x`.
I don't plan to have `wicket-8.x-bootstrap-5.x`. It is too much mainteinance for me.

**Comment by solomax** [comment]
please check https://github.com/solomax/wicket-bootstrap/tree/wicket-9.x-bootstrap-5.x for progress
too early for PR :((

**Comment by solomax** [comment]
@keesvandieren, @martin-g do we need to keep 2 sets of FontAwesome icons? Can I made only 5.x available?

**Comment by martin-g** [comment]
Only 5.x is OK!

**Comment by martin-g** [comment]
@solomax Please create PRs early and often! It would be easier to review and to help each other.

**Comment by solomax** [comment]
FTR: Here is the issue for bootstrap-confirmation plugin https://github.com/mistic100/Bootstrap-Confirmation/issues/133
Not sure what are our chances :(

**Comment by solomax** [comment]
Hello All,

our application seems to work as expected with latest `5.x` branch with https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/913 applied
I would like to get some feedback on what is not working and what can be improved :)

**Comment by reckart** [comment]
> Hello All,
> 
> our application seems to work as expected with latest `5.x` branch with #913 applied
> I would like to get some feedback on what is not working and what can be improved :)

I am also playing around with the 5.x branch you refer to. Looks like Bootstrap Select is not working yet - although the order of the script tags loading bootstrap.js and bootstrap-select.js seems to be correct in the page.

<img width="610" alt="Screenshot 2021-07-11 at 18 02 29" src="https://user-images.githubusercontent.com/1410238/125202063-45323700-e272-11eb-843a-5009a92fd0ca.png">

**Comment by solomax** [comment]
@reckart I did re-write `bootstrap-confirmation` to make it work :(

**Comment by reckart** [comment]
I am not sure I understand your comment. Do you mean that it should be working and I should be checking for a problem on my side?

**Comment by solomax** [comment]
@reckart Sorry for being unclear :(
I'm afraid the `bootstrap-select.js` might be incompatible with BS5
and you need to

- contact plugin develop and wait
- or do something similar to what I did in my PR #913 (`bootstrap-confirmation.js` ...)

**Comment by reckart** [comment]
Maybe I'l just drop BootstrapSelect and use a simple bootstrap-styled HTML select... I'm not using any if the special features of BootstrapSelect anyway... it just looked slightly better than the regular HTML select styling.

**Comment by reckart** [comment]
That said, there seems to be activity on the bootstrap-select side of things regarding BS5 support: https://github.com/snapappointments/bootstrap-select/issues/2505

**Comment by solomax** [comment]
good news :)
I would wait in such case :)

**Comment by martin-g** [comment]
I've updated the application that I use for Wicket trainings to 6.0.0-SNAPSHOT and after fixing few issues in the .html files all seems to work as before!
Thank you, @solomax !

**Comment by solomax** [comment]
good to know :))
I'll try to check some other stuff one more time later
and my work on bootstrap-confirmation is incomplete :(

**Comment by reckart** [comment]
How about doing a beta release?

**Comment by solomax** [comment]
+1 with this https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/915 PR merged :)

**Comment by martin-g** [comment]
@solomax I've missed your comment! I've just released 6.0.0-M1 without #915 
I will review it tomorrow and release 6.0.0-M2!

**Comment by martin-g** [comment]
Well, I just did it!
6.0.0-M2 has been released too!
Please create new issues/PRs for new bugs/improvements!

**Comment by ccartee** [comment]
> @reckart I did re-write `bootstrap-confirmation` to make it work :(

you did a rewrite for some specific project, or is that rewrite available somewhere?

**Comment by solomax** [comment]
@ccartee the source is open and available here: https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-9.x-bootstrap-5.x/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/confirmation/bootstrap-confirmation.js

I had no time to figure out how packing etc should work

So it's just plain js file :)

**Comment by ccartee** [comment]
you're a lifesaver :)

plain js file is fine for me.  I may fiddle with it later.

I grabbed different version on my own and had been messing around with it, but it never triggered the setContent method.  This seems to work just fine

**Comment by solomax** [comment]
glad it is useful :)

please be careful: this JS should be aligned with bootstrap (new versions of bootstrap breaks this code from time to time :(( )

**Comment by heryqk** [comment]
> @solomax Awesome! I've just created `wicket-9.x-bootstrap-5.x` for you! Later we could create `wicket-10.x-bootstrap-5.x`. I don't plan to have `wicket-8.x-bootstrap-5.x`. It is too much mainteinance for me.

Good afternoon everyone, I know this thread is a bit old but I wanted to get your thoughts on the following. We are currently running many  Wicket 8  + Wicket-Bootstrap 2.x applications on IBM WebSphere 9.x.

Unfortunately, because of that, we are stuck on JDK8 and cannot go any higher unless we change our platform. We have to look into upgrading our current Bootstrap 3.x and given that Bootstrap 4.x is end of life, we wanted to investigate going to Bootstrap 5.x. What would the lift in branching the Wicket 9  + Bootstrap 5 branch and downgrading Wicket to 8.x ? 

We could contribute the branch back to this project or we can fork the project for our own use if this causes maintenance concerns. First and foremost I wanted to get your input on feasibility and time estimate if we could allocate a skilled resource full time. 

Any input would be appreciated, 
Thank you.

**Comment by martin-g** [comment]
Hi,

Wicket 8.x is in maintenance mode!
Only security related fixes will be applied to it!
Same policy applies to Wicket Bootstrap project.

I’m afraid you will have to maintain a fork!
