### ISSUE TITLE
wicket-bootstrap-sass not working on Apple Silicon

### ISSUE THREAD

**Issue by reckart** [l0rdn1kk0n/wicket-bootstrap#914]
The current is using the last "official" release of jsass which does not support Apple Silicon. There are alternative versions of jsass out there which do support it. I tried in particular this one: https://githubmemory.com/repo/kasta-ua/jsass - and it seems to work nice as a drop-in replacement for the "official" jsass. 

It could be considered switching wicket-bootstrap-sass to the kasta-ua version.

It could also be considered to try working with upstream jsass to integrated the changes from the kasta-ua version - but not that the jsass has effectively closed shop because the underlying libsass is no longer being developed.

Another option might be to look at https://github.com/larsgrefer/dart-sass-java as a replacement for jsass or as a replacement for libsass within jsass.

**Comment by martin-g** [comment]
Fixed with https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/986

**Comment by reckart** [comment]
Looks like there was an update to the original jsass which now has Apple Silicon support and removes an annoying warning:

- https://gitlab.com/jsass/jsass/-/releases/5.11.0

**Comment by martin-g** [comment]
PR ?

**Comment by reckart** [comment]
https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/1026 ?
