### ISSUE TITLE
Popovers do not work when BS5 JQuery integration is disabled

### ISSUE THREAD

**Issue by reckart** [l0rdn1kk0n/wicket-bootstrap#924]
Bootstrap 5 no longer needs JQuery. To avoid Bootstrap 5 features interfering with other JQuery plugins, one can disable the JQuery Bootstrap integration on a per-page level by adding the attribute `data-bs-no-jquery="data-bs-no-jquery"` to the page body.

However, doing so breaks at least the Wicket Bootstrap PopoverBehavior because it uses `$(component).chain("popover", config).get()` to initialize the popover.

As much as possible, Bootstrap functionalities should be utilised without resorting to JQuery.

Cf. https://getbootstrap.com/docs/5.1/components/popovers/
Cf. https://getbootstrap.com/docs/5.1/getting-started/javascript/#jquery-events

**Comment by martin-g** [comment]
We know that BS 5 does not use jQuery!
We need PRs, not issues! :-)

**Comment by reckart** [comment]
Here you go: https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/929
