### ISSUE TITLE
current closure-compiler-unshaded version has guava, gson, javax, ant, arg4j in the jar

### ISSUE THREAD

**Issue by selckin** [l0rdn1kk0n/wicket-bootstrap#925]
the last version without them seems to be v20200830

**Comment by selckin** [comment]
https://github.com/google/closure-compiler/issues/3731

**Comment by selckin** [comment]
https://github.com/google/closure-compiler/issues/3703 makes it pretty clear they don't care or want to fix this, so maybe the feature should be dropped here

**Comment by martin-g** [comment]
@selckin  It is not clear what do you want me to do.

**Comment by selckin** [comment]
Well, having it as a normal dependency is very dangerous now, since if you add a dependency on bootstrap-extensions, it can override the version you depend on yourself depending on the order of the jars, and lead to all kinds of trouble as i'm sure you're aware

Ideally google/closure compiler would fix their dependencies, but it doesn't looks like they would be open to that from those issues, so either should go back to the old version that doesn't bundle a version of gson/guava/ant etc in the jar,
or possibly just remove the GoogleClosureJavaScriptCompressor class and the dependency, unless someone wants to put time into fixing it

Or maybe you can make the dependency optional, and mark GoogleClosureJavaScriptCompressor deprecated, then users would get a warning, and non users would not get bitten by the bundled dependencies

All kinda depends how much time you're willing to put into it, i can make a pull requests for whatever you think is best if you want

**Comment by martin-g** [comment]
IMO the best would be to revert to the safe version.
Please send a PR!

**Comment by martin-g** [comment]
Or maybe we could use the -shaded version: https://search.maven.org/artifact/com.google.javascript/closure-compiler/v20210907/jar ?!

**Comment by selckin** [comment]
I agree it should work & be the best option , but I had found https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/797 

i don't understand that issue or how what it describes is possible

**Comment by martin-g** [comment]
@ursjoss Ping!

**Comment by ursjoss** [comment]
The problem with the shaded version is that it seems to not be properly shaded (see [here](https://github.com/google/closure-compiler/issues/3523)). That's why we moved to the unshaded variant in  #797. Which worked, as @selckin pointed out, until `v20200830`. Since `v20200920`, however, it again contains the `gson` classes, bringing back the issues.

**Comment by ursjoss** [comment]
On the wicket-9.x branch, we're still on version v20200406, which still works.
PR #905 bumped the closure-compiler to v20210601, was merged to wicket-9.x-bootstrap-4.x.
PR #908 introduced that version into wicket-9.x-bootstrap-5.x.

I would also suggest to downgrade to a safe version, either to the presumably working v2020830 or even the proven v20200406.

**Comment by selckin** [comment]
Thanks the quick update & resolution
