### ISSUE TITLE
Font Awesome 5 - Pro version

### ISSUE THREAD

**Issue by vrozkovec** [l0rdn1kk0n/wicket-bootstrap#932]
Hi, @martin-g would you accept PR that would contain `FontAwesome5ProIconType` implementation, which would contain all icons, including those _pro_ ones of Font Awesome 5.x? 

Each developer would then only need to include those _pro_ assets, assets themselves would not be part of this PR, of course.

**Comment by martin-g** [comment]
Yes, I think it is fine!
Just make sure all this is well explained in its javadoc!

**Comment by martin-g** [comment]
Closing since there is no interest.
