### ISSUE TITLE
Summernote 0.8.12 does not work in Wicket Deployment Mode

### ISSUE THREAD

**Issue by keesvandieren** [l0rdn1kk0n/wicket-bootstrap#941]
Summernote 0.8.11 works fine, but Summernote 0.8.12 is broken in with RuntimeConfigurationType DEPLOYMENT.

Wicket Bootstrap version: 5.0.5 

Both work well with RuntimeConfigurationType DEVELOPMENT.

I tried to reproduce this with bootstrap-samples, but failed as the samples don't work with ConfigurationType DEPLOYMENT. Created #940 for that.

Error in my console:
![image](https://user-images.githubusercontent.com/863966/143937312-7c3f155f-5c24-435e-a6d0-5eb51241276d.png)

In my Gradle project, downgrading to Summernote 0.8.11 seems to resolve the problem:

```
    implementation 'org.webjars.bower:summernote:0.8.11'
```

Once #940 is resolved, I can try if I can reproduce it in bootstrap-samples too

**Comment by martin-g** [comment]
Fixed!
Thanks for the report, @keesvandieren !
