### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by solomax** [l0rdn1kk0n/wicket-bootstrap#942]
Bootstrap has RTL support https://getbootstrap.com/docs/5.1/getting-started/rtl/
would be good to add RTL support to `wicket-bootstrap` as well :))

**Comment by solomax** [comment]
@martin-g I would like to get some help with this task :)
It seems `ITheme` and all child need to be changed to render different CSS based on Session locale

is it OK? or maybe you can propose better solution?
Does it worth to add `isRtl` method to wicket `Session` ?

The code to determine RTL might look like this: https://github.com/apache/openmeetings/blob/2070273b0db7da88d5dbac66cde01746942bbe6b/openmeetings-db/src/main/java/org/apache/openmeetings/db/util/FormatHelper.java#L68

**Comment by martin-g** [comment]
I think it would be better to use Session's metadata. This way you could add custom properties to any Session without modifying the Session source code.
You could add a Util class or just a `default` method in `ITheme` to get the RTL from the Session metadata. Modifying all ITheme impls is fine!

**Comment by solomax** [comment]
My idea was to modify `public Session setLocale(final Locale locale)` https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/Session.java#L602

and add code to set `isRtl` so all wicket users can use this :)

**Comment by martin-g** [comment]
Please create a ticket and a PR, and we'll see :-)

**Comment by solomax** [comment]
I've started to work on this issue :)
The main issue for me so far is bootswatch: https://github.com/thomaspark/bootswatch/issues/1116

**Comment by martin-g** [comment]
@solomax Can we close this ticket ?

**Comment by solomax** [comment]
I'd love to have this feature
BUT I'm blocked with bootswatch :(

**Comment by solomax** [comment]
please see #997 :)

**Comment by martin-g** [comment]
@solomax Can we close this ?
