### ISSUE TITLE
Summernote editor pull request.

### ISSUE THREAD

**Issue by RLStokes** [l0rdn1kk0n/wicket-bootstrap#943]
Hi,

Would it be possible to cherry pick this commit 
https://github.com/l0rdn1kk0n/wicket-bootstrap/commit/056261645f5e5c9613a11de7a51be2fc7f65cd6e

From this PR
https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/878

into these branches
wicket-9.x
wicket-9.x-bootstrap-5.x
wicket-9.x-bootstrap-4.x
wicket-8.x-bootstrap-4.x

or should I open up a new pull request for each of the branches?

Thanks.

**Comment by martin-g** [comment]
I've cherry-picked it to `wicket-9.x`, `wicket-9.x-bootstrap-5.x` and `wicket-9.x-bootstrap-4.x`!
