### ISSUE TITLE
CheckBoxX not compatible with JQuery 3

### ISSUE THREAD

**Issue by reckart** [l0rdn1kk0n/wicket-bootstrap#946]
Looks like the CheckBoxX component in the wicket bootstrap extensions is not compatible with JQuery 3.

For one, when I try starting with a tri-state CheckBoxX, the checkbox starts out rendering in "false" state instead of "indeterminate" state. Debugging leads to the JS initCheckbox method of CheckBoxX where this line is called:

```
                val = $el.prop('indeterminate') ? options.valueNull : options.valueUnchecked;
```

And even though the value sent by the server is `''` and the value attribute in the server-generated HTML is empty, `$el.prop('indeterminate')` returns `false` here. I believe this is a regression from JQuery 2 to JQuery 3, but I did not verify.

The next problem is that that when the JS code calls `$el.trigger('change');`, it seems that the AJAX call to the server and the triggering of the `change: function ()` in CheckBoxX actually happen simultaneously. That means that the value of the component which is committed in `change: function ()` is not reflected in the AJAX call (which still has the old value).

**Comment by martin-g** [comment]
Would you want to test with https://github.com/kartik-v/bootstrap-checkbox-x/releases/tag/v1.5.7 ?
Update the CSS/JS files at https://github.com/l0rdn1kk0n/wicket-bootstrap/tree/wicket-9.x/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/form/checkboxx and send a PR if the issue is fixed.
Thank you!

**Comment by reckart** [comment]
I am currently not using CheckBoxX through Wicket Bootstrap anymore (due to this issue) and presently have no plan to go back to using it.

**Comment by martin-g** [comment]
The samples [application](http://localhost:8080/checkboxes) works just fine with jQuery 3.6.0 in wicket-9.x-bootstrap-[45].x branches!
