### ISSUE TITLE
Bootstrap-confirmation is broken because of Popper

### ISSUE THREAD

**Issue by solomax** [l0rdn1kk0n/wicket-bootstrap#951]
Latest `M7` release contains broken `confirmation`
After some digging I find-out this is because we have `popper` as additional dependency

The modern way is to drop it and use `bootstrap.bundle` instead
(see for ex. here https://stackoverflow.com/a/72336371)

Shall I proceed with such change?
Or Maybe it would be better (for whatever reason) have this behavior configurable?

@martin-g, @ursjoss WDYT? :)

**Comment by solomax** [comment]
According to https://getbootstrap.com/docs/5.1/getting-started/introduction/#separate
we can also bump popper version `2.9.3 -> 2.10.2` (and should keep an eye on it)

**Comment by ursjoss** [comment]
I don't have any experience with popper, but that plan sounds good IMHO. Only blocker right now: the newest version of popper available on maven-central is 2.9.3, we'd have to raise an issue in the [repo](https://github.com/webjars/popper.js).

It seems that popper later became [floatingui](https://floating-ui.com), but no idea how that relates to bootstrap.

**Comment by solomax** [comment]
I would use bundle instead of having 2 JS files being loaded together all the time :)

**Comment by solomax** [comment]
@martin-g WDYT?
shall we keep `bootstrap+popper` (with the possibility to have version conflict)
or
shall we move to `bootstrap-bundle`?

**Comment by solomax** [comment]
@ursjoss, @martin-g could you please take a look at PR? :))

**Comment by martin-g** [comment]
Added my comments to the PR.
Thanks, @solomax !

**Comment by ursjoss** [comment]
Looks good to me, but tbh, I don't have experience with this.
