### ISSUE TITLE
BootstrapMultiSelect shows empty list without any options.

### ISSUE THREAD

**Issue by sibiarunachalam** [l0rdn1kk0n/wicket-bootstrap#952]
Hi guys, 
We are working to implement bootstrap-select in Wicket + Bootstrap 4.x application.
But, the BootstrapMultiSelect shows empty list without any options.
I inspects the rendered html page, it seems everything ok and has all the options . 

Java
`new BootstrapMultiSelect<String>("multiSelectItems", getMultiSelectItems());`

HTML
`<select class="form-control selectpicker"
                    wicket:id="multiSelectItems"
                    multiple="multiple">
            </select>`

Could you help me to identify and fix the problem?

Components used in our  project:

1. Bootstrap 4.x
2. JQuery 3.6.0 
3. Wicketstuff-select2

Note: It works as expected in simple Wicket quickstart project.

**Comment by sibiarunachalam** [comment]
Additional information, this script is not loaded in my webapp whereas it is loaded in Wicket Quickstart project.
`<script type="text/javascript" nonce="">
/*<![CDATA[*/
Wicket.Event.add(window, "domready", function(event) { 
$('#bootstrapMultiSelect1').selectpicker({"multiple":true});;
Wicket.Event.publish(Wicket.Event.Topic.AJAX_HANDLERS_BOUND);
;});
/*]]>*/
</script>`

**Comment by martin-g** [comment]
https://lists.apache.org/thread/2nwklfywck7llwxozk0nw8q67rj05rjf
