### ISSUE TITLE
BootstrapFileInput may not detect bootstrap version

### ISSUE THREAD

**Issue by reckart** [l0rdn1kk0n/wicket-bootstrap#957]
The `BootstrapFileInput` uses `FileinputJsReference` to load its JS code. This JS code auto-configures itself depending on which bootstrap version is being used, e.g. to render button groups properly across versions.

However, the `FileinputJsReference` has no dependency on `de.agilecoders.wicket.core.settings.IBootstrapSettings.getJsResourceReference()` which may cause bootstrap to be loaded only after the `FileinputJsReference` has (wrongly) detected BS, causing rendering errors.

```
    @Override
    public List<HeaderItem> getDependencies() {
        return Dependencies.combine(
                super.getDependencies(),
                CssHeaderItem.forReference(FileinputCssReference.INSTANCE),
                JavaScriptHeaderItem.forReference(Application.get().getJavaScriptLibrarySettings().getJQueryReference()));
    }
```

Observed in: 6.0.0-M8 with BS 5.2.0

**Comment by martin-g** [comment]
Waiting for the PR ...

**Comment by reckart** [comment]
Ok, will prepare :)

**Comment by reckart** [comment]
https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/958
