### ISSUE TITLE
navbar toggle button does not open in bootstrap 5

### ISSUE THREAD

**Issue by subes** [l0rdn1kk0n/wicket-bootstrap#968]
`data-target` needs to be `data-bs-target` according to documentation: https://getbootstrap.com/docs/5.2/components/navbar/#nav

**Comment by martin-g** [comment]
Fixed with https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/969

**Comment by solomax** [comment]
This one can be closed? :)
