### ISSUE TITLE
What is expected timeline to get final release of 6.x for wicket-9.x-bootstrap-5.x

### ISSUE THREAD

**Issue by sibiarunachalam** [l0rdn1kk0n/wicket-bootstrap#971]
Hi guys,
When will we get 6.x for wicket-9.x-bootstrap-5.x?

**Comment by reckart** [comment]
What do you mean? A release supporting Bootstrap 6? A release based on Wicket 10? Both are not released yet.

**Comment by martin-g** [comment]
He/She means Wicket-Bootstrap 6.x (based on Wicket 9.x and Bootstrap 5.x).
I am OK to release 6.0.0 if at least 3 users confirm here that they use it and it works fine for them!

**Comment by reckart** [comment]
I've been using 6.0.0-Mx versions since Aug 2021 in https://github.com/inception-project/inception - currently using 6.0.0-M8. For what it's worth, it works for me - I only use a relatively small part though. Mostly Icons, FileInput ,Popovers, a few behaviors, the occasional radio group.

**Comment by solomax** [comment]
Let me update bootstrap and check please :)

**Comment by solomax** [comment]
Unfortunately I need more time https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/972
Sorry for delay

**Comment by martin-g** [comment]
#972 has been merged!
@sibiarunachalam Could you please test 6.0.0-M9-SNAPSHOT ?

**Comment by sibiarunachalam** [comment]
Hi @martin-g 
We already have started migrating from 5.x to 6.x with 6.0.0-M8, so far no major issues.
Will verify 6.0.0-M9-SNAPSHOT as well.
Thanks guys for your quick feedback.

**Comment by sibiarunachalam** [comment]
Hi guys,
I have done some basic test with 6.0.0-M9-SNAPSHOT. It works as in 6.0.0-M8.

**Comment by solomax** [comment]
Time to release? :))

**Comment by reckart** [comment]
> Time to release? :))

👍 - after the release is before the release anyway ;)

**Comment by martin-g** [comment]
6.0.0 has been released and soon will be available in Maven Central!
