### ISSUE TITLE
NavbarAjaxLink missing nav-link class in versions 5 and 6

### ISSUE THREAD

**Issue by nvolpini** [l0rdn1kk0n/wicket-bootstrap#976]
NavbarAjaxLink should add "nav-link" to the class attribute.

All other Navbar link components work fine.

**Comment by solomax** [comment]
@martin-g would it be OK for add
```
component.add(new CssClassNameAppender("nav-link"));
```

to https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-9.x-bootstrap-5.x/bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/navbar/Navbar.java#L288 ?

**Comment by martin-g** [comment]
Sounds good! This is how it is done for `nav-item` now.

**Comment by reckart** [comment]
@martin-g @solomax apparently, the changes for this issue have been merged, so the issue could be closed.
