### ISSUE TITLE
DropDownAlignmentBehavior must be updated for bootstrap 5

### ISSUE THREAD

**Issue by nvolpini** [l0rdn1kk0n/wicket-bootstrap#977]
Bootstrap 5 have new alignment options: dropdown-menu-start and dropdown-menu-end according to https://getbootstrap.com/docs/5.2/components/dropdowns/#responsive-alignment

This file must be updated: [DropDownAlignmentBehavior.java](https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-9.x-bootstrap-5.x/bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/button/dropdown/DropDownAlignmentBehavior.java)

I'm updating my application from bootstrap 3 to bootstrap 5 (wicket-bootstrap 2.x to 6.x) but it seems that wicket-bootstrap 6 is not production ready yet or at least not tested... anyway, I'm opening new issues for the problems I find. 

I'm not sure if is possible for me to send corrections directly to this repo. If opening issues is not the best way, please give me some pointers on how to contribute with corrections directly.

Thanks.

**Comment by martin-g** [comment]
> If opening issues is not the best way, please give me some pointers on how to contribute with corrections directly.

Pull Requests! ;-)

**Comment by solomax** [comment]
According to the docs there can be multiple "align" classes, would it be OK if I'll refactor this class a bit? :))

**Comment by reckart** [comment]
@martin-g @solomax apparently, the changes for this issue have been merged, so the issue could be closed.
