### ISSUE TITLE
new version wicket-10.x

### ISSUE THREAD

**Issue by solomax** [l0rdn1kk0n/wicket-bootstrap#980]
It seems we need new branch ;))

```
java.lang.NoClassDefFoundError: org/apache/wicket/util/time/Duration
	at de.agilecoders.wicket.webjars.settings.WebjarsSettings.<init>(WebjarsSettings.java:50)
	at de.agilecoders.wicket.webjars.WicketWebjars.install(WicketWebjars.java:66)
```

while trying to use wicket-bootstrap

**Comment by martin-g** [comment]
`wicket-10.x-bootstrap-5.x` has been created!
Please send a PR to upgrade it to Wicket 10-SNAPSHOT.

**Comment by martin-g** [comment]
I will do the same for wicket-webjars and wicket-jquery-selectors
**Update**: `wicket-10.x` have been created for both.
