### ISSUE TITLE
Icons from bootstrap 5 not displayed properly 

### ISSUE THREAD

**Issue by philipjebaseelan** [l0rdn1kk0n/wicket-bootstrap#982]
1. Items such as form-select, radio button, check boxes and the btn-close class for the modal window
2. The icons are not displayed, an error that it violates the Content Security Policy is printed on the console.
3. Under the css for the classes mentioned above the background-image is being loaded with a url data:
4. Is there a work around for this without changing the Content security policy.

**Comment by solomax** [comment]
You have to configure or disable CSP ....

**Comment by martin-g** [comment]
Add `getCspSettings().blocking().disable();` to YourApp#init() method.

**Comment by philipjebaseelan** [comment]
We wont be able to do that as it is a security violation to us. Is there any other option to this?

**Comment by solomax** [comment]
Icons works for us as expected with configured CSP
@philipjebaseelan  please create quickstart illustrating the issue
