### ISSUE TITLE
Update bootstrap fileinput

### ISSUE THREAD

**Issue by reckart** [l0rdn1kk0n/wicket-bootstrap#983]
The `piexif.js` file that is part of the plugins for the file input component has apparently been sourced from PHPFusion and/or is used by PHPFusion as well. In particular, it is used by a PHPFusion version which is flagged in a CVE. Because Wicket Bootstrap Extensions is also using `piexif.js`, some security scanner systems raise a warning about Wicket Bootstrap 6.0.0, which is a red flag for some downstream users.

The latest PHPFusion includes an updated version of the `piexif.js` file which has some minimal changes over the version currently being used by Wicket Bootstrap 6.0.0. Upgrading Wicket Bootstrap 6.0.0 to that file should silence the security scanner warnings.

Actually, it would probably make sense to update to the latest https://github.com/kartik-v/bootstrap-fileinput directly instead of pulling code from PHPFusion.

**Comment by reckart** [comment]
@martin-g thanks for merging all my PRs :) It would be most excellent if we could have a bug-fix or minor release with these changes, WDYT?

**Comment by martin-g** [comment]
6.0.1 is on its way to Maven Central!
