### ISSUE TITLE
Split bootstrap-extension module into per-third-party-library modules

### ISSUE THREAD

**Issue by reckart** [l0rdn1kk0n/wicket-bootstrap#985]
The `bootstrap-extension` has a pretty large dependency footprint - some of the third-party dependencies are even embedded instead of used through Maven dependencies. That means, a downstream user will typically get a large package of which they only use a small part.

To avoid imposing this large footprint on downstream users, it would be nice of the `bootstrap-extension` module would be split up into multiple modules, e.g. `bootstrap-extension-fileinput`, `bootstrap-extension-datepicker`, `bootstrap-extension-fontawesome`, etc.

**Comment by martin-g** [comment]
Closing because no one seems to be interested in doing the work.
