### ISSUE TITLE
[wicket-9.x-bootstrap-4.x] TooltipValidation doesn't work

### ISSUE THREAD

**Issue by keesvandieren** [l0rdn1kk0n/wicket-bootstrap#989]
TooltipValidation on https://wicketbootstrap.teliclab.info/validation/tooltip (probably bootstrap 5) works as expected.

With branch  wicket-9.x-bootstrap-4.x the same example doesn't work.

Steps to reproduce:

* in bootstrap-parent, change wicket-webjars.version to `<wicket-webjars.version>3.0.4</wicket-webjars.version>`
* Build the project
* from IDEA, run Start to run the examples
* Go to http://localhost:8080/validation/tooltip shows the forms; clearing the textinputs and clicking submit won't show the tooltips.

Workaround: switch to wicket-9.x-bootstrap-5.x.

Is it still worth to fix the issue, or is bootstrap-4.x in maintenance mode?

How hard is the update to bootstrap-5.x  branch?

**Comment by martin-g** [comment]
https://wicketbootstrap.teliclab.info/validation/tooltip is using 4.2.1.



> Is it still worth to fix the issue, or is bootstrap-4.x in maintenance mode?

I guess - yes. If you send a PR I will review+merge it and make a new release.



> How hard is the update to bootstrap-5.x branch?

It depends what you use from BS4. Some BS plugins do not provide new versions for BS5 and are either removed or replaced with something else.

**Comment by keesvandieren** [comment]
We have taken the road to upgrade and fixed bootstrap-select to work with Bootstrap 5 instead :-). See PR #990

**Comment by keesvandieren** [comment]
Can we close this issue? Do we want to support old bootstrap, old wicket?

**Comment by martin-g** [comment]
If you don't plan to send a PR for Bootstrap 4.x then we can close it!

**Comment by keesvandieren** [comment]
I won't send a PR. Lets focus on Wicket 9, 10 with Bootstrap 10

**Comment by keesvandieren** [comment]
Closing
