### ISSUE TITLE
[wicket-9.x-bootstrap-5.x] Alert close, hide-after is not working

### ISSUE THREAD

**Issue by keesvandieren** [l0rdn1kk0n/wicket-bootstrap#991]
Reproduction:

* check out correct branch
* On page `IssuesPage`, after `NotificationPanel` line, add this line: `info("Feedback for you!");`
* Run Start, navigate to `http://localhost:8080/issues`
* After 5 seconds, JavaScript error is shown on console and Feedback panel is not closed.

**Comment by solomax** [comment]
@martin-g I'll try to check this one before release :)

**Comment by keesvandieren** [comment]
Is this issue still relevant? Which branches do we want to support?

**Comment by solomax** [comment]
This one should be fixed (and, I believe, merged :)))

**Comment by martin-g** [comment]
To merge what ? There are no open PRs at the moment.

**Comment by martin-g** [comment]
> Which branches do we want to support?

Any branch that you need with Bootstrap 4.x/5.x. Just send a PR!

**Comment by solomax** [comment]
Fix for this issue was commited: https://github.com/l0rdn1kk0n/wicket-bootstrap/commit/b0e98ad1cddcbb884a939990b749670449cc1dba

and released :)

I believe issue can be closed :)
