### ISSUE TITLE
7.0.0 not on Maven Central?

### ISSUE THREAD

**Issue by ilgrosso** [l0rdn1kk0n/wicket-bootstrap#996]
It seems there is no `7.0.0` version on https://central.sonatype.com/artifact/de.agilecoders.wicket/wicket-bootstrap-core/6.0.4/versions

**Comment by ilgrosso** [comment]
@martin-g can you check, please? Thank you!

**Comment by martin-g** [comment]
Thanks, @ilgrosso !
It is available now: https://central.sonatype.com/artifact/de.agilecoders.wicket/wicket-bootstrap-core/7.0.0

**Comment by ilgrosso** [comment]
Thank you very much for quick reaction :+1:
